### ISSUE TITLE
Add Accessibility Guides to Contributing.md

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#102]
**Is your feature request related to a problem? Please describe.**

We currently do not have any reference to our Accessibility guidelines within Psammead.

When you contribute to this component, whether you're a developer, UX designer, tester, or product owner, we expect certain processes to be followed!

We should add our process to the Psammead Contributing guide: https://github.com/BBC-News/psammead/blob/latest/CONTRIBUTING.md

**Describe the solution you'd like**
To  add a high-level summary of Assistive Tech support into Psammead's Contributing.md

- BBC News has a detailed guides available on this publicly accessible site https://bbc-news.github.io/accessibility-news-and-you/
<ul>
  <li><a href="https://bbc-news.github.io/accessibility-news-and-you/accessibility-news-and-business-analysts">Business Analyst</a></li>
  <li><a href="https://bbc-news.github.io/accessibility-news-and-you/accessibility-news-and-designers">Designer</a></li>
  <li><a href="https://bbc-news.github.io/accessibility-news-and-you/accessibility-news-and-developers">Developer</a></li>
  <li><a href="https://bbc-news.github.io/accessibility-news-and-you/accessibility-news-and-product-owners">Product Owner</a></li>
  <li><a href="https://bbc-news.github.io/accessibility-news-and-you/accessibility-news-and-project-managers">Project Manager</a></li>
  <li><a href="https://bbc-news.github.io/accessibility-news-and-you/accessibility-news-and-testers">Tester</a></li>
</ul>

We should reference these guides. We should recommend that people adding or updating existing components to refer to these processes. The Developer and Tester guides are particularly relevant when creating and reviewing PRs. The other guides are useful to link to for a whole overview of how Accessibility should be considered. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: This is documentation. It should be easily understood by Devs, Testers, Product Owners, UX Designers & Business Analysts. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Similar to #103 - just linking to a different part of the Accessibility, News and You.
