### ISSUE TITLE
Add Accessibility Swarm process to Psammead Contributing guide

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#103]
**Is your feature request related to a problem? Please describe.**
We currently do not refer to our Accessibility swarm process within Psammead.

We should add a `Accessibility_Swarm.md`, that can be referenced in the `Contributing.md` file. 

**Describe the solution you'd like**
Add a `Accessibility_Swarm.md`, which explains what happens during an accessibility swarm focusing on a new component. It should include 
- Disciplines involved and the process
- What the checklist of tasks is. Turning the tables here into markdown: ( )
- How we prioritise testing on certain devices and Assistive Technologies by referring to the categorisation of Assistive Tech here: https://github.com/BBC-News/psammead/issues/99
- What the outcomes of the swarm are.

This write-up should be in the Psammead repository and not just linking to external resources. 

**Describe alternatives you've considered**
If this information existed on https://bbc-news.github.io/accessibility-news-and-you/, we could just refer to it. However, it currently does not exist on this site.  

@greenc05 has a slideshow version introducing an Accessibility Swarm. It would be good to contact her before picking up this issue. 

**Testing notes**
[Tester to complete]

Dev insight: This is documentation. It should be easily understood by Devs, Testers, Product Owners, UX Designers & Business Analysts. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Blocked pending the Accessibility Swarm being added to the https://bbc-news.github.io/accessibility-news-and-you/ site.

**Comment by ChrisBAshton** [comment]
Similar to #102 - just linking to a different part of the Accessibility, News and You.

**Comment by ChrisBAshton** [comment]
Raised https://github.com/BBC-News/accessibility-news-and-you/issues/16.

**Comment by greenc05** [comment]
Please see https://bbc-news.github.io/accessibility-news-and-you/accessibility-swarms
