### ISSUE TITLE
Touch area in psammead-consent-banner is too small

### ISSUE THREAD

**Issue by jamesbhobbs** [BBC-archive/psammead#1040]
**Describe the bug**
Touch area is too small

**To Reproduce**
Rum lighthouse see error. The link touch area is too small.

**Expected behaviour**
It's large enough to meet industry usability standards.

**Screenshots**
n/a
**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a
**Additional context**
n/a

**Comment by benjaminhobbs** [comment]
Once done we must increase our lighthouse scores in simorgh-infrastructure

**Comment by jamesbhobbs** [comment]
Cannot reproduce
