### ISSUE TITLE
Update Readme package publishing instructions

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#109]
**Describe the bug**
Currently the Readme's Publishing Packages suggests we should publish all of the packages at the same time: https://github.com/BBC-News/psammead#publishing-packages

We should update it to state: 

**Set up your account**

- Create an npm account with your bbc email address. 
- In your profile settings, set up Two Factor Authentication. Enable it for authorization and publishing. 
- Back up your recovery codes for your account
- Join the BBC npm org by following the process here: https://github.com/bbc/npm When you're added to the org and signed in, you should be able to see all public and private `@bbc` packages here: https://www.npmjs.com/settings/bbc/packages

**Publishing**

- In your terminal, run `npm login` and follow the steps for authentication
- `npm publish packages/<PATH_TO_PACKAGE>`
e.g. `npm publish packages/components/psammead-paragraph`

**Making package public**

- `npm access public @bbc/<PACKAGE_NAME> --otp=<YOUR_2FA_CODE>`

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/psammead/labels/bug)

**Comment by bcmn** [comment]
>npm publish packages/<PATH_TO_PACKAGE>
>e.g. npm publish packages/components/psammead-paragraph

I think this line should also include the `--otp=<YOUR_2FA_CODE>`, as I got an error & re-prompted for it. 😄
