### ISSUE TITLE
Describe why this is called Psammead

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#11]
Simorgh had to do a similar thing ;-) https://github.com/BBC-News/simorgh

**Comment by ChrisBAshton** [comment]
...and how to pronounce it (I'm still calling it "sam-eed")

**Comment by dr3** [comment]
>*I'm still calling it "sam-eed"* 

Ive always gone with "sam-me-ad"

**Comment by pjlee11** [comment]
# Psammead

Pronounced as `sam-me-ad`

"The Psammead, also known as Sand Fairy, is a sapient magical creature once encountered by five children in a gravel pit".

_Perfectly sharable atomically modular magically engineered abstract doodads_ - This is still just a bad joke

**Comment by dr3** [comment]
![image](https://user-images.githubusercontent.com/11341355/49439094-0da8a780-f7b8-11e8-8a78-e83028e34d78.png)

**Comment by ChrisBAshton** [comment]
Thanks Phil - that's a great start! https://github.com/BBC-News/psammead/issues/11#issuecomment-444060436

Though it doesn't explain _why_ we went for it - I feel like the book was a sequel to another BBC repo or something...? Would be good to get that documented 😂

**Comment by pjlee11** [comment]
It's a mythical creature similar to simorgh. It grants wishes. It's from a BBC programme (`Five children and it`).

*The place you come to and wish for a component that supports every requirement across BBC Online…*

**Comment by ChrisBAshton** [comment]
**P**lace (that) **S**upports (requirements) **A**cross (**M**ythical) (**M**ythical again) **E**very **A**spect of BBC **D**&E.

**Comment by dr3** [comment]
# Psammead

Pronounced as `sam-me-ad`

"The Psammead, also known as Sand Fairy, is a sapient magical creature once encountered by five children in a gravel pit". 

_Perfectly sharable atomically modular magically engineered abstract doodads_ - This is still just a bad joke
