### ISSUE TITLE
Bumper bot wanted for non-psammead package updates

### ISSUE THREAD

**Issue by jamesbhobbs** [BBC-archive/psammead#1156]
**Is your feature request related to a problem? Please describe.**
Subsequent to https://github.com/bbc/psammead/issues/888 we want a more generic solution as we don't believe dependabot is good enough, because it opens a PR per package.

**Describe the solution you'd like**
Will not try to answer until the blocking issue https://github.com/bbc/psammead/issues/888 is resolved.

**Describe alternatives you've considered**
Build the ideal solution up front.

**Testing notes**
No testing will be needed

**Additional context**
n/a

**Comment by dr3** [comment]
I think #888 can help resolve this. In my mind for #888, we have three parts
1) Get a list of all newly published psammead packages
2) For each newly published package, find where its used in psammead, update it
3) Run updateSnapshots and make a PR

For this issue, 2 and 3 can be reused. 
We somehow find out if external dependancies have been updated
2) For each dependancy, find where its used in psammead, update it
3) Run updateSnapshots and make a PR

The only difference, #888 gets a list of what to bump from publishing them, this gets its list from some new source of newly published npm packages globally.

**Comment by hindsc52** [comment]
closing in favour of #888

**Comment by chris-hinds** [comment]
Closed in error, re-opening

**Comment by jamesbhobbs** [comment]
Talos now does this, although isn't documented, the issue for explaining how it works is here: https://github.com/bbc/psammead/issues/1861
