### ISSUE TITLE
Update consent banner link and button text

### ISSUE THREAD

**Issue by greenc05** [BBC-archive/psammead#1211]
**Is your feature request related to a problem? Please describe.**
Link and button text does not make sense out of context, this isn't a great UX for a screen reader user

**Describe the solution you'd like**
- Update link and button text so they make sense out of context - Text to be confirmed by Natalie/Jim
- Ask someone to request translations if need for WS sites for updated link and button text

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by sareh** [comment]
@greenc05 What do you mean precisely by `Link and button text does not make sense out of context`?

**Comment by greenc05** [comment]
@sareh A screen reader user can view a list of links out of context, we want to update the link/button text so it makes sense in this situation e.g. out of context. Awaiting confirmation:

1) Yes, I agree > **Yes, I agree to cookies**
2) No take me to settings > **No take me to cookie settings**
3) Ok > **Ok, close privacy and cookies update**
4) Find out what’s changed > **Find out what’s changed with privacy and cookies**

**Comment by sareh** [comment]
@greenc05 OK, thank you, Catharine! 
Is there a reason why such text shouldn't also visible? I'd imagine for usability it'd be clearer to have the text `Yes, I agree to cookies`. It isn't just useful for screen-reader users.

**Comment by greenc05** [comment]
@sareh yep, it should be visible to all users

**Comment by joshcoventry** [comment]
@greenc05 I think we can close this now?
