### ISSUE TITLE
Add timezone support to timestamps

### ISSUE THREAD

**Issue by j-pendlebury** [BBC-archive/psammead#1235]
Blocked on https://github.com/bbc/simorgh/issues/2565

**Is your feature request related to a problem? Please describe.**
Timestamps 2: the return of timezones.

We have basics timestamps, but now it's time to actually add some complexity to them to make user experience better.

**Describe the solution you'd like**
Use [moment's timezone](https://momentjs.com/timezone/docs/#/using-timezones/parsing-in-zone) support for Igbo, Yoruba, and Pidgin.

**Describe alternatives you've considered**
Not using moment and crying about the work to be done 😢 

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
[Timestamp Info Grid](https://www.dropbox.com/s/st883m5a8u9hi3a/WS%20Home%20Pages%20%28Live%29.xlsx?dl=0)
WSFRONTPGS-120

**Comment by dr3** [comment]
![](https://media.giphy.com/media/LpkLWXTp0v0qy70xPp/giphy.gif)

Caution all who go here 🙈 

Our current timestamp support wont scale, it currently filters out all timezones except `London`, this wont work for multiple services as they're in the vendor bundles, meaning any added are downloaded by all services. Doing this for multiple services means we need to import timezones into the service bundles. Easy? lol nope. Moments timezone data is a GIANT json file, making it so you cant just import a single one (ikr its dumb). We most likely need a solution that allows us to build timezone data into our service bundles at build time and then attach it to moment.

**Comment by david-boydell** [comment]
~It seems the three services do not have a timezone listed in the spreadsheet. My understanding was that we would default to GMT if this was the case; the next service out, Thai, is also GMT acording to the spreadsheet.~

~We can probably run with it as it is for now and create an issue for Drew's comment above to address further down the line.~

I'll double check with Jon.

**Comment by david-boydell** [comment]
The spreadsheet has been updated. These are now using `Africa/Lagos` for moment -timezone.

**Comment by dr3** [comment]
Have raised https://github.com/bbc/simorgh/issues/2565 for the above issue

**Comment by j-pendlebury** [comment]
Blocked on https://github.com/bbc/simorgh/pull/2617 and https://github.com/bbc/simorgh/issues/2565

**Comment by dr3** [comment]
This psammead work isn't technically blocked. Receiving a `timezone` string e.g. `Europe/London` in psammead-timestamp-container can then use this string. For now work on the assumption that the timezone is availible to use, and receiving a 'timezone' prop, use it :)

**Comment by j-pendlebury** [comment]
@dr3 agreed. I will remove the label, so we can get some of this work done.

**Comment by ghost** [comment]
We are already using the `timezone` prop in `timestamp-container`. What else needs to be done apart from https://github.com/bbc/simorgh/issues/2565

**Comment by ghost** [comment]
Do we know what timezone maps to which service?
Update: I have seen the spreadsheet containing the mappings.

**Comment by dr3** [comment]
This issue can be closed, psammead timestamp container already has timezone passing support. The rest of this work can be done in https://github.com/bbc/simorgh/issues/2794
