### ISSUE TITLE
Add `npm publish --dry-run` to Psammead CI

### ISSUE THREAD

**Issue by pjlee11** [BBC-archive/psammead#1239]
**Is your feature request related to a problem? Please describe.**
Currently it is possible for our CI to pass but the `npm publish` command fails. For example you could have a space ` ` in the version name and it'll fail (totally wasn't my [typo](https://github.com/bbc/psammead/pull/1238/files)). 

**Describe the solution you'd like**
Add `npm publish --dry-run` to the Psammead CI steps to catch any obvious failures when the deployment attempts to publish a package. This could use `lerna` so that it dry run publishes each package changed in the PR.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: No QA needed

**Additional context**
- https://docs.npmjs.com/cli/publish
```
[--dry-run] As of npm@6, does everything publish would do except actually publishing to the registry. Reports the details of what would have been published.
```

**Comment by jamesbhobbs** [comment]
This is an existing issue: https://github.com/bbc/psammead/issues/205
