### ISSUE TITLE
Psammead Storybook not loading styles correctly

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#124]
**Describe the bug**
Psammead Storybook is not loading styles correctly.

**To Reproduce**

1. `git checkout latest && npm ci && npm run storybook`
2. visit http://localhost:8080/
3. Select the Paragraph component in the menu
4. Inspect the actual paragraph element. See it has no CSS loaded. 

**Expected behavior**
For the Storybook to have styles 

**Screenshots**

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/psammead/labels/bug)

**Comment by ChrisBAshton** [comment]
Semi-resolved in #121 - but then we are missing the global styles so things like Reith font don't work.

**Comment by sareh** [comment]
@ChrisBAshton We'll need to import these styles:

```
import styledNormalize from 'styled-normalize';
import { createGlobalStyle } from 'styled-components';

const GlobalStyle = createGlobalStyle`
  ${styledNormalize}
  /* Box Sizing https://bit.ly/1A91I0J */
  html {
    box-sizing: border-box;
    font-size: 100%;
  }
  *, *:before, *:after {
    box-sizing: inherit;
  }
  @font-face {
    font-display: optional;
    font-family: ReithSansNewsRegular;
    font-style: normal;
    font-weight: 400;
    src: url('https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Rg.woff2') format('woff2'), url('https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Rg.woff') format('woff');
  }
  @font-face {
    font-display: optional;
    font-family: ReithSerifNewsMedium;
    font-style: normal;
    font-weight: 600;
    src: url('https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_Md.woff2') format('woff2'), url('https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_Md.woff') format('woff');
  }
`;
```

[Currently, we have these in Simorgh](https://github.com/BBC-News/simorgh/blob/f6f094ab0f6116a2a09857de6fd98b33f85a48dc/src/app/lib/globalStyles.js#L5-L31) and use them for Storybook and in our application. 

I think it would make sense to break these down into separate constants that can be imported in. e.g.

```
const FF_ReithSansNewsRegular = css`
@font-face {
    font-display: optional;
    font-family: ReithSansNewsRegular;
    font-style: normal;
    font-weight: 400;
    src: url('https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Rg.woff2') format('woff2'), url('https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Rg.woff') format('woff');
  }
`;
```

**Comment by pjlee11** [comment]
Mentioned in refinement that we evaluate defining the font faces as strings rather than a `css` style component. The decision is that we should keep consistent with the current approach in the other packages and create a sharable styled component. Then in the future, we can [investigate how better the share CSS across all the packages](https://github.com/BBC-News/psammead/issues/142)

**Comment by sareh** [comment]
To unblock Storybook work, we could just add these global styles into the 
`psammead/.storybook/config.js` file: 
```
 addDecorator(story => (
  <Fragment>
    <GlobalStyle />
    {story()}
  </Fragment>
));
```
We can separately consider splitting out these global styles into a psammead package.

**Comment by ChrisBAshton** [comment]
So, to clarify - not going to make a separate `@bbc/reith-font` package at this stage - that work has been moved to #148.

This issue is about doing the minimum viable work to get Storybook rendering correctly.
