### ISSUE TITLE
Investigate lerna publishing setup

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#136]
**Is your feature request related to a problem? Please describe.**
We want lerna to publish all packages that have changed since the last publish. Or last merge. 

**Describe the solution you'd like**
- Investigate the best process, by looking at other monorepos that use lerna.
- Give pros and cons for various setups on this issue.  Recommend a particular setup. 
- Open up another issue that implements the recommended process & writes necessary documentation in the Readme.

**Describe alternatives you've considered**
We could not do this and potentially just publish packages one by one. 

**Testing notes**
[Tester to complete]

Dev insight: This ticket shouldn't require any tests. It is an investigation. 

**Additional context**

- [ ] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by dr3** [comment]
This is related to https://github.com/BBC-News/psammead/issues/132 which is to create a publish script. This has a WIP branch that doesnt use `lerna publish` https://github.com/BBC-News/psammead/pull/123

Im not 100% lerna can do what we want re: https://github.com/lerna/lerna/issues/1357
