### ISSUE TITLE
Re-examine VisuallyHiddenText Readme

### ISSUE THREAD

**Issue by bcmn** [BBC-archive/psammead#138]
Catharine had a couple pieces of feedback on #984.

> I think you need to add directly under the heading ‘When not to use this component’:
>
> "When you want content to be available for all users"
>
> and remove:
>
> “Similarly, when adding hidden text that will occur partway through an article, avoid using phrases that may imply that the main body is over. Suddenly hearing a phrase like “Read more on [subject]” may suggest to users that they have finished the article. To mitigate this, you may wish to wrap the content in an [`aside` ARIA landmark](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/landmarks/complementary.html) or include a [“skip link”](https://www.w3.org/TR/WCAG20-TECHS/G1.html), giving users the option to skip back to the main body before the assistive technology reads the full content of the interjection.” (edited)

**Comment by ChrisBAshton** [comment]
Happy to add the sentence, but devs agreed the paragraph is useful so want to keep it.

**Comment by ChrisBAshton** [comment]
Actually we've re-read the README and we think it offers enough explanation 👍 please raise a PR @greenc05 if you think otherwise.

**Comment by greenc05** [comment]
@ChrisBAshton my comments still stand, that paragraph maybe useful though it's not just referring to visually hidden text and therefore I had asked for it to be removed.
