### ISSUE TITLE
Documentation - Global styles to use with Psammead components

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#139]
**Is your feature request related to a problem? Please describe.**
We are working on adding Global styles in this PR: https://github.com/BBC-News/psammead/issues/124 We should document in our Readme how one should use them. 

**Describe the solution you'd like**
We should explain that we recommend using normalize, box-sizing & font-face declarations and how you can import them in 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Documentation should be clear.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Blocked on this issue being completed https://github.com/BBC-News/psammead/issues/124

**Comment by ChrisBAshton** [comment]
Add something like this to the README (pending #124):

```
npm i 'styled-normalize'
```

```
import { css } from 'styled-components';
import styledNormalize from 'styled-normalize';
import { REITH_FONT } from 'reith-font';

const GlobalStyle = css`
  ${styledNormalize}
  /* Box Sizing https://bit.ly/1A91I0J */
  html {
    box-sizing: border-box;
    font-size: 100%;
  }
  *, *:before, *:after {
    box-sizing: inherit;
  }
  ${REITH_FONT}
```

**Comment by ChrisBAshton** [comment]
No longer pending #124, as in #124 we'll not be making any new packages, just doing MVP to get Storybook working.
