### ISSUE TITLE
Change default branch to `latest`

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#14]
This repository should have its default branch changed from `master` to `latest`.

This would make the default branch have a more semantic meaning and remove outdated master-slave analogies from the setup.

Lots of open source projects have done this, e.g. https://github.com/npm/npm, and we currently have `latest` as the main branch on Simorgh (https://github.com/BBC-News/simorgh)

**Comment by ChrisBAshton** [comment]
Done 👍
