### ISSUE TITLE
Package bumping CLI bumps packages in alpha version to full version `1.2.0-alpha.1` -> `1.2.0`

### ISSUE THREAD

**Issue by jroebu14** [BBC-archive/psammead#1400]
**Describe the bug**
Using the package bumping CLI to bump packages will bump packages in an alpha version to full version e.g. `1.2.0-alpha.1` -> `1.2.0`

**To Reproduce**
Steps to reproduce the behaviour:

1. Open terminal and `cd` to `psammead` project
2. Run script `npm run bumpPackages`
3. Choose to minor bump a package in alpha e.g. `@bbc/psammead-inline-link` which is in `1.2.0-alpha.1`
4. Observe the package has been bumped to a full new version `1.2.1`

**Expected behaviour**
The CLI should either increment the alpha version or there should be a new choice in the CLI to bump the alpha version.

Doesn't require any testing from a tester.

**Comment by dr3** [comment]
Refined, we should increment the alpha version
