### ISSUE TITLE
npm script `install:packages` errors with Storybook

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#1401]
**Describe the bug**
When running `npm run install:packages && npm run build && npm run storybook`, we get this error:

<img width="1105" alt="screenshot with error" src="https://user-images.githubusercontent.com/3028997/61620994-eda3f680-ac69-11e9-9c1d-8a59a6dc444e.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. `npm run install:packages && npm run build && npm run storybook`
2. Click on the pages
3. See error

Note: it currently *does* work without errors when running `npm run ci:packages` instead of `npm run install:packages`. 

**Expected behaviour**
Storybook should work after installing packages. 

**Screenshots**
<img width="1105" alt="screenshot with error" src="https://user-images.githubusercontent.com/3028997/61621043-057b7a80-ac6a-11e9-87b1-53bf4cd11de1.png">

**Desktop (please complete the following information):**

- Device: Mac, Firefox Nightly 70.0a1

**Comment by oluoluoxenfree** [comment]
This appears to not be an issue any more, couldn't replicate it on my or two other machines.

@sareh Does this still happen for you?

**Comment by sareh** [comment]
@oluoluoxenfree No this bug seems to be fixed! Closing the issue. Thanks for checking in, Olu.
