### ISSUE TITLE
Documentation - Component usage example

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#141]
**Is your feature request related to a problem? Please describe.**
We should have an example of using components

**Describe the solution you'd like**
- Add a `## Components` section to the readme (or below the Components section in #137, once it's been done)
- Give an example of how to combine at least two Psammead components.
- For testing, share it with a dev in another team to check it's understandable. 

**Testing notes**
[Tester to complete]

Dev insight: Documentation needs to make sense to a new joiner. 
- For testing, share the PR with a dev in another team to check it's understandable. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Yep, still need to do this! https://github.com/bbc/psammead#nut_and_bolt-using-psammead-components

**Comment by thekp** [comment]
@sareh 

i'm not sure what you mean by combine here?
> Give an example of how to combine at least two Psammead components.
