### ISSUE TITLE
Implement new inline-link styling

### ISSUE THREAD

**Issue by pjlee11** [BBC-archive/psammead#1412]
**Is your feature request related to a problem? Please describe.**
Following on from https://github.com/bbc/psammead/issues/1411 if the external accessibility review comes back as okay we should implement the inline-link styles. This does not need to be performed as an alpha as the accessibility swarm will have been been performed both [internal](https://github.com/bbc/simorgh/pull/2566) and external. 

**Describe the solution you'd like**
Add the following styling for default state:
- margin: 0 -0.125rem;
- padding: 0 0.125rem;

Add the following styling for the hover & focus state:
- background-color: ${C_POSTBOX};
- color: ${C_WHITE};

For further details see additional context section.

**Describe alternatives you've considered**
If the external review comes back saying the styling is not acceptable then close this issue. 

**Testing notes**
[Tester to complete]

Dev insight: Visual regression of storybook and snapshots

**Additional context**
## Inline link ##

Production styling:
```
const InlineLink = styled.a`
  color: ${C_EBON};
  border-bottom: 1px solid ${C_POSTBOX};
  text-decoration: none;

  &:visited {
    color: ${C_METAL};
    border-bottom: 1px solid ${C_METAL};
  }

  &:focus,
  &:hover {
    border-bottom: 2px solid ${C_POSTBOX};
    color: ${C_POSTBOX};
  }
`;
```

Desired styling: 
```
const InlineLink = styled.a`
  color: ${C_EBON};
  border-bottom: 1px solid ${C_POSTBOX};
  margin: 0 -0.125rem; // when using background-colour on hover this counter acts the additional padding
  padding: 0 0.125rem; // extra padding is wanted to extend the highlight of background-colour
  text-decoration: none;

  &:visited {
    color: ${C_METAL};
    border-bottom: 1px solid ${C_METAL};
  }

  &:focus,
  &:hover {
    background-color: ${C_POSTBOX};
    border-bottom: 2px solid ${C_POSTBOX}; // still need for high contrast modes/browser colour overrides
    color: ${C_WHITE};
  }
`;
```

**Comment by jamesdonoh** [comment]
Blocked till the work done in https://github.com/bbc/psammead/issues/1411 has been reviewed by the dedicated a11y team.

**Comment by jamesdonoh** [comment]
Going to closing this for now @jimjohnsonrollings @nataliesmart but we can reopen if we get new/updated requirements.
