### ISSUE TITLE
Fix psammead-story-promo on storybook

### ISSUE THREAD

**Issue by andrew-nowak** [BBC-archive/psammead#1415]
**Is your feature request related to a problem? Please describe.**
The timestamp on the story for Story Promos is displayed in Times (no pun intended). It should be indicative of the real page. 

![image](https://user-images.githubusercontent.com/10963046/61705586-f239df00-ad3d-11e9-863e-0ac92f13b3fe.png)

**Describe the solution you'd like**
Update the Timestamp used in this story to deal with the new fonts work by passing the service through

https://github.com/bbc/psammead/blob/latest/packages/components/psammead-story-promo/src/index.stories.jsx#L26

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by ghost** [comment]
This is already handled as part of https://github.com/bbc/psammead/pull/1359
