### ISSUE TITLE
Investigate exporting strings rather than CSS`foo`

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#142]
**Is your feature request related to a problem? Please describe.**
We've been exploring [how to export global styles](https://github.com/BBC-News/psammead/issues/124#issuecomment-445188064) and it was mentioned that we could export either a string (more reusable, fewer dependencies) or a styled-components CSS object (more usable in Simorgh), or both.

It then occurred to us we haven't tried doing something like this with a _string_:

```jsx
import styled from 'styled-components';
import stringyCss from 'somewhere';
export foo = styled.something`
  ${stringyCss}
  color: red;
`;
```

If string interpolation works, then there's no advantage to introducing the styled-components dependency for these simple CSS-only components, and we should consider porting them across to pure CSS inside a string.

The affected components would be most of the components inside utilities/, and anything that comes out of #124.

**Testing notes**
[Tester to complete]

Dev insight: investigation only

- [ ] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by bcmn** [comment]
This works, & given how packages currently use imported fonts, requires minimal change.

**Comment by bcmn** [comment]
Opened #178 as an outcome.
