### ISSUE TITLE
Validate components against our Definition of Done

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#147]
**Is your feature request related to a problem? Please describe.**
It would be nice to have an automated checker that ensures components correspond to our Definition of Done. Ie.

* they should have a README that includes the expected required sections (contributing, Code of Conduct, licence etc)
* they should have a package.json which includes "repository, author, licence, bugs, homepage"
* they should have a `src/` folder that outputs a `dist/` folder.

...etc.

**Describe the solution you'd like**
A script that validates anything that can be automated, and that runs on the PR and offers a status check. It should have a red cross when the component doesn't validate, to prevent merge.

**Describe alternatives you've considered**
Continuing as we are, which is to check these things manually.

**Testing notes**
[Tester to complete]

Dev insight: ideally a validation script should have unit tests which makes sure it works as expected. For manually testing, you should be able to have an invalid README or package.json and see the automated checklist fail when you open a PR.

**Additional context**
Original issue in #64.

**Comment by rossgaskell** [comment]
Will resolve in https://github.com/bbc/psammead/issues/130
