### ISSUE TITLE
Create global styles packages

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#148]
**Is your feature request related to a problem? Please describe.**
The global styles that we copied across in #124 should be properly managed, rather than embedded inside Storybook.

**Describe the solution you'd like**
A NPM package for the Reith font.

Readme to be updated to install `normalise-styles` and the reith font package, and to add instructions to copy and paste the box-sizing CSS, since it is so simple.

(This too could be a package ^ I don't mind).

**Describe alternatives you've considered**
Continuing as-is, which is to duplicate our global styles across Psammead and Simorgh and have overly bloated README instructions for copying and pasting.

**Testing notes**
[Tester to complete]

Dev insight: Regression tests only.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by bcmn** [comment]
Just to document: this ticket will now need to update the README, as this work changes the README additions introduced in #150.

**Comment by ChrisBAshton** [comment]
`box-sizing` will live in the README for now as we don't want to answer this question just yet!

(There are [multiple ways of exporting](https://github.com/sergeysova/styled-normalize/blob/master/src/index.js) - either as css\` or as a [createGlobalStyle()](https://github.com/sergeysova/styled-normalize/blob/master/src/index.js#L153) or as a plain string (investigating this in #142). V2-3 of styled-components recommends the css\` implementation, but v4 uses the `createGlobalStyle` implementation: https://www.npmjs.com/package/styled-normalize). So we'll investigate this one later.

As for Reith font, we've decided Styled Components with props (for font-display property etc) would be a nice approach, but not worth the effort at this stage of Psammead. Will park it for a few months (at which point, we may want to investigate `box-sizing` again).

README is sufficient for now.
