### ISSUE TITLE
Update directory structure

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#15]
As a result of investigating various component libraries, (https://github.com/BBC-News/simorgh/issues/972), we found this folder structure to be useful:

```
src
├── components
│   ├── example-button
│   └── headings
└── contexts
└── utilities
```

We should update the directory structure to this.  
We can do this by updating the `lerna.json` from 
```
"packages": ["packages/*"]
```
to 
```
"packages": ["src/components/*"]
```

We should ensure that all the npm scripts in the main `package.json` file all work correctly. e.g. `npm run build`, etc.

**Comment by ChrisBAshton** [comment]
Closed following discussion in #19.
