### ISSUE TITLE
Add support for links to section-label

### ISSUE THREAD

**Issue by andrew-nowak** [BBC-archive/psammead#1513]
WSFRONTPGS-80

**Is your feature request related to a problem? Please describe.**
We need to add support for section labels that provide links to indexes.

Design: (Details in Zeplin)
![image](https://user-images.githubusercontent.com/10963046/61964777-9930ac00-afc6-11e9-9c8e-21299faffb64.png)

Note that the design changes dramatically at the 600px breakpoint.

This ticket will require a developer accessibility swarm.

**Describe the solution you'd like**
Extend `psammead-section-label` to optionally provide this functionality.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by DenisHdz** [comment]
Add `Acceptance criteria` to the issue once UX meets Catherine.
