### ISSUE TITLE
Switch Lerna to Fixed Mode

### ISSUE THREAD

**Issue by pharingee** [BBC-archive/psammead#1535]
**Is your feature request related to a problem? Please describe.**
Some psammead packages are dependent on each other. And updates to packages on which other packages depend may cause versioning conflicts in simorgh.

**Describe the solution you'd like**
Switch lerna to fixed mode to ensure consistency across package versions.

**Describe alternatives you've considered**
An alternative solution considered was to run npm-check-updates on our packages recursively to ensure all versions and their dependants were updated properly.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by dr3** [comment]
Does this method allow for publishing components as 'alpha'?

**Comment by pharingee** [comment]
Yes it does.

**Comment by dr3** [comment]
Do you have to release all packages as alpha?

**Comment by dr3** [comment]
We have decided not to go down this route
