### ISSUE TITLE
Improve test coverage for our utilities packages

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#156]
**Is your feature request related to a problem? Please describe.**
We currently have a very red test coverage output. This is mainly due to out utilities packages

**Describe the solution you'd like**
We add tests, maybe testing the number of exports, how they're exported etc 

**Describe alternatives you've considered**
We turn off code coverage for utilities.

![image](https://user-images.githubusercontent.com/11341355/49654868-e14b9000-fa30-11e8-9583-0f6ffe35b236.png)

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Fixed in #259
