### ISSUE TITLE
Input Provider with Storybook knobs not working

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#1598]
**Describe the bug**
The input provider drop-down is broken on `latest`
![Screen Shot input provider broken](https://user-images.githubusercontent.com/3028997/62479856-53ce6480-b7a6-11e9-8379-b00c4310a9fc.png)

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 
https://bbc.github.io/psammead/?path=/story/components-headline--default
https://bbc.github.io/psammead/?path=/story/components-inlinelink--default
2. On the 'knobs' panel, select a service that is not 'news'. e.g `arabic`.
3. See just right-aligned english copy.

This is the case for all stories that use knobs and the inputProvider in psammead-storybook-helpers

**Expected behaviour**
When you select a service that is not `news`, you should get copy written in the relevant language. 

**Screenshots**
Pasted above. 

**Additional context**
Way to see it working again: Pin to version `5.0.6`. 
However, it should be fixed forwards instead of pinned to this older version.

**Comment by ghost** [comment]
This seem to be caused by storybook knobs not being updated. It can be reproduced without `inputProvider`
```jsx
.add('the bug', () => {
    const contents = { news: 'this is news', arabic: 'this is arabic' };
    const options = ['news', 'arabic'];

    const selected = select('Select', options, 'news');
    const value = text('Contents', contents[selected]);

    return <span> {value} </span>;
  })
```

**Comment by ghost** [comment]
**Option 1:** Not to render `value` and render `contents[selected]` but then we loose the ability to edit the text.

**Comment by sareh** [comment]
@sadickisaac Since we rarely edit the text, I think it'd be a good option. It'd give us visibility of the text in the various languages and scripts, which we currently do not have.

**Comment by andrew-nowak** [comment]
:( Looks like this functionality got removed from storybook in the minor version increase to 5.1.0

This looks like the PR where it was removed https://github.com/storybookjs/storybook/pull/6486/files#diff-0f0ba9ed2031f812b0f6abbd2b80b14dL55

And this looks like the issue to follow for bringing the functionality back into storybook https://github.com/storybookjs/storybook/issues/7150

I have found it useful in the past to be able to edit the text, but that functionality can be approximated in the browser dev console, so let's move forward with this until the functionality is readded to storybook
