### ISSUE TITLE
Merge CI task should publish Storybook

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#167]
**Is your feature request related to a problem? Please describe.**
Blocked on #165 and #37.

When a PR is merged, we should run our storybook-deploy task, which builds and deploys the latest Storybook to gh-pages.

Add Jenkins as a collaborator. Create a new access token - ideally that can only push to `gh-pages` if possible. Make `gh-pages` locked down to admins and Jenkins.

**Describe the solution you'd like**
Add Storybook publishing to the CI pipeline.

**Describe alternatives you've considered**
Continue doing this manually from the command line after each merge (error-prone).

**Testing notes**
[Tester to complete]

Dev insight: Create a new package or bump a version of an existing package (example-button maybe?) and when PR is merged, that component should be visible at https://bbc-news.github.io/psammead.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by dr3** [comment]
I dont think this is really blocked on #165  @ChrisBAshton

**Comment by ChrisBAshton** [comment]
Fair. #165 was about setting up a new job, originally - not needed anymore!
