### ISSUE TITLE
Separate out the SitewideLinks component

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#169]
**Is your feature request related to a problem? Please describe.**
See https://github.com/BBC-News/psammead/pull/154#discussion_r239843867

**Describe the solution you'd like**
I believe it makes more sense to split out SitewideLinks into a FooterLinks component. The adjacent "externalLink" and "copyrightText" would be InlineLink and Paragraph components combined... or we could create a new FooterText component to amalgamate them.

**Describe alternatives you've considered**
Leaving as-is.

Or, going the whole hog and porting over the Footer component, which would replace SitewideLinks.

**Testing notes**
[Tester to complete]

Dev insight: TBC

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by sareh** [comment]
It would make sense to split it out if we had any use-case for a site-wide links component without the external link or copyright text information.  I don't believe this is the case, so I believe this is premature optimisation.
