### ISSUE TITLE
Add code climate icons to Readme

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#171]
**Is your feature request related to a problem? Please describe.**
We should add code climate icons in our readme like simorgh has

**Describe the solution you'd like**
Add the following icons, updating the URLs to be Psammead's, the following are simorghs

```
[![Test Coverage](https://api.codeclimate.com/v1/badges/b7c465069b1aacb64daa/test_coverage)](https://codeclimate.com/github/BBC-News/psammead/test_coverage)
[![Maintainability](https://api.codec
limate.com/v1/badges/b7c465069b1aacb64daa/maintainability)](https://codeclimate.com/github/BBC-News/psammead/maintainability)
```

**Testing notes**
The icons look correct and show the correct data.

Dev insight: 
These icons will need to be generated by the code climate owner, which I believe is @benjaminhobbs 

**Additional context**

![image](https://user-images.githubusercontent.com/11341355/49725479-ae3d1280-fc63-11e8-8696-b9ebc21aa67c.png)

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by BogdanDogaru** [comment]
```[![Maintainability](https://api.codeclimate.com/v1/badges/3f7b756f1358f3633362/maintainability)](https://codeclimate.com/github/BBC-News/psammead/maintainability)```

```[![Test Coverage](https://api.codeclimate.com/v1/badges/3f7b756f1358f3633362/test_coverage)](https://codeclimate.com/github/BBC-News/psammead/test_coverage)```
