### ISSUE TITLE
Dual-calendar timestamps for Persian and Pashto

### ISSUE THREAD

**Issue by jamesdonoh** [BBC-archive/psammead#1732]
**Is your feature request related to a problem? Please describe.**
Following the investigation in https://github.com/bbc/simorgh/issues/1567 we have decided to add support for dual calendar (Gregorian and Jalali) timestamps to `psammead-locales`.

The implementation can reuse some of the code and tests from the legacy `moment-ws` codebase as it has been extensively validated in production, but it should be reviewed for correctness and modernised/tidied up before being integrated into psammead.

**Describe the solution you'd like**
- Where possible reuse the existing `moment-ws` JS code and tests (with appropriate updates/improvements and the addition of any required documentation)
- Add any locale changes (e.g. Jalali month names) to the [moment.js](https://momentjs.com/) locales in `psammead-locales` - as [has already been done for Yoruba](https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-locales/moment/yo.js)
- Re-use `jalaali-js` for the actual calendar conversion unless there is a more lightweight/convenient alternative (some research needed)
- Demonstrate that only the Pashto/Persian service bundles sizes are increased (by the minimum possible) and other bundles are not impacted

**Describe alternatives you've considered**
See https://github.com/bbc/simorgh/issues/1567

**Testing notes**
- Full unit test coverage
- Update storybook and relevant documentation

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by ibMadbouly** [comment]
the dual calendar conversion is waiting on issue #1788
