### ISSUE TITLE
Slack notification on build

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#175]
**Is your feature request related to a problem? Please describe.**
Notify Slack when NPM publishes, and when Storybook is deployed.

**Describe the solution you'd like**
When #166 and #167 are merged, we want to send separate notifications for each step, whether they pass or fail.

**Describe alternatives you've considered**
Manually checking Jenkins.

**Testing notes**
[Tester to complete]

Dev insight: When a PR is merged, Slack notifications should be sent as per this issue.

**Comment by ChrisBAshton** [comment]
I believe this is done already - if so, just close the issue.

**Comment by dr3** [comment]
This will be covered by https://github.com/BBC-News/psammead/issues/204 for npm publishes. Github pages release notifications happen automatically by the github integration, closing as done
