### ISSUE TITLE
Desktop width top stories

### ISSUE THREAD

**Issue by andrew-nowak** [BBC-archive/psammead#1761]
WSFRONTPGS-129
**Is your feature request related to a problem? Please describe.**
There have been some updated designs for Top Story promos for 600px+ breakpoints. 

**Describe the solution you'd like**
Update `psammead-story-promo` to conform to the new designs when the `topStory` prop is set to `true`.

Before merge, your pull request will require
- UX approval
- a developer accessibility swarm
- a manual test

Accessibility acceptance criteria has not changed from previous implementations of `psammead-story-promo`.
You may not be blocked from getting started with this ticket, but completion is likely blocked by merging of Index Alsos to psammead #1567. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by ghost** [comment]
Blocked on https://github.com/bbc/psammead/issues/1791, https://github.com/bbc/simorgh/issues/3198
