### ISSUE TITLE
Export Strings instead of styled-components CSS

### ISSUE THREAD

**Issue by bcmn** [BBC-archive/psammead#178]
**Is your feature request related to a problem? Please describe.**
Following #142, it is clear we can export String values from packages such as `gel-foundations-styled-components`, instead of styled-components CSS components. This removes an unnecessary dependency from us, & from anybody who wishes to utilise these foundational packages.

**Describe the solution you'd like**
Instead of:
```
export const GEL_MINION = css`
  font-size: 0.75em;
  line-height: 1em;
`;
```
We would do:
```
export const GEL_MINION = `
  font-size: 0.75em;
  line-height: 1em;
`;
```

[Because of our current usage of these values](https://github.com/BBC-News/psammead/blob/a33a2e3afd9debc464b39c8d5b16624920a89945/packages/components/psammead-paragraph/src/index.jsx#L7-L13), which already injects the exported values into styled-components CSS blocks where used, there should be no change to other packages as a result of this change alone.

However, it raises an interesting point as to our current packages. The `gel-` packages are currently split primarily by implementation detail -- whether `-styled-components` or `-constants`. Following this PR, there will be no need for the `-styled-components` package any more. As such, one of the following should happen:
1. All type size exports to move to `gel-constants`
2. Both `gel-foundations-styled-components` & `gel-constants` become a new `gel-foundations` package.

I would recommend the second option, as this simplifies the "product-y" view of our utility packages.

**Testing notes**
[Tester to complete]

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Agreed in refinement we'd go for option 2 (`gel-foundations`).
