### ISSUE TITLE
Export Index Alsos from `Psammead-story-promo`

### ISSUE THREAD

**Issue by DenisHdz** [BBC-archive/psammead#1780]
**Is your feature request related to a problem? Please describe.**
At the moment we are not exporting the Index Alsos, so we can't import them in Simorgh doing `@bbc/psammead-story-promo/IndexAlsos`.

**Describe the solution you'd like**
We need to export them somehow.

**Describe alternatives you've considered**
 - Export them directly from `psammead-story-promo/src/index.jsx` doing:
    `
    export * as IndexAlsos from './IndexAlsos';
   `

- Create a nested `package.json` like [here](https://github.com/bbc/psammead/tree/latest/packages/utilities/gel-foundations/typography)

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by andrew-nowak** [comment]
In refinement we decidide on option 1:

> Export them directly from psammead-story-promo/src/index.jsx doing:
> export * as IndexAlsos from './IndexAlsos';

**Comment by ghost** [comment]
Looking at this again i think we should go with option 2. I could not find any reference to this pattern `export * as namespace from './Component'`. This will allow us to avoid pulling in this dependancy `@babel/plugin-proposal-export-namespace-from`
