### ISSUE TITLE
Add pashto locale to psammead locales

### ISSUE THREAD

**Issue by rhenshaw56** [BBC-archive/psammead#1788]
**Is your feature request related to a problem? Please describe.**
We have decided that the moment translations for Pashto aren't suitable for editorial and may need to add it to suit our requirements

**Describe the solution you'd like**
We need to extend the pashto file to psammead-locales https://github.com/bbc/psammead/tree/latest/packages/utilities/psammead-locales/moment which updates the `ps` locale
The update should ensure we include:

~~1. The double month name (This can be seen on an existing Arabic page eg. https://www.bbc.com/arabic/middleeast-49365997)~~
2. Eastern Arabic numerals (i.e. ۰, ۱, ۲, ۳, ۴, ۵, ۶, ۷, ۸, ۹, ۱۰...)
3. Remember to update relevant documentations

 

**Describe alternatives you've considered**

**Testing notes**
- Unit tests needed to cover locales in psammead

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by ibMadbouly** [comment]
I checked with @sareh that `pashto` articles don't have double month name like done in Arabic articles, cause `pashto` should have calendar conversion as independent calendar and this should be covered in issue #1732. @sareh can you please confirm?
