### ISSUE TITLE
'Experimental' directory for components

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#18]
As a result of investigating various component libraries, (BBC-News/simorgh#972), we found the idea of a `labs` or `experimental` directory to be useful. 
For example: 
src
├── components
│   └── headings
├── experimental
│   └── headings

Where the npm module for experimental packages should be namespaced to `experimental/<component-name>`, e.g. `experimental/headings` for example.

## Suggested approach
We can do this by updating the lerna.json to
```
"packages": ["src/components/*", "src/experimental/*"]
```

We should ensure that all the npm scripts in the main package.json file all work correctly. e.g. npm run build, etc.

**Comment by chris-hinds** [comment]
This is been addressed by the use of Alpha labels on our psammead components.
