### ISSUE TITLE
Storybook - AMP script duplication

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#1833]
**Describe the bug**
When 

**To Reproduce**
Steps to reproduce the behaviour:

1. Run storybook: `npm ci && npm run storybook`
2. Visit an AMP image story: http://localhost.bbc.com:9001/?path=/story/containers-article-article-figure-amp--with-a-caption-and-non-bbc-copyright & open the dev console. Then click through to another AMP image
3. See error regarding duplication. The image isn't loading - we just see the placeholder
<img width="1413" alt="Screenshot of error in storybook" src="https://user-images.githubusercontent.com/3028997/63346197-64591000-c34c-11e9-8523-ca7087a1e6b2.png">

Note - that doing a hard refresh loads the amp-img correctly.

**Expected behaviour**
No console error & the image loading correctly when clicking through to multiple AMP image stories

**Screenshots**
Added aboce

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
Just ran into this when working on an AMP component - also happens after a hot reload when you're making code changes!
