### ISSUE TITLE
We need to review psammead docs and writeup the development workflow

### ISSUE THREAD

**Issue by jamesbhobbs** [BBC-archive/psammead#1838]
**Is your feature request related to a problem? Please describe.**
Documentation is not up to date with latest tooling available in the repo

**Describe the solution you'd like**
Review all docs and ensure they tie together (probably best to ignore package specific docs in this issue). We need to ensure that part of what is documented is: 

- Full development workflow for non-alpha components. 
- Full development workflow for alpha components.
- Examples of each of the aforementioned with explicit reference to tooling (npm scripts and Talos used and when they are used.
- Clear definition of how and when things should be pulled in [Simorgh](https://github.com/bbc/simorgh/) repo - this should probably neatly dovetail with new Simorgh documentation on how to pull in alpha or non-alpha components and hide them behind feature toggles.

Core docs are:
https://github.com/bbc/psammead/blob/latest/packages/components/README.md
https://github.com/bbc/psammead/blob/latest/CONTRIBUTING.md

**Describe alternatives you've considered**

**Testing notes**
Testing will be giving docs to a novice and seeing them contribute in the preferred manner.

~- [ ] This feature is expected to need manual testing.~

**Additional context**
Refer to docs in https://github.com/bbc/simorgh/ but do not make the interdependent beyond referring to the shared Github Project board.

**Comment by jamesbhobbs** [comment]
NB to self add deprecation process for when something is erroneously published

**Comment by jamesbhobbs** [comment]
Include "Document method of linking psammead components to simorgh"

**Comment by jamesbhobbs** [comment]
https://github.com/bbc/psammead/blob/09a06116b174961f2b3543f94c792bc0a92b99e2/documentation/architecture-decision-records/ADR0003-definition_of_done.md

**Comment by HarveyPeachey** [comment]
Some links are also broken on the main README:

- [Dependancy status and devDependancies status](https://github.com/bbc/psammead/blob/latest/README.md)
- [Testing instructions for each assistive technology](https://github.com/bbc/psammead/blob/latest/README.md#assistive-technology-support)

**Comment by jamesbhobbs** [comment]
> * Dependancy status and devDependancies status

First link is fixed, second link is correct but needs fixing: https://github.com/bbc/accessibility-news-and-you/issues/40 I'm happy to do this as I broke it, but I need @greenc05 's help as I accidentally removed my own access to administrate that repo.

**Comment by amywalkerdev** [comment]
Updating the alpha component workflow in #2428 , will check the overall state of the docs after that is merged
