### ISSUE TITLE
Event tracking - data attributes for brand component

### ISSUE THREAD

**Issue by j-pendlebury** [BBC-archive/psammead#1853]
**Is your feature request related to a problem? Please describe.**
Add data attributes for event tracking in the brand component.

**Describe the solution you'd like**
Add data attributes to the brand component which will be used for tracking the component in Simorgh, e.g. `data-brand=header`.

Data attributes should be added to the brand in the header and the footer, i.e. `data-brand=header`, `data-brand=footer`.

**Testing notes**
[Tester to complete]

Dev insight: Snapshots

- [ ] This feature is expected to need manual testing.

**Additional context**
* https://paper.dropbox.com/doc/Event-tracking--AjZNWSURmJ_~rHV8QUSJkDShAg-3i47TvVb9IJBMJFcL8D6u#:uid=275080311694076762638564&h2=Brand
* WSFRONTPGS-178
* https://github.com/bbc/simorgh/tree/latest/src/app/containers/ATIAnalytics

**Comment by j-pendlebury** [comment]
Blocked on https://github.com/bbc/simorgh/issues/3365 and https://github.com/bbc/simorgh/issues/3366

**Comment by j-pendlebury** [comment]
to be moved to Simorgh

**Comment by DenisHdz** [comment]
This can be closed as has been done in https://github.com/bbc/psammead/pull/2377
