### ISSUE TITLE
Event tracking - data attributes for navigation component

### ISSUE THREAD

**Issue by j-pendlebury** [BBC-archive/psammead#1854]
**Is your feature request related to a problem? Please describe.**
Add data attributes for event tracking in the navigation component.

**Describe the solution you'd like**
Add data attributes to the navigation component which will be used for tracking the component in Simorgh, e.g. data-navigation=[label-url].

**Testing notes**
[Tester to complete]

Dev insight: Snapshots

- [ ] This feature is expected to need manual testing.

**Additional context**
* https://paper.dropbox.com/doc/Event-tracking--AjZNWSURmJ_~rHV8QUSJkDShAg-3i47TvVb9IJBMJFcL8D6u#:uid=199862101615944830195329&h2=Navigation
* WSFRONTPGS-179

**Comment by j-pendlebury** [comment]
Blocked on https://github.com/bbc/simorgh/issues/3365 and https://github.com/bbc/simorgh/issues/3366

**Comment by ghost** [comment]
@jblaut should the `data-navigation` be added to the navigation component or to the individual links? If it is on the `Navigation` component then we can't have the value being `label-url`.( which url would we use?) What is `label`? is it the title of the link?

**Comment by j-pendlebury** [comment]
@sadickisaac ideally, the data attributes should be added to each link in the nav. Label refers to the title of the link.
