### ISSUE TITLE
Talos fails to run

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#1863]
**Describe the bug**
Talos sometimes fails to run. This happens when manually invoked or via a publish

```
* Running "npx npm-check-updates @bbc/gel-foundations, @bbc/psammead-assets, @bbc/psammead-styles --packageFile package.json -u -a --jsonUpgraded && npx lerna exec --parallel --no-bail -- npx npm-check-updates @bbc/gel-foundations, @bbc/psammead-assets, @bbc/psammead-styles -u -a --jsonUpgraded"

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
```

https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/psammead/detail/latest/524/pipeline

**Expected behaviour**
It runs correctly

- ~[ ] This bug fix is expected to need manual testing.~

**Additional context**

**Comment by FK78** [comment]
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/34196381/63774192-a21de180-c8d4-11e9-80a0-7cdf5c3ed243.png">

[Jenkins](https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/psammead/detail/latest/533/pipeline/)
