### ISSUE TITLE
Consistent use of destructuring props

### ISSUE THREAD

**Issue by ghost** [BBC-archive/psammead#1921]
**Is your feature request related to a problem? Please describe.**
Currently there is a mixed usage of destructuring when it comes to props passed to styled components.
https://github.com/bbc/psammead/blob/3ae1fadb466a54dc0f5228f624d7ac6a8fa58fd6/packages/components/psammead-story-promo/src/index.jsx#L162-L168

**Describe the solution you'd like**
Desctrucuture `props` where we have `props.script` in `psammead-packages`

**Describe alternatives you've considered**
Leave them as they are.

**Testing notes**
[Tester to complete]

Dev insight: Regression

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by Bopchy** [comment]
Since most of the instances are not destructured - change to a un-destructured format. Also look into adding a eslint check for this

**Comment by ghost** [comment]
Also note that `script` is the only prop not destructured when passed  to a style component apart from 
https://github.com/bbc/psammead/blob/0e7d21ef7f0dde0e8c976218a0a4983c61dda1ac/packages/components/psammead-section-label/src/titles.jsx#L75
https://github.com/bbc/psammead/blob/0e7d21ef7f0dde0e8c976218a0a4983c61dda1ac/packages/components/psammead-section-label/src/titles.jsx#L104

I have no idea why. I guess we only need to change the two places.

**Comment by ghost** [comment]
Since we are already desctructuring `props` everywhere in psammead. Can we just destructure `props` passed to styled components. IMO just looks much nicer and consistent with what we are already doing.
