### ISSUE TITLE
Timestamp Container story buttons not working

### ISSUE THREAD

**Issue by gabriellorin** [BBC-archive/psammead#1934]
**Describe the bug**
When using the Timestamp Container story (https://bbc.github.io/psammead/?path=/story/containers-timestampcontainer--default), the buttons to change the date/time do not currently work.

**To Reproduce**
1. Visit https://bbc.github.io/psammead/?path=/story/containers-timestampcontainer--default (or run locally)
2. Click on button `20 days ago` (or any other button)
3. The date displayed doesn't change.

And:
1. Visit https://bbc.github.io/psammead/?path=/story/containers-timestampcontainer--default (or run locally)
2. Set the `isRelative` checkbox to true
2. Click on button `2 hours ago` (or any other button)
3. The date displayed displays `x minutes ago` instead of `2 hours ago` (`x` being the amount of time since the page has loaded).

**Expected behaviour**
The buttons should update the time / date.

**Screenshots**
(Taken 29th of Aug 2019)
<img width="947" alt="screenshot-29th-aug" src="https://user-images.githubusercontent.com/1299130/63927914-e92fe200-ca4e-11e9-87f3-0af005b18209.png">

**Desktop:**
- OS: macOS
- Browser: Chrome, Safari

**Testing notes**
- [ ] This bug fix is expected to need manual testing.

**Comment by amywalkerdev** [comment]
Fixed
