### ISSUE TITLE
Create new EU/EEA cookie banner component

### ISSUE THREAD

**Issue by jimjohnsonrollings** [BBC-archive/psammead#1957]
**Is your feature request related to a problem? Please describe.**
GNL are changing how the cookie banner works in the EU/EEA - but not in the UK.

**Describe the solution you'd like**
Create a component that meets the requirements of GNL:
* The banner is an overlay for the entire page.  It is not possible for the user to interact with the page without accepting the cookies
* The banner will display the new wording (set in service config in Simorgh)
* Clicking the agree button will set the ckns_explicit cookie = `2` and the ckns_policy cookie = `111`

<img width="1295" alt="Screen Shot 2019-09-02 at 10 11 17" src="https://user-images.githubusercontent.com/8124899/64103514-5488f500-cd6a-11e9-91ba-4286e367373e.png">

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by EinsteinNjoroge** [comment]
~Blocked on https://github.com/bbc/simorgh/issues/3494~
