### ISSUE TITLE
Expand changeScanner to cover base level packages

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#1967]
**Is your feature request related to a problem? Please describe.**
Currently `npm run changeScanner` will complain if you make a change to a package without updating its changelog/package/packageLock.

**Describe the solution you'd like**
Update changeScanner so if someone makes a change to psammead, outside of the `packages` folder it complains you havent bumped the base level psammead changelog/package/packageLock

E.g. changing `psammead/scripts/enforceVersions.sh` would complain and ask you top bump the base level changelog/package/packageLock

but

changing `psammead/packages/utilities/gel-foundations/breakpoints/package.json` would complain that you havent updating the gel-foundations changelog/package/packageLock, NOT the base level ones

**Testing notes**
Write unit tests

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by mykeels** [comment]
I'd like to take this.

Where can I find the `changelog/package/packageLock` file?
