### ISSUE TITLE
Create NPM user and add token to Jenkins credential store

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#200]
**Is your feature request related to a problem? Please describe.**
To publish npm packages we need an account and token to use to publish. 

**Describe the solution you'd like**
1) Create the account `bbc-online`
2) Give read-write access to psammead packages
3) Generate token
4) Work with Frameworks to put token AND EMAIL in Jenkins credential store.

**Additional context**
A similar task is in the backlog for frameworks ticket RESFRAME-2511

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Raised https://github.com/bbc/npm/issues/546

**Comment by ChrisBAshton** [comment]
Blocked on Frameworks pulling the access token into Jenkins.

**Comment by ChrisBAshton** [comment]
Raised PR with frameworks: https://github.com/bbc/news-credentials/pull/4

**Comment by ChrisBAshton** [comment]
This is now live & in use, albeit not merged in the other repo.
