### ISSUE TITLE
Put Image component into Psammead 

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#203]
**Is your feature request related to a problem? Please describe.**
Create an Image component in Psammead, looking at the one in Simorgh:

Corresponding 'pull from Psammead' issue in Simorgh: https://github.com/BBC-News/simorgh/issues/1077.

**Note: update the `README.md`** to include standard sections: https://github.com/BBC-News/psammead/tree/latest/packages/components/psammead-paragraph

**Describe the solution you'd like**
A PR in Psammead, which adds an Image component.

**Describe alternatives you've considered**
N/A

**Testing notes**
Check to make sure component displays (with styling) as expected in Storybook.

Dev insight: Unit tests (if any) will be transferred from Simorgh.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Blocked on https://github.com/BBC-News/simorgh/issues/929

**Comment by ChrisBAshton** [comment]
https://github.com/BBC-News/simorgh/issues/929 is proving more difficult than anticipated.

We can pick up #203 in the meantime, and then port across the AmpImg PR to Psammead once we've nailed it in Simorgh.
