### ISSUE TITLE
Improve publish package

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#205]
**Is your feature request related to a problem? Please describe.**
We have decided as https://github.com/BBC-News/psammead/pull/180 is blocking we should try and get it merged.

There are however a few features that are desired:

**Describe the solution you'd like**
- Make report more informative, how many packages checked
- Add option to run as 'dry run' to see what packages your PR affects and would publish
- Add logging for when default is overwritten

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by jamesdonoh** [comment]
Are these features still needed? How important/urgent are they?
