### ISSUE TITLE
Story Promo in Storybook - Media knob missing visually hidden text

### ISSUE THREAD

**Issue by greenc05** [BBC-archive/psammead#2097]
**Describe the bug**
[Story promo](https://bbc.github.io/psammead/?path=/story/components-storypromo-storypromo--default) - When selecting a media type knob, the SVG icon code for this gets added though no visually hidden text is added to the h3 for this, it should be.

**To Reproduce**
Go to https://bbc.github.io/psammead/?path=/story/components-storypromo-storypromo--default then select a media type knob, you will see the SVG icon added but no visually hidden text to the h3

**Expected behaviour**
When I select a media knob, the visually hidden code should get added along with the SVG code

**Screenshots**
<img width="1232" alt="Screen Shot 2019-09-11 at 12 00 09" src="https://user-images.githubusercontent.com/1061401/64692139-49317a00-d48c-11e9-8544-60c6b48f1432.png">

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Comment by ghost** [comment]
Double check with simorgh storybook
