### ISSUE TITLE
Override numerals in moment

### ISSUE THREAD

**Issue by ghost** [BBC-archive/psammead#2098]
**Is your feature request related to a problem? Please describe.**
Some services have incorrect timestamp numerals i.e Nepali expected `14 जुलाई 2019`, what we currently have `८ जुलाई २०१९`

**Describe the solution you'd like**
Override moment default for the following services. 
- Hindi
- Gujarati
- Tamil
- Marathi
- Nepali

More details WSFRONTPGS-197

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by DenisHdz** [comment]
This can now be closed as the smaller issues have been already merged.
