### ISSUE TITLE
Add Slack token to Jenkins for NPM publishes

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#215]
**Is your feature request related to a problem? Please describe.**
When we publish npm packages via the CI we need a slack token to notify of these publishes

**Describe the solution you'd like**

1. Get Token from Slack or Drew
2. Work with Frameworks to put token in Jenkins credential store.

This was attempted to be done in https://github.com/BBC-News/psammead/issues/204 however it was deemed too complicated for now, this approach will be done for the mean time.

**Additional context**
A similar task is in the backlog for frameworks ticket RESFRAME-2511 and BBC-News/psammead#200

 [x] Initially labelled with "Refinement needed"

**Comment by ChrisBAshton** [comment]
Is the Slack token articles-specific or News-wide? The answer will affect what we name it and where in the credentials store repo we put it.

**Comment by dr3** [comment]
@ChrisBAshton its specific to the psammead channel

**Comment by dr3** [comment]
Also does it need to be in a credentials repo? If its manually added does it ever disappear? It takes 10 seconds to get it out of slack, plus its very easily regenerated, which means if someone accidentally clicks the regen button, theres a huge overhead to replace it

**Comment by ChrisBAshton** [comment]
Hmmm rather than everyone sticking team-specific stuff as ENV variables inside Jenkins, we could agree on a Jenkins salt.

```
const SALT = 'nfew9ngew98gnwe98gnew9'; // or whatever
// ^ export this globally in Jenkins

const saltedSlack = encryption_function(SALT, 'secret slack token');
// ^ store the outputted version in psammead, we do this ahead of time

const slackToken = decryption_function(SALT, saltedSlack)
// ^ this is the bit of runtime code we keep in Jenkinsfile
```

**Comment by dr3** [comment]
Ooh yes that sounds much nicer @ChrisBAshton 

We could use node core `crypto` package, it looks like `aes-256-ctr` is recomended https://lollyrock.com/posts/nodejs-encryption/ what do you think?

**Comment by ChrisBAshton** [comment]
De-prioritising this issue as we still get emails when NPM packages are published - it can wait until January.

Have discussed the salt approach with News Frameworks and we're not quite sure of the best approach at this stage - will consult with a TA.

**Comment by jamesbhobbs** [comment]
We get the jenkins notification, that is sufficient
