### ISSUE TITLE
Pull in media icons from psammead-assets

### ISSUE THREAD

**Issue by OlgaLyubin** [BBC-archive/psammead#2159]
**Is your feature request related to a problem? Please describe.**
This is a continuation for https://github.com/bbc/psammead/issues/1834 . Now that the PR that puts icons in `psammead-assets` is published, the icons need to be pulled into `psammead-media-indicator`.

**Describe the solution you'd like**
Remove media icons from `psammead-media-indicator`
Pull in media icons from `psammead-assets` into `psammead-media-indicator`

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by OlgaLyubin** [comment]
This is blocked until https://github.com/bbc/psammead/pull/2115 gets merged.

**Comment by Bopchy** [comment]
This can be done in one PR with #2158

**Comment by OlgaLyubin** [comment]
This is unblocked now since https://github.com/bbc/psammead/pull/2115 got merged.
