### ISSUE TITLE
Add package linking command and documentation

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#217]
**Is your feature request related to a problem? Please describe.**
We need a way of linking packages locally for local development

**Describe the solution you'd like**
Add an NPM command `npm run link` -> `lerna link --force-local`

And document on the readme (near the top) what this does

**Additional context**

You need `--force-local`, If a package requires `^0.1.0` and you have `0.2.0` locally, it wont link unless you force it, which is weird, but IMO its what we want  https://github.com/lerna/lerna/tree/master/commands/link#readme

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
Talking this through in the office, my opinion is it shouldn’t be automatic but a message could be clearly logged saying something like

```
For a better dev experience you can link all the packages together using this command:
npm run link
```

Then in the package.json have `"npm run link": "npx lerna link --force-local"`

We should also document how to transpile the code using the `build` command as this can be confusing when updating a dependency and using the new code in a single PR.

**Comment by ChrisBAshton** [comment]
This is already in flight, via #239
