### ISSUE TITLE
Update moment month translations

### ISSUE THREAD

**Issue by DenisHdz** [BBC-archive/psammead#2173]
**Is your feature request related to a problem? Please describe.**
The translations for the date, as used by the BBC, were stored partly in `PAL` and partly in Moment under the BBC specific `moment-ws`. 

As we now only want to use `moment`, we have to apply the correct date translations.

**Describe the solution you'd like**
Apply the correct month values as described in the spreadsheet. Where possible the month string has been created from the PAL config. As we only use the full month description on the Frontpage, only these values will be updated.

- Afaan Oromoo -> https://github.com/bbc/psammead/pull/2187
- Amharic -> https://github.com/bbc/psammead/pull/2187
- Bengali -> https://github.com/bbc/psammead/pull/2227
- Gahuza -> https://github.com/bbc/psammead/pull/2193
- Gujarati -> https://github.com/bbc/psammead/pull/2227
- Hausa -> https://github.com/bbc/psammead/pull/2196
- Hindi -> https://github.com/bbc/psammead/pull/2227
- ~~Igbo~~ `Doesn't require updating - according to spreadsheet on WSFRONTPGS-200`
- Nepali -> https://github.com/bbc/psammead/pull/2210
- Pashto -> https://github.com/bbc/psammead/pull/2227
- Somali -> https://github.com/bbc/psammead/pull/2196
- Swahili -> https://github.com/bbc/psammead/pull/2227
- Tigrinya -> https://github.com/bbc/psammead/pull/2193
- ~~Ukrainian~~
`We do not need to override months for Ukrainian for now because those are Russian and are required for a Russian locale.`
- Urdu

More details WSFRONTPGS-200

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [X] This feature is expected to need manual testing.

**Additional context**

**Comment by ghost** [comment]
Can we combine this with the work being done currently to override relative timestamps.

**Comment by DenisHdz** [comment]
Yes, we can, but some of these services are not covered by the ongoing PRs.

**Comment by DenisHdz** [comment]
> Can we combine this with the work being done currently to override relative timestamps.

Yes, we can, but some of these services are not covered by the ongoing relative timestamps PRs.
