### ISSUE TITLE
Add a `watch` command to improve DevX

### ISSUE THREAD

**Issue by pjlee11** [BBC-archive/psammead#218]
**Is your feature request related to a problem? Please describe.**
We currently have to manually run the `build` command to transpile JSX code. This can be irritating when forgotten about. 

**Describe the solution you'd like**
Automate the linking of local npm dependencies and have a watch task that automatically transpiles code when the files are changed/saved.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Ensure that packages link correctly and code auto-transpiles on save.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ryanmccombe** [comment]
I'm maybe misunderstanding the ticket, but this already seems to be implemented?

Running the `storybook` npm script will watch the files, and update when any changes are made
