### ISSUE TITLE
Give ability to choose what package is being created with `npm run create:package`

### ISSUE THREAD

**Issue by HarveyPeachey** [BBC-archive/psammead#2188]
**Is your feature request related to a problem? Please describe.**
At the moment when you create a brand new package for psammead using the command `npm run create:package` which uses a generator called [yeoman](https://yeoman.io/), it generates all the necessary files to start work on a new package. However, it automatically assumes you're creating a `component` as it places it in the `packages/components` directory.

**Describe the solution you'd like**
We need to add something to our yeoman configuration to ask what package we're creating between `components`, `containers` and `utilities` which places the generated files into their corresponding directories. 

Depending on which package is being created the default `index.stories.jsx` should reflect this as well e.g the [`Psammead Locales`](https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-locales/numerals/index.stories.jsx) is added to the utilities subsection in storybook whereas by default it's adding it to the `other` section by default. The URL in the default `CHANGELOG.MD` is incorrect it should be `https://github.com/bbc/psammead/pull/XX`

**Describe alternatives you've considered**
We could just let the user type the directory they wish the package to go to, after generation.

**Testing notes**
Doesn't require any testing from a tester.

Dev insight: Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
The generated `index.stories.jsx` has linting issues which makes sense to be addressed as part of this PR as well:
![Screenshot 2019-09-19 at 15 19 58](https://user-images.githubusercontent.com/4706195/65252611-30127400-daf1-11e9-8ddd-c467274d6873.png)

**Comment by ghost** [comment]
The story generated should be in the correct storybook category `components`, `utilities` or `containers` instead of `others` as currently is.

**Comment by jroebu14** [comment]
Consider adding the `withServicesKnob` decorator to generated components.

**Comment by mykeels** [comment]
@jroebu14 I've created this issue to track that https://github.com/bbc/psammead/issues/2632
