### ISSUE TITLE
Allow inline link colours to change

### ISSUE THREAD

**Issue by jimjohnsonrollings** [BBC-archive/psammead#2195]
**Is your feature request related to a problem? Please describe.**
As we launch services outside of 'News', we need to be able to apply different colours to the inline link, e.g. /scotland should use Dark Saltire

TBC: reference to colour requirements for services

**Describe the solution you'd like**
- Allow the colour of the inline link default state border bottom to vary
- Allow the colour of the inline link hover state text and border bottom to vary
- Essentially, any time the link is currently red, it should be able to be a different colour instead, on a per service basis
- Look at existing 'theme' usage in service config e.g. at https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/services/scotland.js#L38
  - Propose a solution for how link colours should be incorporated/added to this
  - Look at how to allow the inline links to be viewed in Storybook with different colour schemes
- Implement in a way that means it can also be used on other page types such as front pages, media pages or indexes
- This must have an a11y swarm because we are changing colours which may not be accessible

**Describe alternatives you've considered**
N/A

**Testing notes**
- Not clear whether Cypress can simulate hover state to be able to test link colours - this should be confirmed and e2e tests implemented if possible
  - If not possible in Cypress look at other ways of allowing automated tests for hover link colours - e.g. via Chromatic or other means
  - And/or look at ability of `react-testing-library` to fire events for a particular component and inspect the styles on this component or as a last resort compare snapshot

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment]
@jimjohnsonrollings Do you want the colour of the text and border-bottom to change *independently* of one another?

Or would it be sufficient to have `inlineLinkColour`, `inlineLinkColourVisited`, `inlineLinkColourFocusHover`?

**Comment by jimjohnsonrollings** [comment]
In the default state the text and line are different colours currently.

**Comment by jimjohnsonrollings** [comment]
> In the default state the text and line are different colours currently.

**Comment by sareh** [comment]
Ah, good point. 
In that case, we could either pass in a prop that's an object with 
```
textColour,
underlineColour,
visitedTextColour
visitedUnderlineColour
focusHoverTextColour
focusHoverUnderlineColour
```
The reason to call it underline is that we might change the implementation from border-bottom to text-decoration: underline, to something else, and it is a way to name it so the prop name doesn't need to change.

**Comment by sareh** [comment]
This issue is for articles. Just added the shared components label for visibility / code reviewing.

**Comment by jimjohnsonrollings** [comment]
We're not going to do this any more.
