### ISSUE TITLE
Yeoman tests intermittently time out

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#2197]
**Describe the bug**
The Yeoman unit tests intermittently time out when running on CI.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Jenkins CI branch with the failing test.  e.g. this job: `Talos%2F201992082854/2/pipeline/`
2. See error

**Expected behaviour**
The tests to run and pass without timing out

**Screenshots**
<img width="1199" alt="Screenshot Jenkins job with Yeoman test timing out" src="https://user-images.githubusercontent.com/3028997/65313934-2cccc600-db8d-11e9-9e7a-721f1d1be97a.png">

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
N/A

**Comment by thekp** [comment]
initial issue: https://github.com/bbc/psammead/issues/1995

**Comment by mykeels** [comment]
Is there a way to reproduce this issue?

**Comment by thekp** [comment]
@mykeels  when you run `npm run test:unit` locally in psammead, you will be able to see the error occur. 

for it to occur more frequently, you can change this line: https://github.com/bbc/psammead/blob/latest/.yeoman/index.test.js#L42

to a smaller number such as `1000`

**Comment by thekp** [comment]
From this build: https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/psammead/detail/latest/729/pipeline
![image](https://user-images.githubusercontent.com/30599794/66475213-c7cd0780-ea8a-11e9-8651-cb2b91e936b7.png)
It shows that there is still a possibility of yeoman tests to fail even with my most recent changes

i've reopened this issue to continue looking into a better fix
