### ISSUE TITLE
Treeshaking not working for psammead-style fonts

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#2212]
**Describe the bug**
Treeshaking not working for psammead-style fonts

Webpack Bundle Analyzer in Simorgh
![image](https://user-images.githubusercontent.com/11341355/65396064-0def4f00-dd9a-11e9-8c71-3f1350661326.png)

**Expected behaviour**
It only bundles a small subset of `fonts.js` to each service. This should be <3kb per service, not 15 as seen above

NB: make sure you view 'stat' size, not gzip size in Webpack Bundle Analyzer

**Testing notes**

Requires a regression on all the components as `psammead-styles` affects all the components.

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by jroebu14** [comment]
I'm not totally convinced that tree shaking is working for any of the modules within `psammead-styles`. Can you be absolutely sure that tree-shaking works for e.g. colours.js

I see a few things potentially wrong

- there is no `"sideEffects": false` in the package.json
- there is no path to the esm in the package.json `"module": "esm/index.js`
- based on the last point, there is no index.js file that re-exports everything in the package

@FK78

**Comment by FK78** [comment]
Alongside the suggestions @jroebu14 made, I've also tried the following:

- Basic webpack setup in a basic app with `psammead-styles` imported, tree shaking worked.

- Copied export style of `psammead-styles colours.js` (which we know treeshaking works for), tree shaking did not work.

- Copied export style of `psammead-assets svgs.jsx`, tree shaking did not work.

- Similar webpack and babel setup to Simorgh's in a basic app with `psammead-styles` imported, tree shaking did not work.
