### ISSUE TITLE
Investigate Link Styles within Caption & Body Copy

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#222]
**Is your feature request related to a problem? Please describe.**
For links in the caption and body copy:

- Background colour in hover/focus covers up text in lines above/below. 
Hover state:
<img width="195" alt="screen shot 2018-12-17 at 15 39 22" src="https://user-images.githubusercontent.com/3028997/50097591-2bdbc200-0212-11e9-849d-0d3f8182f98b.png">
Focus state:
<img width="190" alt="screen shot 2018-12-17 at 15 39 42" src="https://user-images.githubusercontent.com/3028997/50097589-2b432b80-0212-11e9-9516-adc644d96692.png">

- Bottom border sits over the text below: screenshot

<img width="191" alt="screen shot 2018-12-17 at 15 38 27" src="https://user-images.githubusercontent.com/3028997/50097592-2bdbc200-0212-11e9-8300-b0ba735a6e53.png">

See this in Storybook, with Caption with an inline link: https://bbc-news.github.io/psammead/?selectedKind=Caption&selectedStory=containing%20an%20inline%20link&full=0&addons=1&stories=1&panelRight=1&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

**Describe the solution you'd like**
To propose an alternative technical solution to getting similar hover/focus styles without obscuring the text. 

Note: removing padding as suggested by https://github.com/BBC-News/simorgh/issues/1055 goes some way, but does not completely address this issue.

See @pjlee11's prior investigation into this issue: (https://github.com/BBC-News/simorgh/issues/616#issuecomment-444551804)

> The current border-bottom design may not be acceptable when it comes to multi-line links so we could:
> a) Use text-decoration: underline instead of border-bottom for inline link styling
> b) Experiment with box-shadow instead of border-bottom however we would also require a fallback, potentially text-decoration?
> c) Continue using border-bottom however we will need to change all the typography settings/groups so that they render the border correctly for multi-line links

If there is no alternative technical solution, and the UX team are not able to change the line height for the GEL types, @nataliesmart and other UX designers would need to change the link styles. 

**Describe alternatives you've considered**
**Note: Changing the line height and font size may work, however this investigation is assuming these are kept as per current GEL Typography specs. This is because changing the Types specs is a longer process**

**Testing notes**
[Tester to complete]

Dev insight: Testing in Storybook, in the Caption - text with link.  Check on 2-3 older devices as part of the QA.

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Can we consolidate some of these issues into this one?

https://github.com/BBC-News/simorgh/issues/1055
https://github.com/BBC-News/simorgh/issues/1010
https://github.com/BBC-News/simorgh/issues/828
https://github.com/BBC-News/simorgh/issues/616

**Comment by dr3** [comment]
### Current
![image](https://user-images.githubusercontent.com/11341355/50594326-0dbdc500-0e94-11e9-8cee-c1795472b456.png)
![image](https://user-images.githubusercontent.com/11341355/50612511-24830c80-0ed2-11e9-8268-377d6379a18e.png)
### With no top bottom link padding
![image](https://user-images.githubusercontent.com/11341355/50594339-19a98700-0e94-11e9-9985-d78b56863b06.png)
![image](https://user-images.githubusercontent.com/11341355/50612332-88f19c00-0ed1-11e9-99c0-c66ff03d85a5.png)
### With no top bottom link padding - HOVER
![image](https://user-images.githubusercontent.com/11341355/50594388-4fe70680-0e94-11e9-826d-85caa6e8ab61.png)
![image](https://user-images.githubusercontent.com/11341355/50612376-acb4e200-0ed1-11e9-81ee-71383ed867bf.png)
### Box shadow on text has same effect and cant be shortened
![image](https://user-images.githubusercontent.com/11341355/50611568-d7516b80-0ece-11e9-9929-a86609ca60a5.png)

Closing pending investigation in https://paper.dropbox.com/doc/Reith-font-GEL-typography-specs-Article-issues--AU4yC9u0eH6HqXzVRUmPzR6wAg-r2S7GERgi4tNFSicqmQzL.

This work found no possible fix to make the solution perfect. Removing the padding seems to have some positive affects so https://github.com/BBC-News/simorgh/issues/1055 will be reopened and done on its own.
