### ISSUE TITLE
Talos undefined console errors

### ISSUE THREAD

**Issue by hotinglok** [BBC-archive/psammead#2241]
**Describe the bug**
When running `npm run test:unit`, two console errors show `undefined`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to local psammead repository.
2. Run `npm run test:unit`
3. ~Not profit.~

**Expected behaviour**
No console errors.
**Screenshots**
![image](https://user-images.githubusercontent.com/53564281/65613412-e7096680-dfad-11e9-8286-5835a1c4d4fa.png)

**Comment by FK78** [comment]
I'm unable to replicate this.

**Comment by HarveyPeachey** [comment]
I didn't get any console logs:
![Screenshot 2019-10-01 at 17 23 34](https://user-images.githubusercontent.com/4706195/65981079-4369fb80-e470-11e9-8142-889343301c9d.png)

**Comment by FK78** [comment]
I did not get any console log errors for `scripts/talos/getBranchName/index.test.jsx

![image](https://user-images.githubusercontent.com/34196381/66046871-8edae300-e51e-11e9-9932-beaed5260f29.png)

**Comment by hotinglok** [comment]
Unable to be replicated now as well, closing.
