### ISSUE TITLE
Fix datestamps discrepencies from documentation

### ISSUE THREAD

**Issue by AlistairGempf** [BBC-archive/psammead#2245]
**Describe the bug**
There are some discrepancies on the datestamps in comparison to what documentation has been made available.

*Mundo*
Date is displaying as `17 de julio de 2019`, we are expecting `17 julio 2019`.

*Brasil/Portuguese*
The date on Brasil/Portuguese is capitalised on the page but on the spreadsheet it’s completely lowercase.

*Serbian*
There is no Cyrillic reference on the documentation and it's unclear whether the latin date should include a completely lowercase month or one that includes a capitalised beginner letter.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'localhost.bbc.co.uk/7080/[mundo|portuguese|serbian/lat|serbian/cyr'
2. Scroll down to the timestamp of a story
3. See error

**Expected behaviour**

**Screenshots**
*Mundo*
![image](https://user-images.githubusercontent.com/43134742/65683812-24293380-e056-11e9-8a9b-1115c32353e3.png)
*Portuguese*
![image](https://user-images.githubusercontent.com/43134742/65684181-e547ad80-e056-11e9-99ff-83eb27bcfced.png)

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
Found as part of testing of [#3819](https://github.com/bbc/simorgh/issues/3819)

**Comment by j-pendlebury** [comment]
```
jordit  18 hours ago
The spread sheet is right for Mundo and Brasil: lowercase month names no preposition (de).


jordit  18 hours ago
In Serbian months names are also lowercase. so the Capital on the Latin month name is wrong in the spreadsheet
```
