### ISSUE TITLE
Add a play button to Media Player placeholder

### ISSUE THREAD

**Issue by simonsinclair** [BBC-archive/psammead#2248]
**Is your feature request related to a problem? Please describe.**
We need to add a play button to the placeholder images of the media player, so that users are aware it is playable.

**Describe the solution you'd like**
1. We should create `psammead-play-button` following the UX specification.
2. Overlay it on Media Player placeholder.

![image](https://user-images.githubusercontent.com/7690572/63012330-f4e1ad00-be81-11e9-8713-d10611650e68.png)

Designs, including screenreader UX:
- Default state for play button, (with duration displayed): https://zpl.io/aMK7WBd
- Hover/focus state for play button (with duration displayed): https://zpl.io/VOKM56l

According to the UX spec, the visually hidden text should follow this format for video:
- `Play video, "Video Title", 1 minute 40 seconds`

And this format for audio:
- `Play audio, "Audio Title", 1 minute 40 seconds`

We can get this information from the media block that we're embedding.

We will need to add a story into Storybook with this logic.

Accessibility notes:
```
HTML:
Button

Announced text:
Play video, "Video Title", 1 minute 40 seconds (Duration not possible with current version of SMP) 

Landmark: 
Sits within Primary (primary content)

NB:
- Sit within a 'figure'
- Image alt text should not be read out
```

**Describe alternatives you've considered**
n/a

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
- The play button will be the same for audio and video for the MVP.
- We can look at iterating on this at a later stage to introduce a 'speaker' icon for audio.
- The play button would be used in a Placeholder component, which might also house things like Guidance warnings etc.

**Comment by dr3** [comment]
👋 Hey, IMO this is a very different component to media indicator, being a button with hover states. Also IMO its not technically an indicator of media, to a user, it is media (play button)

Can I suggest, like MediaIndicator
```jsx
import MediaIndicator from '@bbc/psammead-media-indicator';

<MediaIndicator
  duration="2:15"
  datetime="PT2M15S"
  type="audio"
  service="news"
/>;
```
We perhaps make a new component called PlayButton?
```jsx
import PlayButton from '@bbc/psammead-play-button';

<PlayButton
  duration="2:15"
  datetime="PT2M15S"
  type="audio"
  service="news"
  onClick={() => {}}
  title="I am a video title"
/>;
```
(Props may need to change, as we may want different colours for different uses/ different duration logic 😄)

Then I imagine `@bbc/psammead-play-button` would be used in a `Video Placeholder` component with the guidence warning? haha

**Comment by sareh** [comment]
I agree with @dr3's suggestion, since looking at the Accessibility notes in Zeplin, we have this:
```
HTML:
Button

Announced text:
Play video, "Video Title", 1 minute 40 seconds (Duration not possible with current version of SMP) 

Landmark: 
Sits within Primary (primary content)

NB:
- Sit within a 'figure'
- Image alt text should not be read out
```

So the semantics of the component are entirely different, as well as the style of the SVG alongside the duration. So having a `button` styled element imported as  `import PlayButton from '@bbc/psammead-play-button';` sounds good.

**Comment by simonsinclair** [comment]
Hey @dr3 @sareh, thanks for the steer.

I drafted this issue based on the parent found here https://github.com/bbc/simorgh/issues/3135 and it was clear this might end up being an extension of or different component from the media indicator.

I won't be picking it up properly until Monday, but will go over your comments in greater detail before then and update the ticket. Keep an eye on it. 😄 Thanks for all the additional information.
