### ISSUE TITLE
Navigation iteration prototype

### ISSUE THREAD

**Issue by AlistairGempf** [BBC-archive/psammead#2291]
**Is your feature request related to a problem? Please describe.**
The navigation bar needs a prototype of a new iteration.

**Describe the solution you'd like**
The navigation bar should have a dropdown menu and all the links to the right in a swipable format.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
This is just a prototype.

**Comment by DenisHdz** [comment]
Closed as done https://github.com/bbc/psammead/pull/2302
