### ISSUE TITLE
Create rich-text-transforms utility package

### ISSUE THREAD

**Issue by pjlee11** [BBC-archive/psammead#2301]
**Is your feature request related to a problem? Please describe.**
For the MAP work we need to find a way to render the `candy_xml` format we get from Ares. The WebCore team have built an XML parser that we can make use of however it is not publicly available on `npm`. Therefore we should host it on psammead so that it can be used within Simorgh. 

We should use the version of this library that has `ramada` and `xml2js` as it is smaller and safer - `fabl-modules/pull/126`

**Describe the solution you'd like**
Copy the `rich-text-transforms` library from the `fabl-modules` repo and deploy it via psammead.

**Describe alternatives you've considered**
Rather than copying the library we could make the other repo open source but this would be a slow process that would block the use of this library in Simorgh. 

**Testing notes**
No testing required 

- ~[ ] This feature is expected to need manual testing.~

**Additional context**

**Comment by sareh** [comment]
@pjlee11 I'd suggest asking the `fabl-modules` maintainers to publish `rich-text-transforms` to npm publicly themselves, rather than create a forked version that'll continually go out of date.

**Comment by pjlee11** [comment]
@sareh we've discussed this with them and have agreed to fork due to concerns about changing one of their modules to be publicly available will the rest are private, with all being contained in a private repo.

**Comment by dr3** [comment]
Can I suggest we review and move https://github.com/bbc/fabl-modules/pull/126 to psammead, instead of master?

**Comment by pjlee11** [comment]
@dr3 it's already in the description 

>We should use the version of this library that has ramada and xml2js as it is smaller and safer - fabl-modules/pull/126
