### ISSUE TITLE
Implement new line heights for Latin diacritic services

### ISSUE THREAD

**Issue by jimjohnsonrollings** [BBC-archive/psammead#2345]
**Is your feature request related to a problem? Please describe.**
Services in Latin diacritics need new line heights to avoid their diacritics crashing into the line above. 
The services are:  Afrique, Azeri, Turkish, Serbian Latin, Vietnamese, Brasil, Mundo
Example of the problem: Vietnamese double-stack their diactrics on top of letters, which means they sometimes crash into the line above.

**Describe the solution you'd like**
Increase the line heights for these services, as follows:

Element | Font spec used | New line height Group A | New line height Group B | New line height Group D |
------------ | ------------- | ------------- | ------------- | -------------
H1 | canon | 36 | 42 | 58
H2 | trafalgar | 28 | 32 | 42
H3 / Quote | paragon | 26 | 30 | 38
H4| double-pica | 24 | 26 | 32

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by jimjohnsonrollings** [comment]
Blocked pending UX signoff

**Comment by lizcameron** [comment]
UX have asked for these new line heights to be applied to all Latin diacritic services. Issue updated to reflect this.

**Comment by sareh** [comment]
Work has been carried out in Psammead: https://github.com/bbc/psammead/pull/2462 Just needs to be pulled in to Simorgh.

**Comment by lizcameron** [comment]
Closed via https://github.com/bbc/psammead/pull/2462
