### ISSUE TITLE
We need a way to watch+build psammead packages

### ISSUE THREAD

**Issue by mykeels** [BBC-archive/psammead#2357]
**Is your feature request related to a problem? Please describe.**
I was working on a bug in simorgh that depended on a psammead package, and there was no way to build the psammead package on the fly, using `yarn link`.

**Describe the solution you'd like**
A way to build psammead packages, and have it update a dependent build in simorgh, if they're connected by `npm link` or `yarn link`.

**Describe alternatives you've considered**
Build the psammead package, and restart the build (slow).

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Comment by FK78** [comment]
https://www.viget.com/articles/how-to-use-local-unpublished-node-packages-as-project-dependencies/

This seems like a decent solution.
