### ISSUE TITLE
Lock down NPM Publishing

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#236]
**Is your feature request related to a problem? Please describe.**
Currently all of the articles team can publish to NPM, while we do all have 2FA it would be more secure to only allow `bbc-online` to publish packages. This also has the benefit of all publishes being emailed to the mailing list. 

**Describe the solution you'd like**
Lock down the current packages and stop new packages from being automatically assigned with us as maintainers.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
This is done I think
