### ISSUE TITLE
Use a small XML parser

### ISSUE THREAD

**Issue by pjlee11** [BBC-archive/psammead#2363]
**Is your feature request related to a problem? Please describe.**
As described in this comment https://github.com/bbc/simorgh/pull/4184#issuecomment-540079051 the package `xml-js` in `psammead-rich-text-transforms` isn't big as a published size but the install size is significantly bigger than expected. 

**Describe the solution you'd like**
Find and use a smaller parser for `psammead-rich-text-transforms`

**Describe alternatives you've considered**
Accept the 90KB+ increase and split the bundles so `xml-js` is only included on page that require it to render. 

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- ~[ ] This feature is expected to need manual testing.~

### Additional context
Tried and not suitable: 

**xml2json-light**
Ignores text between nodes 
`</paragraph><bold>this is okay</body>this is lost</paragraph>`

**fast-xml-parser**
Combines matching nodes and doesn't keep the order when multiple matched

Now trying
**xmldoc** 
Looks promising with the complicated example.

**Comment by pjlee11** [comment]
Both `xml-js` and `xmldoc` rely on `sax` which has an install size of [54KB](https://packagephobia.now.sh/result?p=sax@1.2.4). `xml-doc` has an install size of 90KB which means it may not end up being smaller than `xml-js` 🤔

**Comment by ibMadbouly** [comment]
😢 conditional bundling, only when user loads CPS Asset ?
