### ISSUE TITLE
psammead-rich-text-transforms: swap reduce for forEach

### ISSUE THREAD

**Issue by pjlee11** [BBC-archive/psammead#2367]
**Is your feature request related to a problem? Please describe.**
Currently the package `psammead-rich-text-transforms` is using a `reduce` when looping over the XML nodes. This seems to be because there are duplicates in the returned data which leads me to believe that we are looping over the data more times than necessary. We should be able to use `forEach` and `push` to ensure we only loop over the data as few times as possible. 

**Describe the solution you'd like**
Remove the `reduce` and use `forEach` and `push` to ensure the least looping possible. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: The current unit tests passing proves the functionality is correct.

- ~[ ] This feature is expected to need manual testing.~

**Additional context**

**Comment by graeme-lindsay** [comment]
This tech debt, will close off until it is causing a problem
