### ISSUE TITLE
psammead-rich-text-transforms: nested element support

### ISSUE THREAD

**Issue by pjlee11** [BBC-archive/psammead#2378]
**Is your feature request related to a problem? Please describe.**
The current `psammead-rich-text-transforms` doesn't support complex nested structures. We should evaluate if this type of support is needed or if it's not required based on the input data. 

**Describe the solution you'd like**
If we deem necessary, add the test example in **Additional context** and support complex nested structures in `psammead-rich-text-transforms`

**Describe alternatives you've considered**
If the input will never be this complicated then close this issue. 

**Testing notes**
[Tester to complete]

Dev insight: Unit test

- ~[ ] This feature is expected to need manual testing.~

**Additional context**
A test case like this shows the current issues. 
```
test('can handle horrible nesting', () => {
  const richText = candyXmlToRichText(
    createBody(
      '<paragraph>Some <foo>text <bar>content with<meh> </meh>many nested</bar></foo> tags</paragraph>',
    ),
  );

  expect(richText).toStrictEqual({
    type: 'text',
    model: {
      blocks: [
        {
          type: 'paragraph',
          model: {
            text: 'Some text content with many nested tags',
            blocks: [
              {
                type: 'fragment',
                model: {
                  text: 'Some ',
                  attributes: [],
                },
              },
              {
                type: 'fragment',
                model: {
                  text: 'text ',
                  attributes: [],
                },
              },
              {
                type: 'fragment',
                model: {
                  text: 'content with',
                  attributes: [],
                },
              },
              {
                type: 'fragment',
                model: {
                  text: ' ',
                  attributes: [],
                },
              },
              {
                type: 'fragment',
                model: {
                  text: 'many nested',
                  attributes: [],
                },
              },
              {
                type: 'fragment',
                model: {
                  text: ' tags',
                  attributes: [],
                },
              },
            ],
          },
        },
      ],
    },
  });
});
```

**Comment by ryanmccombe** [comment]
This is part of a wider concern around what type of data we can expect back from CPS

We need some analysis on what we need to support.  Ideally to gather up a wide range of CPS payloads in order to automate the testing of this

Related issue: https://github.com/bbc/simorgh/issues/4393

**Comment by aeroplanejane** [comment]
Closing - need to investigate
