### ISSUE TITLE
Update psammead-media-player prop documentation

### ISSUE THREAD

**Issue by simonsinclair** [BBC-archive/psammead#2475]
**Describe the bug**
The Media Player API changed in https://github.com/bbc/psammead/pull/2317. At the moment the [`README`](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-media-player/README.md) for `psammead-media-player` is outdated, as some props introduced by this and other work haven't been properly documented.

**Describe the solution you'd like**
Go through props within both the [amp](https://github.com/bbc/psammead/blob/0be6fee4b760960535d08b9260c44d4ed1604942/packages/components/psammead-media-player/src/index.jsx#L106) and [canonical](https://github.com/bbc/psammead/blob/0be6fee4b760960535d08b9260c44d4ed1604942/packages/components/psammead-media-player/src/index.jsx#L79) media player to see what props are missing from the documentation and add them accordingly.

**Additional context**
Example prop not documented: https://github.com/bbc/psammead/blob/0be6fee4b760960535d08b9260c44d4ed1604942/packages/components/psammead-media-player/src/index.jsx#L88 which isn't documented in the [`README`](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-media-player/README.md) prop table

**Comment by HarveyPeachey** [comment]
[Comment on duplicated issue:](https://github.com/bbc/psammead/issues/2541#issuecomment-548831408) Whilst someone is updating documentation, I noticed that the list of packages is also out of date: https://github.com/bbc/psammead/blob/latest/packages/README.md#list-of-all-packages
