### ISSUE TITLE
Psammead Calendars - Pashto on storybook is not displaying correctly

### ISSUE THREAD

**Issue by HarveyPeachey** [BBC-archive/psammead#2478]
**Describe the bug**
The Jalaali calendar for Pashto is not displaying correctly on [storybook](https://bbc.github.io/psammead/?path=/story/utilities-psammead-moment-calendars--jalaali-pashto). This is because the Pashto locale needs to be imported into the story.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://bbc.github.io/psammead/?path=/story/utilities-psammead-moment-calendars--jalaali-pashto
2. See that it displays in English and then displays nothing

**Expected behaviour**
To show the gregorian calendar and the Jalaali calendar in Pashto

**Screenshots**
<img width="346" alt="Screenshot 2019-10-23 at 16 09 15" src="https://user-images.githubusercontent.com/4706195/67407538-8e7ab880-f5af-11e9-8e24-6082c010bd5c.png">

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Comment by karinathomasbbc** [comment]
This is now fixed!
