### ISSUE TITLE
Remove active state for items in navigation for articles

### ISSUE THREAD

**Issue by 12** [BBC-archive/psammead#2479]
**Is your feature request related to a problem? Please describe.**
Currently, there is this logic in `psammead-navigation`:
https://github.com/bbc/simorgh/blob/latest/src/app/containers/Navigation/index.jsx#L29

This is setting the active item in the navigation to always be `Home`. This works for world service homepages, but not for Articles, as the user is on an article... not a homepage.

**Describe the solution you'd like**
Add some logic to remove the active state from navigation items when the user is viewing an article.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by amywalkerdev** [comment]
Covered in https://github.com/bbc/simorgh/issues/5216
