### ISSUE TITLE
Storybook icons are broken on gh-pages storybook

### ISSUE THREAD

**Issue by radiocontrolled** [BBC-archive/psammead#249]
**Describe the bug**
psammead components have storybook icons at the top of their README. On the gh-pages hosted version of our storybook, each icon is broken.

![screen shot 2019-01-03 at 10 07 02](https://user-images.githubusercontent.com/916416/50632308-5aaaa580-0f3f-11e9-9756-47e81f4a8210.png)

**To Reproduce**

1. View https://bbc-news.github.io/psammead/
2. Observe that each storybook icon is broken.

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/psammead/labels/bug)

**Comment by dr3** [comment]
Closing as duplicate https://github.com/BBC-News/psammead/issues/246
