### ISSUE TITLE
Disable Chromatic QA on Moment Locales

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#2526]
**Is your feature request related to a problem? Please describe.**
As a result of the Simorgh Seniors meeting, it was decided to disable Chromatic QA from running on Psammead Locales' Moment stories.

This is so that UX and Product still have the stories visible, but that we do not have multiple diffs in Chromatic QA on each PR. 

**Describe the solution you'd like**
Can add a ` chromatic: { disable: true },` within a Storybook. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by DenisHdz** [comment]
Are we planning to do the same for the Simorgh - Editorial and Developer view stories?
