### ISSUE TITLE
Reduce height of Brand and Script Link components

### ISSUE THREAD

**Issue by AlistairGempf** [BBC-archive/psammead#2555]
**Is your feature request related to a problem? Please describe.**
The new brand designs have reduced the height of the brand component on breakpoints below 400px and the brand and script link components above 600px.

**Describe the solution you'd like**
Reduce the height of the components to match the designs.

**Testing notes**
- Manual testing in psammead storybook
- Ensure grid fallback working as expected in IE11

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

![image](https://user-images.githubusercontent.com/43134742/68137254-90813780-ff1e-11e9-8a28-d0fd6061fc72.png)

**Comment by DenisHdz** [comment]
The `Brand` doesn't look to be vertically centered inside the Banner. Is that expected?

<img width="680" alt="brand" src="https://user-images.githubusercontent.com/46446236/68388401-72068080-0158-11ea-8ed2-ebe3aedf5ee8.png">

<img width="316" alt="brand2" src="https://user-images.githubusercontent.com/46446236/68388434-8480ba00-0158-11ea-9759-794370ffed70.png">

**Comment by PriyaKR** [comment]
@AlistairGempf @OlgaLyubin are there zeplin docs to refer to the design changes?

**Comment by PriyaKR** [comment]
https://app.zeplin.io/project/5c8a5e021d454124ef90669f/screen/5db96f04b9175d22aa0036c5
