### ISSUE TITLE
Navigation: Create dropdown and toggle components

### ISSUE THREAD

**Issue by tochwill** [BBC-archive/psammead#2557]
**Is your feature request related to a problem? Please describe.**
The new navigation designs contain a burger menu icon, which opens a dropdown of navigation items when selected.

See burger menu in navigation in the designs in zeplin:
<img width="192" alt="Screenshot 2019-11-04 at 17 19 57" src="https://user-images.githubusercontent.com/6690955/68142464-641de900-ff27-11e9-928d-e4f6a25b8a16.png">

Once the burger menu has been interacted with, the dropdown menu is presented:
<img width="195" alt="Screenshot 2019-11-04 at 17 20 51" src="https://user-images.githubusercontent.com/6690955/68142513-7c8e0380-ff27-11e9-889c-b1685ac623b0.png">

(See zeplin for margin + padding values)

Right to left designs:
<img width="292" alt="Screenshot 2019-11-04 at 17 21 47" src="https://user-images.githubusercontent.com/6690955/68142567-9af3ff00-ff27-11e9-8940-48a1b613b4fc.png">

<img width="193" alt="Screenshot 2019-11-04 at 17 22 15" src="https://user-images.githubusercontent.com/6690955/68142606-ae06cf00-ff27-11e9-8311-40717f986887.png">

**Describe the solution you'd like**
- Add burger menu and cross icons to psammead assets.

- Currently this contains the same list of nav items as the scrollable navigation, but this will not always be the case, so the navigation dropdown needs to accept a separate list than the scrollable nav.

- This dropdown menu pushes the rest of the page content down, it does not overlay on top of it (just need to build the dropdown in psammead).

When the user interacts with the cross icon, the dropdown menu is closed. The interaction will need to be handled differently between Canonical and AMP pages - the psammead package should export presentational components that can be composed into the navigation, and controlled when integrated.

We can reuse the presentational components between AMP and Canonical exports, which accept event handlers in a format such as this (this is not meant to represent the final component design, just to show how to accept AMP and Canonical actions):

```
export AmpDropdown = ({ closeAction, children, etc... }) => (
    <DropdownWrapper>
        <button on={closeAction}><CloseIcon /></button>
        <DropdownList>
            {children}
        </DropdownList>
    </DropdownWrapper>
); 
```

```
export CanonicalDropdown = ({ onClose, children, etc... }) => (
    <DropdownWrapper>
        <button onClick={onClose}><CloseIcon /></button>
        <DropdownList>
            {children}
        </DropdownList>
    </DropdownWrapper>
); 
```

Similary for the burger menu:

```
export AmpBurger = ({ action, etc... }) => (
    <button on={action}><BurgerIcon /></button>
); 
```

```
export CanonicalBurger = ({ onClick, etc... }) => (
    <button onClick={onClick}><BurgerIcon /></button>
); 
```

(There may be a preferable name for this component than 'Burger' 🍔 )
- The burger menu and dropdown are only rendered < 600px.

- Screenreader UX can be found in zeplin: https://app.zeplin.io/project/5c8a5e021d454124ef90669f/screen/5db9725f3cab221121ebab72

**Describe alternatives you've considered**

**Testing notes**
Storybook testing in psammead

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by PriyaKR** [comment]
Looks good to me except one small font size with the dropdown menu ie) at 360-599px expected font size is 15px actual its 16px.If UX is fine with it then this PR can be merged.

**Comment by PriyaKR** [comment]
UX is fine with the above small issue.
