### ISSUE TITLE
Set max width on brand svg

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#256]
**Describe the bug**
When CSS is disabled the svg brand icon fills the full width of the page

**To Reproduce**

1. Go to an article when its using https://github.com/BBC-News/psammead/pull/253
2. Disable CSS
3. See the SVG is full width

**Expected behavior**

**Suggested Solution**
Set a width and height value that can be overriden in css

**Screenshots**
![image](https://user-images.githubusercontent.com/11341355/50646637-7d07e780-0f6e-11e9-98a8-0b6f8b29c080.png)

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/psammead/labels/bug)

**Comment by sareh** [comment]
Closed as fixed.
