### ISSUE TITLE
Update guidance message using new requirements

### ISSUE THREAD

**Issue by rhenshaw56** [BBC-archive/psammead#2562]
**Is your feature request related to a problem? Please describe.**
As part of https://github.com/bbc/simorgh/issues/3139, we added guidance message to the media placeholder [here](https://github.com/bbc/psammead/pull/2517), however we dd not have complete UX designs and a11y requirements in place for it. As of now, these have been provided by UX and we would need to make the following updates to the guidance component.

**Describe the solution you'd like**
- remove the guidance icon as it's no longer in the design
- use updated design to add support for screen widths of `240px` -> https://bit.ly/32hgE2g

**Describe alternatives you've considered**

**Testing notes**
- Manual regression testing required

Dev insight: Will there be any potential regression? etc

- [X] This feature is expected to need manual testing.

**Additional context**

**Comment by RayNjeri** [comment]
UX to provide designs for 240px screen size

**Comment by lizcameron** [comment]
Design for 240 screen size: https://app.zeplin.io/project/5baa564c05c2eba0d2b89568/screen/5dc18da9eceabf570125c09c
Note: screenreader UX is detailed at the 375 size design: https://app.zeplin.io/project/5baa564c05c2eba0d2b89568/screen/5c59ad1aa48da042125184d0
