### ISSUE TITLE
Bump all packages to version 1.0.0

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#257]
**Is your feature request related to a problem? Please describe.**
In https://github.com/BBC-News/psammead/pull/239, after some investigation of @bcmn he discovered that NPM has special treatment for semver versions under 1.0.0. They treat the first non-zero character as the 'major' version and thus `0.1.0` to `0.2.0` is a major breaking change, which I don't think any of us intend

**Describe the solution you'd like**
Pending a team discussion I would like us to bump all packages to version 1.0.0 to avoid this qwerk and we can start using the full semver `major` `minor` `patch` range.

**Additional context**
@bcmn Has a great comment here https://github.com/BBC-News/psammead/pull/239#issuecomment-451419401 describing the issue, as well as NPMs docs here https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
Stale
