### ISSUE TITLE
Failing Unit Test in psammead timestamp container

### ISSUE THREAD

**Issue by thekp** [BBC-archive/psammead#2570]
**Describe the bug**
Our current unit tests break on latest on Psammead, strangely it passes on CI but fails locally.

![image](https://user-images.githubusercontent.com/30599794/68223800-5a5abb00-ffe5-11e9-8023-eac7550f8639.png)

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'psammead  locally'
2. run 'npm run test:unit'

**Expected behaviour**
All tests should pass locally.

**Screenshots**

**Comment by mykeels** [comment]
Can this still be reproduced?

I couldn't reproduce it locally. Perhaps, it's a daylight savings time issue? I'll try fiddling with my system's datetime settings.

**Comment by thekp** [comment]
> I couldn't reproduce it locally. Perhaps, it's a daylight savings time issue? I'll try fiddling with my system's datetime settings.

it might be a current issue on our Greenwich Mean Time zone
