### ISSUE TITLE
Update changeScanner so it doesn't include all files

### ISSUE THREAD

**Issue by amywalkerdev** [BBC-archive/psammead#2651]
**Is your feature request related to a problem? Please describe.**
Our changeScanner script that runs on CI currently requires you to update the changelog and psammead base version number when any file is changed. [changeScanner](https://github.com/bbc/psammead/tree/latest/scripts/changeScanner)

<img width="561" alt="Screenshot 2020-06-23 at 14 04 14" src="https://user-images.githubusercontent.com/44577498/85406957-73a37e00-b55a-11ea-87ab-4f8da5c3c5f9.png">

**Describe the solution you'd like**
Is this useful for all files, or should we have a list of files that do not need a change and version bump? (e.g changing the codeowners)

This will need either a small discussion, or a review of the files in Psammead to decide which should be exluded from the changescanner requirements. Then implement some kind of exclusion list so the scanner does not run against those.

**Describe alternatives you've considered**
Keeping it how it is, which adds additional files to change on every single PR when it may not be necessary.

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by mykeels** [comment]
We could maintain a .scannerignore file, containing globs.
