### ISSUE TITLE
UX Investigation: Reith bugs when used with GEL typography specs

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#267]
**Describe the bug**
​​Within the Articles project we have come across several problems with the Reith font when used with the GEL typography specifications. This issue is to track the progress of the various issues we have found. Some of these issues are apparent when using other font faces however they are greatly emphasised when using Reith with GEL specs.

This has been written up by @pjlee11 in [a dropbox paper document](https://paper.dropbox.com/doc/Reith-font-GEL-typography-specs-Article-issues--AVPBBiOOYu3qKksmbx4cXHdgAg-r2S7GERgi4tNFSicqmQzL)

**Screenshots**
See [the dropbox paper document](https://paper.dropbox.com/doc/Reith-font-GEL-typography-specs-Article-issues--AVPBBiOOYu3qKksmbx4cXHdgAg-r2S7GERgi4tNFSicqmQzL)

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/psammead/labels/bug)

**Comment by pjlee11** [comment]
Review of the [investigation document](https://paper.dropbox.com/doc/Reith-font-GEL-typography-specs-Article-issues--AVuLmyRqSGEyNOnUQdVwXcSiAg-r2S7GERgi4tNFSicqmQzL) is needed

**Comment by pjlee11** [comment]
Reviews completed, handing off to UX to follow up on the document
