### ISSUE TITLE
Document method of linking psammead components to simorgh

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#268]
**Is your feature request related to a problem? Please describe.**
When we make a feature change in psammead, while it is useful to see it in storybook, having it within a simorgh article is much more useful

**Describe the solution you'd like**
Decide and document a method of showing local psammead changes in simorgh. This process must be agreed on with @jamesbrumpton as this is likely to be the primary method of testing psammead components for the article page

**Describe alternatives you've considered**
Looking at the storybook, crossing your fingers and testing properly when its pulled into simorgh. 

Dev insight: This might have issues with multiple instances of styled-components, 1 in psammead and 1 in simorgh

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Is this still worth doing?

**Comment by dr3** [comment]
I think so @ChrisBAshton, me and sareh were talking earlier about how we still need to fix somethings about how they link, I think @sareh is gunna raise an issue

**Comment by jamesbhobbs** [comment]
Added to this higher level issue: https://github.com/bbc/psammead/issues/1838
