### ISSUE TITLE
Psammead Grid Fallbacks, Bugs and Edge Cases

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#2722]
**NB:** This issue is just to maintain log of work that's already done vs the remaining work on the Grid.

**Is your feature request related to a problem? Please describe.**
The `Grid` component has some untested edge cases and outstanding bugs, we should test them and fix all known bugs.

**Note**
This table shows all possible combinations for `Margin`, `Gutters`, `Start Offset `and `Nested Grid` along with whether these combinations 1, `match the grid implementation`, and 2, `are used in simorgh`.

| Margin | Gutters | Start Offset | has nested Grid | Is fixed? (As in, matches Grid layout) | Used on Simorgh pagetypes (currently) |
| --         | --          | --                 | --                        | --         | --         |
| Yes | No | No | No | Yes, matches Grid implementation | ?  |
| Yes | No | Yes | No | Yes, matches Grid implementation |?  |
| Yes | No | No | Yes | Yes, matches Grid implementation |?  |
| Yes | No | Yes | Yes | |?  |
| Yes | Yes | No | No | |?  |
| Yes | Yes | Yes | No | |?  |
| Yes | Yes | No | Yes | | WS Front Pages  |
| Yes | Yes | Yes | Yes | ~Has issue with `padding: 0 1rem` for margin implementation only being applied to first child - see <Screenshot 1>~ fixed in https://github.com/bbc/psammead/pull/2796 | Articles  |
| No | No | No | No | Yes, matches Grid implementation |?  |
| No | No | Yes | No | Yes, matches Grid implementation |?  |
| No | No | No | Yes | Yes, matches Grid implementation |?  |
| No | No | Yes | Yes | |?  |
| No | Yes | No | No | |?  |
| No | Yes | Yes | No |Yes, matches Grid implementation (Frontpages) |WS Front Pages |
| No | Yes | No | Yes | |?  |
| No | Yes | Yes | Yes | |?  |

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by thekp** [comment]
Another grid issue, where the last child would not be formatted as expected. Issue occurs on IE, can be replicated by viewing storybook for grid (top story slice).  https://github.com/bbc/psammead/issues/2781

![image](https://user-images.githubusercontent.com/30599794/69958397-a0c80a80-14fc-11ea-8f79-f1c7a0c5c79b.png)

**Comment by EinsteinNjoroge** [comment]
Known issue with the padding on IE https://github.com/bbc/psammead/issues/2780
<img width="600" alt="Screenshot 1" src="https://user-images.githubusercontent.com/3028997/69865334-d371c900-1298-11ea-90b2-fd2a6257c6af.png">

**Comment by EinsteinNjoroge** [comment]
https://github.com/bbc/psammead/issues/2722#issuecomment-560370012 & https://github.com/bbc/psammead/issues/2722#issuecomment-561619072 will be fixed in https://github.com/bbc/psammead/pull/2796

**Comment by sareh** [comment]
Closed as fixed.
