### ISSUE TITLE
MostReadList numbers do not follow the correct direction in IE

### ISSUE THREAD

**Issue by hotinglok** [BBC-archive/psammead#2742]
**Describe the bug**
`grid-auto-flow` is not supported in IE11 which means that the numbers do not go vertically in IE11. Second screenshot also shows some spacing issues with the last item but this is not relevant to this issue.

**To Reproduce**
Steps to reproduce the behaviour:

1. Run storybook `npm run storybook`
2. Go to `MostRead` -> `List` -> Any story.
3. Change breakpoints 

**Expected behaviour**
Chrome:
![image](https://user-images.githubusercontent.com/53564281/69952121-71aa9c80-14ee-11ea-83ed-5e6ee0d0f8cd.png)
![image](https://user-images.githubusercontent.com/53564281/69952116-6a838e80-14ee-11ea-965d-6937e358e73b.png)

**Screenshots**
IE:
![image](https://user-images.githubusercontent.com/53564281/69952006-3d36e080-14ee-11ea-8969-5e99bbc59f99.png)
![image](https://user-images.githubusercontent.com/53564281/69952039-4aec6600-14ee-11ea-982f-36ee35cfcd6a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by thekp** [comment]
I believe we are accepting this IE bug. Closing this issue.
