### ISSUE TITLE
Update Psammead snapshots (react-testing-library)

### ISSUE THREAD

**Issue by radiocontrolled** [BBC-archive/psammead#276]
**Is your feature request related to a problem? Please describe.**
After https://github.com/bbc/psammead/issues/273 is complete, the Psammead snapshots should be updated. 

The package.json version numbers will have to be updated. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by radiocontrolled** [comment]
Blocked on https://github.com/bbc/psammead/issues/273

**Comment by PriyaKR** [comment]
Associated PR [Use react-testing-library for Simorgh bbc/simorgh#1182](url) is now closed and this mainly requires updating the snapshots using react-testing-library.

**Comment by jroebu14** [comment]
`react-testing-library` has only been implemented in Simorgh. Before picking up this issue we need to complete https://github.com/bbc/psammead/issues/273 to implement `react-testing-library`* in Psammead.

*`react-testing-library` is now called `@testing-library/react`.

**Comment by chris-hinds** [comment]
blocked on #273
