### ISSUE TITLE
Update psammead-styles to reflect updated UX colours & fonts

### ISSUE THREAD

**Issue by bcmn** [BBC-archive/psammead#277]
**Is your feature request related to a problem? Please describe.**
UX have changed the colours utilised by the article. `psammead-styles` should reflect these new values & their names.

**Describe the solution you'd like**
All new UX colours are exported from `psammead-styles/colours`. These are:
- Shadow: `#3F3F42`
- Cloud-dark: `#757575`
- Cloud-light: `#BABABA`
- Lunar: `#F2F2F2`
- Ghost: `#FDFDFD`
- White: `#FFFFFF`

All UX-required font families are exported from `psammead-styles/fonts`. These are:
- Reith Serif Medium
- Reith Serif Medium Italic
- Reith Sans Regular
- Reith Sans Regular Italic
- Reith Sans Bold
- Reith Serif Light (n.b. Only in Most read, subset of numerals only, may not be visible in V1)

We should keep the colours that are no longer used in `psammead-styles` for now. 

We're adding more functionality, so a minor version bump should be used. Note: since we're still sub-1.0, this counts as a 'major' version, so consuming components need to have their package.json dependency versions updated. 

**Describe alternatives you've considered**

**Testing notes**
Happy to not write Cypress tests that test Psammead specifically. Will revisit this once it has been integrated with Simorgh.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
Please ensure we add tests for these new exports, see [docs for details](https://github.com/bbc/psammead/tree/latest/packages/utilities/psammead-styles#contributing)
