### ISSUE TITLE
Read&Write is not reading the script link on IE11 on windows (and incorrectly on Chrome)

### ISSUE THREAD

**Issue by tochwill** [BBC-archive/psammead#2776]
**Describe the bug**
Read&Write is not reading the script link on IE11 on windows. On Chrome, on hovering over the script link, all of the content of the Brand component is read. A javascript error is then thrown by the browser extension, and the link is not read again on a second hover:

<img width="423" alt="Screenshot 2019-12-04 at 17 47 33" src="https://user-images.githubusercontent.com/6690955/70167254-3959b880-16be-11ea-952d-1f2822c51680.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Brand component in psammead storybook
2. Use Read&Write software, and set to 'Read the Web' mode (or 'Hover' mode on chrome)
3. Hover over script link

**Expected behaviour**
Read&Write should read the content of the script link.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by greenc05** [comment]
I would expect this to read 'Lat' when 'Read the web' is selected and you hover over the item (as it does for each of the nav items. Could be down to some of the CSS we have used??

**Comment by greenc05** [comment]
Actually looks like this isn't reading out in IE because of the after CSS that we are using, as we are effectively adding a 'layer' with CSS over the text and the AT can't reach it. If this is the only way we can write the CSS to achieve the UX then ignore this issue, though I suspect we could re-write the CSS?

**Comment by ghost** [comment]
This seems to be a bug on the Read&Write extension. It happens on any page after reading out what is hovered. Even google.com

<img width="423" alt="Screenshot 2019-12-04 at 17 47 33" src="https://user-images.githubusercontent.com/6690955/70167254-3959b880-16be-11ea-952d-1f2822c51680.png">

Chrome reading all of the content of the Brand component can be solved by adding an extra `div` to wrap the `scriptLink`.

**Comment by ghost** [comment]
```css
 a {
      text-decoration: none;
      padding: 0 1rem;
      border: 0.0625rem solid black;
      height: 3rem;
      display: inline-block;
      margin: 0.1875rem;
      line-height: 3rem;
    }
    a:hover {
      border: 0.25rem solid black;
      margin: 0;
    }
```
When run in isolation this works and fixes the IE read&write issue. But when putting this to the `scriptLink` component we notice some wiggling on hover.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/48688870/71093245-e271da00-21b9-11ea-8389-f81891289e75.gif)

When run in isolation: https://react-drxzzs.stackblitz.io
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/48688870/71093380-1ea53a80-21ba-11ea-8547-14445aa3d0a7.gif)
