### ISSUE TITLE
Investigate italic typeface implementation

### ISSUE THREAD

**Issue by bcmn** [BBC-archive/psammead#281]
**Is your feature request related to a problem? Please describe.**
We want to investigate italicised fonts, & ensuring that we are able to retain the semantic meaning offered by `<i>` tags (particularly around accessibility) while ensuring we accurately represent the desired UX. We want to ensure we can declare a fontface as italic, allowing us this semantic markup, without risking altering the font.

**Describe the solution you'd like**
We have a clear recommendation for how we will implement italic typefaces going forward.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by dr3** [comment]
Have moved this investigation into https://github.com/bbc/psammead/issues/285
