### ISSUE TITLE
Most Read Storybook doesn't work with service variants

### ISSUE THREAD

**Issue by thekp** [BBC-archive/psammead#2832]
**Describe the bug**
https://bbc.github.io/psammead/?path=/story/components-mostread--default-rtl
When trying to use a service with a variant, it does not work.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://bbc.github.io/psammead/?path=/story/components-mostread--default-rtl'
2. Click on 'click on a service with a variant'
3. See error

**Expected behaviour**
It should show the component with the translations for that selected service.

**Screenshots**
![image](https://user-images.githubusercontent.com/30599794/70990213-f1bf2d80-20bc-11ea-91ca-0a082871ed96.png)

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by FK78** [comment]
When selecting a service without a variant the title translation `Most Read` does not change.
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/34196381/71723706-92378080-2e25-11ea-9596-fcbbeb912909.png">

**Comment by FK78** [comment]
Further investigation shows that none of the translations are working.
