### ISSUE TITLE
Investigate font-face and font-family usage

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#285]
**Is your feature request related to a problem? Please describe.**
We have a requirement to use the following fonts
```
Serif Medium
Serif Medium Italic
Sans Regular
Sans Regular Italic
Sans Bold
Serif Light
```
Currently we treat the ones we do have as separate font families. This causes issues when we want the italic font as the fallback is helvetica, a non italic font.

**Describe the solution you'd like**
Investigate working font-face and font-families for psammead. The fonts should all work when desired and fallback to a suitable alternative (.e.g bold reith -> bold helvetica, italic reith -> italic helvetica)

We want to investigate italicised fonts, & ensuring that we are able to retain the semantic meaning offered by `<i>` tags (particularly around accessibility) while ensuring we accurately represent the desired UX. We want to ensure we can declare a fontface as italic, allowing us this semantic markup, without risking altering the font.

Based on a short investigation we will likely have many font faces under 2 font families `ReithSerifLatin` and `ReithSansLatin`.

On a branch, have these updated font-face declarations using these two Serif and Sans font families. Show examples of the fallbacks working as expected for each of the examples.

An outcome of this investigation should be a PR to add the font-faces to the component library. The readme should explain how the fallbacks work. 

**Testing notes**
As it's an investigation, it won't be tested.

Dev insight: 

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by sareh** [comment]
I agree about treating italic fonts similar to our non-italic fonts. Just a note about fallbacks:

There are set 'font stacks' for GEL: https://www.bbc.co.uk/gel/guidelines/typography

>Sans serif: BBC-Reith-sans, Helvetica, Arial, sans-serif
>Serif: BBC-Reith-serif, Helvetica, Arial, sans-serif

The fallbacks are GEL-defined.

**Comment by bcmn** [comment]
```
  // Sans Regular
  @font-face {
    font-display: optional;
    font-family: ReithSansNewsRegular;
    font-style: normal;
    font-weight: 400;
    src: url('https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Rg.woff2') format('woff2'), url('https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Rg.woff') format('woff');
  }
  
  // Sans Regular Italic
  @font-face {
    font-display: optional;
    font-family: ReithSansNewsRegular;
    font-style: italic;
    font-weight: 400;
    src: url('https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_It.woff2') format('woff2'), url('https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_It.woff') format('woff');
  }

  // Sans Bold
  @font-face {
    font-display: optional;
    font-family: ReithSansNewsRegular;
    font-style: normal;
    font-weight: bold;
    src: url('https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_Bd.woff2') format('woff2'), url('https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_Bd.woff') format('woff');
  }

  // Sans Bold Italic
  @font-face {
    font-display: optional;
    font-family: ReithSansNewsRegular;
    font-style: italic;
    font-weight: bold;
    src: url('https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_BdIt.woff2') format('woff2'), url('https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_BdIt.woff') format('woff');
  }

  // Serif Medium
  @font-face {
    font-display: optional;
    font-family: ReithSerifNewsMedium;
    font-style: normal;
    font-weight: 600;
    src: url('https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_Md.woff2') format('woff2'), url('https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_Md.woff') format('woff');
  }
  
  // Serif Medium Italic
  @font-face {
    font-display: optional;
    font-family: ReithSerifNewsMedium;
    font-style: italic;
    font-weight: 600;
    src: url('https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_MdIt.woff2') format('woff2'), url('https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_MdIt.woff') format('woff');
  }
```

This would get us where needed for Simorgh -- I spoke to Jim, & he seems confident the sixth font is not `Serif Light`, but in fact `Sans Bold Italic`. Serif Light will not be needed by Simorgh for V1.0, whereas Bold & Italic is a valid combination.
