### ISSUE TITLE
Add dotfiles

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#29]
**Is your feature request related to a problem? Please describe.**
We should add dotfiles.

**Describe the solution you'd like**
`.gitignore`
```
**/.DS_Store
npm-debug.log*
**/node_modules
coverage
```

`.gitattributes` 
```
*.js text eol=lf
*.jsx text eol=lf
```

`.npmrc`
```
version=6.4.1
```
`.nvmrc`
```
v8.11
```

`.prettierrc`
```
 {
  "singleQuote": true,
  "trailingComma": "all"
 }
```

**Describe alternatives you've considered**
N/A

**Testing notes**

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by bcmn** [comment]
`.prettierrc` has already been handled by #21.
