### ISSUE TITLE
Radio Schedules: Generalise Bulletin component to allow for programme card designs

### ISSUE THREAD

**Issue by tochwill** [BBC-archive/psammead#2924]
**Is your feature request related to a problem? Please describe.**
The radio schedule programme card contains many of the same elements and behaviours of the bulletin component that is currently being used. Make sure we can make this component generic across both, and if we can, then update the component to allow it to be used in both situations. If we can't, see how we can reuse common elements across both components.

**Describe the solution you'd like**
- Ensure we can recolour the svg to blue (to allow for the 'next' state) in a similar manner to the way we recolour svgs at the moment.
- Consider being able to pass the heading as a child, so the component doesn’t need all of the code for all of the states (for example, don’t have booleans for ‘live’ and ‘next’ states, pass in the correct heading from the parent). 
- Have individual storybook stories for different states, and unit tests in Psammead.
- The whole card should be a link, as the bulletin component currently is. this is currently being done for story-promo here: https://github.com/bbc/psammead/blob/latest/packages/components/psammead-story-promo/src/index.jsx#L316-L326 
(we would need to add this code snippet to our link and a position relative to the element that we want to be included in the link area)

This doesn't include the timestamp above the card:

<img width="164" alt="Screenshot 2020-01-14 at 11 13 35" src="https://user-images.githubusercontent.com/6690955/72339920-207df300-36bf-11ea-9ea1-34ad2da9fbbb.png">

**Describe alternatives you've considered**
Building a new, separate, radio schedule programme card component.

**Testing notes**
Expected outcome is either generalised component which supports bulletin and radio schedule component or separate one for both.

Dev insight: Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
See designs here: https://app.zeplin.io/project/5c8a5e021d454124ef90669f/screen/5dc0724999d4a3572b675557

Screen reader UX can be seen here: https://app.zeplin.io/project/5c8a5e021d454124ef90669f/screen/5dc0724850731722a4aa767a

Pick this up as a pair for the initial investigation.

**Comment by EinsteinNjoroge** [comment]
Taking into consideration the specs for the program card, @itimirichard and I have decided to design an entirely new **_psammead-program-card_** component, so as not to add too much complexity into the bulletin component which serves both radio and TV bulletins. 

The main considerations here were 
1) The typography and font styles for the heading and summary are different
2) The paddings and margins combinations are different also different
3) Font and background colors are different as well

cc @tochwill @sareh
