### ISSUE TITLE
Radio Schedules: Clock icon and timestamp styling

### ISSUE THREAD

**Issue by tochwill** [BBC-archive/psammead#2926]
**Is your feature request related to a problem? Please describe.**
Off the back of https://github.com/bbc/psammead/issues/2925, export a component from Psammead with the clock icon, timestamp and horizontal line as seen in the [designs](https://app.zeplin.io/project/5c8a5e021d454124ef90669f/screen/5dc0724999d4a3572b675557), which can be composed inside a wrapping container alongside the radio schedule card component.

**Testing notes**
Expected according to the zeplin designs.

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
See designs here: https://app.zeplin.io/project/5c8a5e021d454124ef90669f/screen/5dc0724999d4a3572b675557

**Comment by tochwill** [comment]
Dependent on #2925

**Comment by EinsteinNjoroge** [comment]
Closed in https://github.com/bbc/psammead/pull/2988
