### ISSUE TITLE
Jenkins not running on new Psammead PRs

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#294]
**Describe the bug**
Opening new PRs no longer triggers Jenkins tests for Psammead.

**To Reproduce**

1. Open a PR
2. See that the Jenkins check never completes

**Expected behavior**
Jenkins check should complete with a Pass or Fail.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
No PR should be needed to fix this - but wanted to raise an issue to document it.

Current workaround is to trigger the 'scan repository now' button in Jenkins, but this isn't a great solution.

- [x] Initially labelled with ["bug"](https://github.com/bbc/psammead/labels/bug)

**Comment by sareh** [comment]
Added high priority label since this bug is slowing down development on PRs in Psammead, since for each new commit you currently have to manually run Jenkins.

**Comment by ChrisBAshton** [comment]
We had disabled the webhook. Have now re-enabled it in GitHub settings.

Props to Sareh for finding it.
