### ISSUE TITLE
Skip to content link overflows brand container < 400px

### ISSUE THREAD

**Issue by tochwill** [BBC-archive/psammead#2944]
**Describe the bug**
We reduced the height of the brand container on screen widths below 400px, and now the skip to content link doesn't fit inside:

<img width="261" alt="Screenshot 2020-01-16 at 11 49 02" src="https://user-images.githubusercontent.com/6690955/72522874-894ba380-3856-11ea-9639-0a570b806015.png">

This could be fixed without reducing the tappable area by changing the 'top' value from 0.5rem to 0 at this breakpoint (check with UX if this is an acceptable solution):

<img width="266" alt="Screenshot 2020-01-16 at 11 49 23" src="https://user-images.githubusercontent.com/6690955/72522951-b009da00-3856-11ea-8f04-5b9fe9bd7923.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'http://localhost:7080/afrique'
2. Tab through to skip to content link

**Expected behaviour**
The skip to content link should not overflow its container.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by nicolasj638** [comment]
UX: Happy to change ‘top’ value from 0.5rem to 0 at this breakpoint
