### ISSUE TITLE
Remove Lerna

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#297]
**Is your feature request related to a problem? Please describe.**
Currently, our recommended setup uses lerna. `npm run install:packages` (runs npm install and lerna bootstrap). The standard test command runs `lerna run test` as well. 

These are setups both for local development and also on CI. 
This is manageable currently, since currently Psammead is used by a single team and all of the components are used for that team's work.  When we shortly will have multiple teams' components within this library, as developers we will be often installing dependencies and running tests that will be unnecessary for our project. This wastes time. 
We should remove lerna and have a custom script implementation.

**Describe the solution you'd like**

We should remove lerna and instead have these npm scripts:
- `install-named-packages` allows passing in of a list of packages and *only* installs those locally.
- `test-named-packages` allows passing in a list of packages and *only* runs the npm test command for those. 
- (optionally, to be discussed:)`link-named-packages` allows passing in of a list of packages and npm links those locally.

The documentation should be updated to reflect this. 

We should also have this functionality:
- on each PR, there will be a check: _get a list of packages have been updated/ added in the PR_ . This list should be passed to the install script above and test script above. 
If we have any library-level tests, e.g ones against storybook, we should run these too.  

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Instructions should be clear to follow. We should be able to run the scripts locally as well as on CI. 

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
@sareh this doesn't seem to have been a problem, it's a tad slow locally, but until we have many many more packages we can live with it as-is imo

**Comment by sareh** [comment]
Agreed. Once it becomes a problem, a new issue can be written up to address it.
