### ISSUE TITLE
Add Amp-Geo to Psammead component library

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#298]
**Is your feature request related to a problem? Please describe.**
There are several amp components that are being used in Simorgh. `<amp-geo>` has set values relating to geo-restriction the EU that is subsequently used by the `<amp-analytics>` and `<amp-consent>` elements to determine whether they should collect analytics from the user's session. 

This issue is to add `<amp-geo>` as a react component within Psammead

**Describe the solution you'd like**
We should add a component to Psammead that returns the markup for `<amp-geo>`. The component should allow for returning other amp elements too, as we need them. (e.g. in future we'll likely want to pull out `<amp-analytics>` into Psammead too. 

It could be called `psammead-amp` & it could return the relevant React Amp components, such as this for AmpGeo:
```
const ampGeoData = {
  ISOCountryGroups: {
    eu: [
      'at',
      'be',
      'bg',
      'cy',
      'cz',
      'de',
      'dk',
      'ee',
      'es',
      'fi',
      'fr',
      'gb',
      'gr',
      'hr',
      'hu',
      'ie',
      'is',
      'it',
      'li',
      'lt',
      'lu',
      'lv',
      'mt',
      'nl',
      'no',
      'pl',
      'pt',
      'ro',
      'se',
      'si',
      'sl',
    ],
  },
};

const jsonInlinedScript = data => (
  <script
    type="application/json"
    /* eslint-disable-next-line react/no-danger */
    dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
  />
);

const AmpGeo = () => (
  <amp-geo layout="nodisplay">
    {jsonInlinedScript(ampGeoData)}
  </amp-geo>
);
```

**Describe alternatives you've considered**
We could have separate individual components for each AMP element. I think it'll be easier for use to have a single component that has all of these, for ease of use by users of Psammead who want to create an AMP page. 

**Testing notes**
[Tester to complete]

Dev insight: Unit tests should suffice. 

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by dr3** [comment]
The amp EEA list is inaccurate, we should update it before we merge this. AFK atm but the real list is on the original amp geo simorgh pr
