### ISSUE TITLE
Most Read: Confirm Accessibility Requirements

### ISSUE THREAD

**Issue by thekp** [BBC-archive/psammead#2985]
**Is your feature request related to a problem? Please describe.**
We recently conducted an accessibility swarm on the Most-Read component: https://bbc.github.io/psammead/?path=/story/components-mostread--default-ltr-with-timestamp

We need to confirm the following queries:

- do we want the number of the rank to be read out with the link when tabbing?
- when using the arrow key navigation, the screen reader already reads the index value of the item, is that sufficient enough (instead of having it as a prefix of the link), i.e it currently reads “link, list item x of 10”?

**Describe the solution you'd like**
Address the issues stated on this spreadsheet: 
https://docs.google.com/spreadsheets/d/1fL1IaWHfgjVnx3bt_ux2YN4mRR3pya9NDKHh15Vp0d8/edit#gid=0

And confirm the queries above.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by greenc05** [comment]
"do we want the number of the rank to be read out with the link when tabbing?" No as the number is not semantically part of the heading/title of the article that is linked to

**Comment by greenc05** [comment]
when using the arrow key navigation, the screen reader already reads the index value of the item, is that sufficient enough (instead of having it as a prefix of the link), i.e it currently reads “link, list item x of 10”? - **Agreed**
