### ISSUE TITLE
Scrollable Navigation - Android Talkback announces link twice when navigation scrolls

### ISSUE THREAD

**Issue by tochwill** [BBC-archive/psammead#2999]
**Describe the bug**
If a navigation item begins off screen, and focusing that item causes it to be brought onto the screen, talkback announces the text within that item twice (once before the link is brought into view, and once after).

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'localhost:7080/afrique'
2. Using talkback, scroll through the scrollable navigation until you reach an item that is off screen.

**Expected behaviour**
The item should only be announced once.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by DenisHdz** [comment]
Raised as part of swarm from https://github.com/bbc/simorgh/issues/4569.
