### ISSUE TITLE
Investigate updating font file location

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#302]
**Is your feature request related to a problem? Please describe.**
Currently, we're using fonts from the GEL endpoint: https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Rg.woff2 

We should check to see whether we should serve fonts from the Nav endpoint. e.g. from https://nav.files.bbci.co.uk/orbit/2.0.0-502.c3ab836/font/BBCReithSans_W_Rg.woff2

Sounds, iPlayer, CBBC, Sport & Homepage use fonts from `https://nav.files.bbci.co.uk`
Weather use fonts from `https://gel.files.bbci.co.uk/`
To maximise caching of fonts between pages, we'd want to also use the font files hosted on the `nav` domain.

**Describe the solution you'd like**
Decide whether there should be a change. If so, update the font declarations.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: We should update any unit and cypress tests to reflect any changes.

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
We should not use file from that location. We have built a new thing specifically for our needs that there will be another issue opened for.
