### ISSUE TITLE
Resolve circular dependency

### ISSUE THREAD

**Issue by FK78** [BBC-archive/psammead#3054]
**Describe the bug**
Related to https://github.com/bbc/simorgh/issues/5182

The latest update of `jest-styled-components` requires `styled-components` as a peerDependency, adding `styled-components` inside `psammead-test-helpers` causes a test failure.

Bumping of `styled-components` in the root `package.json` resolves the test failure above, but produces new test failures, this is because `psammead-test-helpers` is used throughout psammead.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to `psammead-test-helpers` and open `package.json`
2. Bump `jest-styled-components` and add `styled-components` as a peerDependency.
3. Run `npm install` inside `packages/utilities/psammead-test-helpers`
4. Run unit tests.
5. See error
6. Go to Psammead's root `package.json`
7. Bump `styled-components` to `5.0.0`
8. Run `npm install`
9. Run unit tests.
10. See error

**Expected behaviour**
No errors.
We should not have to publish a failing package.

**Screenshots**
![Screenshot 2020-02-04 at 10 55 23](https://user-images.githubusercontent.com/34196381/73738725-e8f1ec00-473c-11ea-8b42-4a0bfb2f1bf3.png)
Bumping `jest-styled-components` and adding `styled-components` as a peerDependency in `psammead-test-helpers`.

![image (1)](https://user-images.githubusercontent.com/34196381/73737513-adeeb900-473a-11ea-8a58-68c22eedf6a8.png)
Bumping `styled-components` in root `package.json`.

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by oluoluoxenfree** [comment]
This seems to be a recently reported issue to the `jest-styled-components` team: https://github.com/styled-components/jest-styled-components/issues/297#issuecomment-575607479

I don't think it's because the dependency is circular; I think it's the versions.

**Comment by mykeels** [comment]
I found that to bump styled-components to 5.0.0, we have to bump jest-styled-components to 7.0.0

It's also important to modify the package-lock.json in root to specify `^7.0.0` for the jest-styled-components version, and run `npm ci` instead of `npm i`, so the specified versions in the lock file are installed.

**Comment by sareh** [comment]
`jest-styled-components` has released 7.0.0, so can this ticket be unblocked? https://www.npmjs.com/package/jest-styled-components?activeTab=versions

**Comment by sareh** [comment]
It seems like this is still an issue. Still blocked pending this being fixed in jest-styled-components: https://github.com/styled-components/jest-styled-components/issues/297

**Comment by simonsinclair** [comment]
We've started tackling this as part of https://github.com/bbc/simorgh/issues/6922 and https://github.com/bbc/simorgh/issues/5182 with the merge of #3636 and #3638.
