### ISSUE TITLE
Format duration timestamp correctly for Radio Schedules

### ISSUE THREAD

**Issue by OlgaLyubin** [BBC-archive/psammead#3065]
**Is your feature request related to a problem? Please describe.**
The duration timestamp in the program-card does not use the correct time format. 

**Describe the solution you'd like**
Create the duration timestamp using the `Timestamp` component in order to transform unix time into a correct timestamp for the program card button.
Make sure that screen readers are announcing the duration correctly :  _Announced text: Duration 30,00_

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Comment by tochwill** [comment]
Can we also check with Jon/UX about formatting of the duration for each service?

**Comment by tochwill** [comment]
And we don't necessarily want duration to have the _same_ formatting as the start time, just that it is within a time element :)

**Comment by greenc05** [comment]
"And we don't necessarily want duration to have the same formatting as the start time, just that it is within a time element :)" - Time element for the displayed start time only? Not the visually hidden start time @tochwill ?

**Comment by tochwill** [comment]
That's correct! My understanding is we have the start time as a correctly formatted string within the H3 for visually hidden, use the semantic time element for the start time in the visual start time above the card (but this is marked as aria-hidden), and the duration in a time tag at the bottom of the card (and we have the translated word 'Duration' with the announced text). We've just gone through the issues again to make sure the requirements are clear as some things got confused in the initial ticket that was created.

**Comment by greenc05** [comment]
Sounds good @tochwill Just a typo above "That's correct! My understanding is we have the **start time** as a correctly formatted string within the H3 for visually hidden..."

**Comment by tochwill** [comment]
I'm don't think timestamp container is set up to handle durations (there's an example here: https://css-tricks.com/time-element/) - we aren't going to be using a unix timestamp for the duration, just a formatted duration (the format is MM:SS in the designs, but might differ by service?). We could use the timestamp _component_ though?

**Comment by OlgaLyubin** [comment]
@tochwill good point about the timestamp container, will update the ticket description. Though as I understand correctly, initially we will get duration as unix time? Since it will be `transmissionTimeEnd - transmissionTimeStart` from Ares data

**Comment by tochwill** [comment]
Aha, so the unix timestamp measures the time since the 'unix epoch' (Midnight 1 January 1970). If we take one away from the other, we will have worked out the duration, but that's not a 'unix timestamp' anymore - if we treat this as a unix timestamp and pass it into the formatters we use for that, we'll end up with the date that is the unix epoch + our duration (So, 00:20 on 1st January 1970 for a 20 minute programme), if that makes sense?

**Comment by tochwill** [comment]
We also get the duration from ares in this format: `PT19M`, for example. This is valid for the 'datetime' attribute in the time tag.
