### ISSUE TITLE
Investigate publishing Storybook per branch

### ISSUE THREAD

**Issue by bcmn** [BBC-archive/psammead#307]
**Is your feature request related to a problem? Please describe.**
Could we investigate a way of accessing Psammead Storybook for branches from Github pages?

Currently, when reviewing a visual change on a branch, I must:
- stash, shelve or reset my changes
- checkout the branch
- `npm run install:packages`
- `npm run storybook`

Many of these steps are already performed by our CI, & on merge the branch's changes will finally be published to `https://bbc.github.io/psammead/`.

It might speed up code review & testing to be able to view branches on Github Pages prior to merge (especially when this repo is more actively contributed to by multiple teams). For example, by simply visiting `https://bbc.github.io/psammead/update-headline-appearance/`.

**Describe the solution you'd like**
Investigate the concept, & make a series of clear recommendations regarding the following considerations:

- Feasibility
- Simplicity of implementation
- Clearing branches when merged or deleted?
- Doing so in a secure way -- perhaps limiting the process to only run for individuals with Github rights.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
This isn't scalable, we use github pages for storybook for latest and this is used by many people.
