### ISSUE TITLE
Navigation: Visually Hidden 'Skip to Content' text shown on Opera Mini 'Extreme Mode'

### ISSUE THREAD

**Issue by tochwill** [BBC-archive/psammead#3098]
**Describe the bug**
The text from the visually hidden 'skip to content' link is being rendered by Opera Mini in 'extreme mode' (on Android - this is known as 'Opera Mini' mode on iOS).

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to any page using Opera Mini extreme mode.

**Expected behaviour**
This should not be visible.

**Screenshots**

![visually hidden text](https://user-images.githubusercontent.com/6690955/74139759-d881bb80-4beb-11ea-915e-dcfe1cc0fcd4.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
This is only visible on the new navigation, blocking while creating a new PR to unrevert this.

**Comment by tochwill** [comment]
To test this, you can run the branch here: https://github.com/bbc/simorgh/pull/5484
You will need to download Opera Mini to an Android or iOS device.
On Android, set the Data Saving mode to 'Extreme'. On iOS, make sure you are running in 'Opera Mini' mode.
We don't have proper test environments yet that we can push a branch to. In the meantime, you can use heroku like Alistair sets out in this comment: https://github.com/bbc/simorgh/pull/5342#issuecomment-580704935
Then you can access this heroku deployed version of Simorgh from your device.

It's quite an involved process. If you have picked up this ticket and want a hand getting set up, let me know.

**Comment by j-pendlebury** [comment]
![Screenshot_20200213-094141__01__01](https://user-images.githubusercontent.com/13763899/74425051-fbf67180-4e4a-11ea-9a4c-1b81ff42594a.jpg)
This is what I get in Opera Mini on Extreme mode, the brand disappears completely (cookie banner appears as normal)

**Comment by jblaut** [comment]
+

**Comment by tochwill** [comment]
Hey! This is what's currently in latest (/live), you need to be looking at the branch mentioned in my comment above :) Our new Navigation PR fixed the issue that the brand is not visible, but now we can see the visually hidden text in the link.
