### ISSUE TITLE
Navigation: Scrollable menu does not scroll on Opera Mini Extreme mode

### ISSUE THREAD

**Issue by tochwill** [BBC-archive/psammead#3099]
**Describe the bug**
Horizontally scrollable areas are not scrollable on Opera Mini when using extreme mode. This can also be seen when visiting the BBC Sport website (for example https://www.bbc.co.uk/sport/football/league-one/table), and the barbican site (https://www.barbican.org.uk/).

We also have the burger menu, which does allow the dropdown navigation to work on Opera Mini extreme mode (although it requires javascript, the intermediate server used by Opera mini prerenders the state of the page after a user interaction, and updates the view). This means the content is available currently, but this is not an ideal solution.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to any page

**Expected behaviour**
We need to decide how to handle this behaviour.

**Screenshots**

![visually hidden text](https://user-images.githubusercontent.com/6690955/74140319-c2c0c600-4bec-11ea-9508-96c142b68e6b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
We don't currently have a solution for this, have blocked until we decide how to move forward.

**Comment by amywalkerdev** [comment]
Not going to be fixed by the Home team.
