### ISSUE TITLE
Live radio audio player background is off-white

### ISSUE THREAD

**Issue by rebeccamcginn** [BBC-archive/psammead#3112]
**Describe the bug**

When you go to https://www.bbc.com/tamil/bbc_tamil_radio/liveradio note that the background colour should be WHITE #FFFFFF

It is currently slightly off-white. We need to ensure that it matches the background colour of the page

**To Reproduce**
https://www.bbc.com/tamil/bbc_tamil_radio/liveradio

**Expected behaviour**
The background colour should be WHITE #FFFFFF

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Comment by joshcoventry** [comment]
@rebeccamcginn I cannot reproduce this, was it fixed?

**Comment by rebeccamcginn** [comment]
> @rebeccamcginn I cannot reproduce this, was it fixed?

Yes, iirc it was fixed with a Morph PR
