### ISSUE TITLE
README instructions throw errors

### ISSUE THREAD

**Issue by twinlensreflex** [BBC-archive/psammead#315]
**Describe the bug**
When following the instructions on the README the project doesn't run as the instructions say. Instead a lot of errors are thrown.

**To Reproduce**

1. Follow README Instructions from the beginning
2. Errors at `npm run storybook` and `npm run test`

**Expected behavior**

There should be no errors and the project should run.

**Additional context**
When running an `npm run build` before running `npm run storybook` it will work!

- [x] Initially labelled with ["bug"](https://github.com/bbc/psammead/labels/bug)

**Comment by sareh** [comment]
We could add `npm run build` at the start of both npm scripts for `storybook` and `test`
