### ISSUE TITLE
MostRead One Column on all breakpoints for CPS Story Pages

### ISSUE THREAD

**Issue by hotinglok** [BBC-archive/psammead#3178]
**Is your feature request related to a problem? Please describe.**
WS Stories are looking to use MostRead for their CPS story pages which involve it being used only in the one column layout we currently have for mobile breakpoints. 

**Describe the solution you'd like**
Exactly the same thing as we did where we added a `maxTwoColumns` prop but adjusting it to just be one column instead.

**Describe alternatives you've considered**
N/A for now

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
Ideally we would find a better way to make it adapt based on the parent container width but as everything is currently based on media queries and viewport widths, this is the quickest solution.

**Comment by HarveyPeachey** [comment]
~Blocked until https://github.com/bbc/simorgh/pull/5417 is merged~
