### ISSUE TITLE
Add story to test passing VisuallyHiddenText component as a child of Copyright

### ISSUE THREAD

**Issue by rossgaskell** [BBC-archive/psammead#326]
**Is your feature request related to a problem? Please describe.**
We need to test how the Copyright component works with visually hidden text for accessibility

**Describe the solution you'd like**
Add an example story for the Copyright component with a VisuallyHiddenText component

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by PriyaKR** [comment]
Looks good to me can be merged.
