### ISSUE TITLE
See all label is wrong background color

### ISSUE THREAD

**Issue by thekp** [BBC-archive/psammead#3275]
**Describe the bug**
We have recently changed the background of the entire application to be `C_GHOST` however some components had a hardcoded background of #FFF. Unfortunately, we missed out updating.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://www.bbc.com/igbo'
2. See section label with a `see all` label
3. Inspect the label.

**Expected behaviour**
The label should match the color of the background.

**Screenshots**
![image](https://user-images.githubusercontent.com/30599794/77064245-0de1ac00-69d7-11ea-8914-cd6dac8400f5.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by DenisHdz** [comment]
This should be fixed in this PR https://github.com/bbc/simorgh/pull/5893/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R87

**Comment by thekp** [comment]
Closing because the most recent changes in psammead-section-label fixes this issue and it just needs to be bumped in Simorgh
