### ISSUE TITLE
Consider adding eslint rule eol-last.

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#33]
**Is your feature request related to a problem? Please describe.**
To maintain consistency across the I think we should add the eslint rule `eol-last` with `"always"` This is clearly very opinionated so will need to agree that we want this.

**Describe the solution you'd like**
Add the rule and ensure that all files have a trailing newline

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by chris-hinds** [comment]
We need to see if this is provided by the prettier config and why we need this rule on its own.

**Comment by ryanmccombe** [comment]
This rule does seem to already be applied - it is part of the airbnb eslint config that we import

Removing an end-of-file line break and then running `npm run test:lint` does throw an error as expected
<img width="607" alt="Screen Shot 2019-06-07 at 10 36 26" src="https://user-images.githubusercontent.com/8601460/59095481-8546c300-8910-11e9-9073-320e40ea3424.png">
