### ISSUE TITLE
Program Card styling bugs

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#3300]
**Describe the bug**
- Program card summary should use Brevier. Currently using Long primer.
- Duration component has a 1 extra pixel white border
- Sound icon is not 12px high

<img width="709" alt="Screenshot 2020-03-25 at 13 37 37" src="https://user-images.githubusercontent.com/3028997/77542253-cf983100-6e9d-11ea-9ff8-737aa186fa90.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to www.test.bbc.com/hausa?renderer_env=live
2. Scroll down to Radio schedule component (below top stories)
3. See error

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by OlgaLyubin** [comment]
Styling bug on IE11 in high-contrast mode is in a separate issue: https://github.com/bbc/psammead/issues/3310

**Comment by greenc05** [comment]
"Duration component has a 1 extra pixel white border" If this is referring to a white border around each promo... then this is coming from the transparent border CSS we have for when a user changes colour preferences in FF/windows high contrast mode, we may need to look at a different way to implement the transparent border...
