### ISSUE TITLE
Radio Schedules - Duration markup

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#3303]
**Describe the bug**
Currently duration is read out twice - `datetime="PT29M30S"` 29 mintues, 30 seconds and the visually hidden text `Duration 29,30 `

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to `www.test.bbc.com/hausa?renderer_env=live`
2. Use VoiceOver on iOS (iPhone) to navigate to the Radio Schedules component
3. Hear duration read out twice. 

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac version 10.13.6
- Browser Safari version 12.1
- Version 12.1

**Testing notes**

- [x] This bug fix is expected to need manual testing with all AT.

**Additional context**
We'd like to simplify this as much as possible without compromising accessibility for screen reader users. 
e.g we should test a simpler layout with all our supported Assistive Tech devices. 
```
<time dir="ltr" datetime="PT29M30S"><span class="VisuallyHiddenText-sc-1yjwwa5-0 jFfEvX"> Duration 29,30 </span><span aria-hidden="true" class="DurationTextWrapper-sc-6oo8lp-10 dfaGSJ">29:30</span></time>

**Comment by greenc05** [comment]
I'd be interested to see if this is a bug with VoiceOver/iOS due to using the time element...
