### ISSUE TITLE
Simplify the DOM structure within Headings in the radio schedule component

### ISSUE THREAD

**Issue by tochwill** [BBC-archive/psammead#3305]
**Describe the bug**
We have complicated, nested DOM elements within headings inside the radio schedule programme card.

Heading level 3s are very complex - we should simplify the DOM where possible. Current setup is this:
```
<h3>
  <span role="text">
    <span>NEXT</span>
    <span class="VisuallyHiddenText">,</span>
    <span> جام جهان نما</span>
    <span class="VisuallyHiddenText">, ۱۵:۰۰, </span>
    <span>25/03/2020 GMT</span>
  </span>
</h3>
```

<img width="338" alt="Screenshot 2020-03-25 at 15 02 40" src="https://user-images.githubusercontent.com/6690955/77551038-bdbc8b00-6ea9-11ea-9555-7321e3020426.png">

An issue in NVDA that may be related:

When navigating via elements, first it reads `heading level 3/link` + the name of the headline + the start time (whithout the date), but when navigating to the next element, it reads again `heading level 3/link` + just the date. Should it be all announced at once as when navigating via headings/links?

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/hausa?renderer_env=live
2. Inspect the radio schedule heading

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by greenc05** [comment]
This bug is due to CSS... if you disable CSS NVDA reads out the h3/link as expected with one key press

**Comment by greenc05** [comment]
Also I only observe this bug when navigating via the down/up arrow key, it's fine when navigating via headings and links using 'h' or the 'tab' key

**Comment by greenc05** [comment]
This bug is due to using display block CSS on span.TitleWrapper-sc-6oo8lp-5 jjATGt if we change display block to display inline-block, this fixes this bug, I believe we will then also need to apply width 100% to the span in question to fix the layout... Though I notice that the hover styling is now only underlining the 1st part of the h3 (the title such as 'Shirin Rana') - how can we address that? Or maybe that's ok?? Can ask UX if we can't fix that....

**Comment by greenc05** [comment]
There is a related ZoomText bug "When using the TAB key to navigate through the feature, just the headline and start time are announced, not the date." This is also fix by changing the CSS as per above. Zoomtext should be re-tested when this has been implemented along with NVDA and all other AT.

**Comment by greenc05** [comment]
Before fixing this issue with CSS lets check it's not due to an escaped character in the code similar to the fix for the duration bug https://github.com/bbc/psammead/pull/3321
