### ISSUE TITLE
Update all timestamps to use service numerals

### ISSUE THREAD

**Issue by tochwill** [BBC-archive/psammead#3308]
**Is your feature request related to a problem? Please describe.**
In the radio schedules component, we are using the numerals as defined by the service:

<img width="1057" alt="Screenshot 2020-03-25 at 15 48 07" src="https://user-images.githubusercontent.com/6690955/77556337-4b9b7480-6eb0-11ea-91b3-c003c6ed6e42.png">

In media content, we are using western arabic numerals everywhere:

<img width="283" alt="Screenshot 2020-03-25 at 15 50 23" src="https://user-images.githubusercontent.com/6690955/77556402-6241cb80-6eb0-11ea-8aff-5bbf6b7ce1da.png">

We have spoken within the team, and agree that we should be consistent. Within our team, and after conversations with Jon and Jim, we would prefer to use the service numerals. We need to discuss this with other teams, and ensure that we keep this consistent across Simorgh.

**Describe the solution you'd like**
Decide which numerals to use, and then use them.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by tochwill** [comment]
Addendum from Jim: Where the numerals are used as a placeholder for duration on the SMP (standard media player) we should use western arabic as that's all that SMP can support. Everywhere else we would like to use the service numerals.

**Comment by tochwill** [comment]
The first step for implementing this would be to take a look at our current piecemeal approach, and decide on where a holistic approach could be taken to specify which numerals are used by which service in one central place (and not spread between simorgh and psammead). We currently have [psammead-locales](https://github.com/bbc/psammead/tree/latest/packages/utilities/psammead-locales), where numerals are defined. We could standardise in here and override for SMP in simorgh, or think about approaches.

**Comment by karinathomasbbc** [comment]
One for the discussion tomorrow - the date we see on the radio schedule is autogenerated by Nitro (? or some system after the episode has been broadcast) and is always in the same format `25/03/2020 GMT`.  I wanted to try and see if we could convert this into a date (rather than a string), which would then mean that we could use the service numerals.

**Comment by sareh** [comment]
@karinathomasbbc The radio schedule date has been updated to be autogenerated by the start datestamp in this draft PR: https://github.com/bbc/psammead/pull/3377


To update the duration on Story Promos, we need to update the psammead-timestamp-container to be able to use the localised numerals defined for the services. This should impact Bengali, Burmese, Nepali, Pashto, Persian.

**Comment by sareh** [comment]
Should be opened until we pull in `@bbc/psammead-timestamp-container` version 3.0.0 into all other Psammead dependencies.

**Comment by sareh** [comment]
Closed as fixed.
