### ISSUE TITLE
Add knobs to every component with text in storybook

### ISSUE THREAD

**Issue by rossgaskell** [BBC-archive/psammead#331]
**Is your feature request related to a problem? Please describe.**
We need to evaluate how components which show text respond to different text strings/characters that are prevalent in the WS

**Describe the solution you'd like**
Add the `psammead-storybook-helpers package` to change the properties of each text-displaying component

**Describe alternatives you've considered**
Creating different stories for each case we want to evaluate.

**Testing notes**
N/A

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc
N/A

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by andrew-nowak** [comment]
Helper methods to do this were introduced in #378
