### ISSUE TITLE
Program Card styling bug on IE11 high contrast mode

### ISSUE THREAD

**Issue by OlgaLyubin** [BBC-archive/psammead#3310]
**Describe the bug**
High contrast mode on Windows 7 with IE11 - you don't see the left side of the border on the 'duration' section at the bottom of the card

<img width="1070" alt="Screenshot 2020-03-26 at 15 15 29" src="https://user-images.githubusercontent.com/17802955/77663248-c3cb6e00-6f74-11ea-94ed-d9eab0f92cb6.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to www.test.bbc.com/hausa?renderer_env=live
2. Scroll down to Radio schedule component (below top stories)
3. See error

**Expected behaviour**

**Desktop (please complete the following information):**

- OS: Windows 7
- Browser: Internet Explorer
- Version: 11

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Comment by PriyaKR** [comment]
LGTM.
