### ISSUE TITLE
Investigate theming

### ISSUE THREAD

**Issue by DenisHdz** [BBC-archive/psammead#332]
**Is your feature request related to a problem? Please describe.**
Investigate theming on the components.

**Describe the solution you'd like**
We would like to be able to modify the component typography and styles depending on the WS service.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [X] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by sareh** [comment]
It would be useful to break down all of Theming into smaller parts.

- Font face declarations can be added to `@bbc/psammead-styles` https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-styles/src/fonts.js
For example, you can add BBCNassim font faces for Persian here and export them to be used in the application. 

- Layout styles - switching to use right-to-left for Persian and other RTL languages: currently all of the components are agnostic to direction. By adding `dir="rtl"` attribute at the top level of the page-level container, this should be sufficient. This will change in future once we have components that have specific left-right behaviour, such as promos with images on the right and text on the left. 

- Typography definitions for Latin are included in `@bbc/gel-foundations`. This is where the font-size and line-height values are defined for all the GEL Types https://github.com/bbc/psammead/blob/latest/packages/utilities/gel-foundations/src/typography.js 

One proposal for generalising this, to work well for multiple scripts:

Make the Types (e.g. GEL Trafalgar) into functions, which takes in the parameter `script` and output the relevant styles. 

```
import { gelTrafalgar } from '@bbc/gel-foundations/typography';
import styled from 'styled-components';

const NewComponent = ({ script }) => {

  const StyledElement = styled.div`
    ${gelTrafalgar(script)};
  `;

  return (<StyledElement />);
};
```

This would mean that the UX team could define that New Component Y should use GEL Trafalgar and when we use this component and pass in a script value, the typography library would return the font sizes / line heights relating to that script. 

Usage: `<NewComponent script="latin" />`
The suggested change here would clearly be a breaking change to Typography. 

This is just one approach.  If we decide to use an internationalisation library that is configurable, it might be simpler to use that, for consistency.

**Comment by dr3** [comment]
I second what @sareh said, sounds great, My only concern would be how we handle typography and decoration/weight for different scripts? Perhaps we could expand on your example to account for how certain typography groups wouldn't allow for combinations? e.g. News shows captions in italic, but persian text shouldn't be italicised, or maybe a different weight level?

`gelTrafalgar({ script: 'en-GB', italicised: true, bold: true })`
```
font-size: 4.875rem;
line-height: 5.25rem;
font-style: italic;
weight: 700;
```
`gelTrafalgar({ script: 'fa', italicised: true, bold: true })`
```
font-size: 6.723rem;
line-height: 7.242rem;
weight: 500;
```
Note the second output has had a set of rules applied for persian text

Obs this would need coordination with UX to assess its possibility

**Comment by sareh** [comment]
I agree with you Drew that we should explore having config to define what is allowed for each script.

We should note that `script` and `language` are different. 
e.g. Persian uses Arabic script. News uses Latin script. 
We will need script-variants for our typography settings. e.g. Latin with diacritics. You can have multiple services using a particular script-variant.

**Comment by mgurgel** [comment]
Investigation complete, Issues raised, ADR to follow here https://github.com/bbc/psammead/issues/357
