### ISSUE TITLE
Investigate re-use of StoryPromo for Recommendations OJ

### ISSUE THREAD

**Issue by HarveyPeachey** [BBC-archive/psammead#3325]
**Is your feature request related to a problem? Please describe.**
As we've done with previous CPS onward journeys like CPS Related Content, [Top Stories](https://github.com/bbc/simorgh/issues/5700) and [Features and Analysis](https://github.com/bbc/simorgh/issues/5701), we've reused `psammead-story-promo` to create this component as they are visually similar. However, the Recommendations has specific accessibility requirements which Story promos might not adhere to:

<details>
  <summary><strong>Accesibility Acceptance Criteria (Click me to see)</strong></summary>

**Landmark**
Given I use a screen reader
When I navigate to the Recommendations section within the body copy of a STY page
Then a region landmark must be announced e.g. Region
And this must be announced with a label
And the label must be the same as the strong HTML element (e.g. component title)
And this should be inside the main landmark

**Skip link**

Given I use a keyboard
When I navigate to the Recommendations component
Then a skip link is visually displayed when it receives focus
And this should be the first content within the component
And the text should say "Skip [title of component] and continue reading"

Given I use a screenreader
When I activate the skip link
Then my focus moves to an end message
And this should be the last content within the component
And this is announced as "End of [title of component]"

Given I use a keyboard
When I navigate to the Recommendations component
Then a skip link is visually displayed when it receives focus
And the browser default focus outline styling is applied 

**Screenreader UX**

Given I am using a screenreader
When I navigate to the Recommendations component title
And this is within the body copy of a STY page
Then this should not have heading semantics
And it should be a strong HTML element

Given I am using a screenreader
When I navigate to the Recommendations component promos
And this component is within the body copy of a STY page
Then these should not contain heading semantics
</details>

**Describe the solution you'd like**
We need to investigate whether we can re-use story promo like we have before or create a new component to satisfy the accessibility requirements needed for the Recommendations OJ.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by HarveyPeachey** [comment]
## **Investigation of Re-using StoryPromo**

**Implementation Issues**

As we have a DRY approach for our CPS onward journey components I thought it would be as simple as creating a new container called CpsRecomendations in Simorgh and passing the down the fixture data that we get from Camino. 

However, the json data we get from the Camino endpoint won't work with the [StoryPromo container](https://github.com/bbc/simorgh/blob/latest/src/app/containers/StoryPromo/index.jsx) we have in Simorgh as there is prop validation in our DRY approach for [CpsOnwardJourney](https://github.com/bbc/simorgh/blob/f060742f06630b91654e3aa23076de6b6f1c0307/src/app/containers/CpsOnwardJourney/index.jsx#L97). This can be solved by either removing the prop validation for the content being in the story item format or transforming the data we get from Camino into the correct format:
<details>
  <summary><strong>Transformed Data Concept (Click me to see)</strong></summary>

```{
  "items": [
    {
      "assetUri": "/mundo/noticias-america-latina-51975331",
      "ampUri": "/mundo/amp/noticias-america-latina-51975331",
      "shortHeadline": "Argentina ordena cuarentena total obligatoria por el coronavirus",
      "imageHref": "http://c.files.bbci.co.uk/5A4D/production/_111371132_hi060727445.jpg"
    },
    {
      "assetUri": "/mundo/noticias-america-latina-52250630",
      "ampUri": "/mundo/amp/noticias-america-latina-52250630",
      "shortHeadline": "Por qué México se convirtió en el gran obstáculo del plan de la OPEP para aumentar el precio del petróleo",
      "imageHref": "http://c.files.bbci.co.uk/49F7/production/_111753981_03009521-c6ba-41e6-8328-65d0caf07635.jpg"
    },
    {
      "assetUri": "/mundo/noticias-52275464",
      "ampUri": "/mundo/amp/noticias-52275464",
      "shortHeadline": "El inédito y cuestionado plan de emergencia económica de Ecuador contra la crisis del coronavirus",
      "imageHref": "http://c.files.bbci.co.uk/34F5/production/_111775531_tv061050412.jpg"
    },
    {
      "assetUri": "/mundo/noticias-51796524",
      "ampUri": "/mundo/amp/noticias-51796524",
      "shortHeadline": "La guerra de precios entre Arabia Saudita y Rusia que hundió el valor del petróleo y las bolsas en medio de la crisis por el coronavirus",
      "imageHref": "http://c.files.bbci.co.uk/4627/production/_111195971_mediaitem111195968.jpg"
    }
  ]
}
```
```
[
  {
    "headlines": {
      "shortHeadline": "Argentina ordena cuarentena total obligatoria por el coronavirus"
    },
    "locators": {
      "assetUri": "/mundo/noticias-america-latina-51975331"
    },
    "indexImage": {
        "href": "http://c.files.bbci.co.uk/5A4D/production/_111371132_hi060727445.jpg",
    }
  },
  {
    "headlines": {
      "shortHeadline": "Por qué México se convirtió en el gran obstáculo del plan de la OPEP para aumentar el precio del petróleo"
    },
    "locators": {
      "assetUri": "/mundo/noticias-america-latina-52250630"
    },
    "indexImage": {
        "href": "http://c.files.bbci.co.uk/49F7/production/_111753981_03009521-c6ba-41e6-8328-65d0caf07635.jpg",
    }
  },
  {
    "headlines": {
      "shortHeadline": "El inédito y cuestionado plan de emergencia económica de Ecuador contra la crisis del coronavirus"
    },
    "locators": {
      "assetUri": "/mundo/noticias-52275464"
    },
    "indexImage": {
        "href": "http://c.files.bbci.co.uk/34F5/production/_111775531_tv061050412.jpg",
    }
  },
  {
    "headlines": {
      "shortHeadline": "La guerra de precios entre Arabia Saudita y Rusia que hundió el valor del petróleo y las bolsas en medio de la crisis por el coronavirus"
    },
    "locators": {
      "assetUri": "/mundo/noticias-51796524"
    },
    "indexImage": {
        "href": "http://c.files.bbci.co.uk/4627/production/_111195971_mediaitem111195968.jpg",
    }
  }
]
```
</details>

But when looking deeper into the prop validation for the [story image](https://github.com/bbc/simorgh/blob/f060742f06630b91654e3aa23076de6b6f1c0307/src/app/models/propTypes/storyItem/index.js#L4) and the [StoryPromo container](https://github.com/bbc/simorgh/blob/e17db8f1e75d773603017b270f10f90717002f23/src/app/containers/StoryPromo/index.jsx#L212) we need the `path` attribute however, we only get the `href` of the image from the Camino response. [Example of difference between path and href](https://github.com/bbc/simorgh/blob/f060742f06630b91654e3aa23076de6b6f1c0307/src/app/pages/StoryPage/featuresAnalysis.json#L78-L79) and where [`path`](https://github.com/bbc/simorgh/blob/e17db8f1e75d773603017b270f10f90717002f23/src/app/containers/StoryPromo/index.jsx#L42) is used. Also, the [StoryPromo container](https://github.com/bbc/simorgh/blob/latest/src/app/containers/StoryPromo/index.jsx) that is used in our CPS onward journeys has been created to use a specific format for the data that is passed through to it, so we wouldn't be able to reuse it.

The first option that removes the validation from the [CpsOnwardJourney Container](https://github.com/bbc/simorgh/blob/f060742f06630b91654e3aa23076de6b6f1c0307/src/app/containers/CpsOnwardJourney/index.jsx#L97) would be better as we do the same [validation](https://github.com/bbc/simorgh/blob/e17db8f1e75d773603017b270f10f90717002f23/src/app/containers/CpsFeaturesAnalysis/index.jsx#L41) in the specfic onward journey containers anyway. This would allow us to meet a lot of the accessibility requirements with no extra work.

In this case, we would have to create a CpsRecommendations container, that would use the different components from [`psammead-story-promo`](https://github.com/bbc/psammead/tree/latest/packages/components/psammead-story-promo) to build the elements of the Recommendations block which would be an Image, Headline and Link. Then we would have to remove the `content` prop validation from the [`CpsOnwardJourney`](https://github.com/bbc/simorgh/blob/e17db8f1e75d773603017b270f10f90717002f23/src/app/containers/CpsOnwardJourney/index.jsx#L97) container that is specific to a [storyItem](https://github.com/bbc/simorgh/blob/e17db8f1e75d773603017b270f10f90717002f23/src/app/models/propTypes/storyItem/index.js#L10) and use it to provide the accessibility requirements for a region landmark and a label.


**Accessibility Issues**
One of the main requirements of the Recommendations block is that the headline titles shouldn't use HTML headlines and use `<strong>`. However the StoryPromo component has been created to always use h3's for the headline title, so this would need a change in [`psammead-story-promo`](https://github.com/bbc/psammead/tree/latest/packages/components/psammead-story-promo) that would allow the option of rendering a headline with no `<h3>`. There is also no skip link functionality so this would need to be added to satisfy another accessibility requirement.

**Conclusion**

 - Remove `content` prop validation from [CpsOnwardJourney](https://github.com/bbc/simorgh/blob/f060742f06630b91654e3aa23076de6b6f1c0307/src/app/containers/CpsOnwardJourney/index.jsx#L97).
 - Create a CpsRecommendations container in Simorgh that is made up of an Image, Headline and Link from `psammead-story-promo`, which is passed into CpsOnwardJourney for Landmark and Label accessibility requirements.
- Make changes to `psammead-story-promo` to make `h3` optional in the headline where a `<strong>` will be used instead. A skip link needs to be implemented as well whether that be within `psammead-story-promo` or potentially a `psammead-skip-link` component that can just be imported into the Simorgh container. See [psammead-social-embed](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-social-embed/src/SkipLinkWrapper/index.jsx) for a skip link implementation.

**Comment by rhenshaw56** [comment]
This is really good @HarveyPeachey, I think it would be worth having a short swarm on this with the team to device a streamlined/incremental approach with smaller issues. Although I've got a question.

Why should we get rid of the [content prop validation](https://github.com/bbc/simorgh/blob/f060742f06630b91654e3aa23076de6b6f1c0307/src/app/containers/CpsOnwardJourney/index.jsx#L97), if we can transform an item in the camino data to look like a [promo story item](https://github.com/bbc/simorgh/blob/f060742f06630b91654e3aa23076de6b6f1c0307/src/app/models/propTypes/storyItem/index.js#L10) ?

**Comment by HarveyPeachey** [comment]
> This is really good @HarveyPeachey, I think it would be worth having a short swarm on this with the team to device a streamlined/incremental approach with smaller issues. Although I've got a question.
> 
> Why should we get rid of the [content prop validation](https://github.com/bbc/simorgh/blob/f060742f06630b91654e3aa23076de6b6f1c0307/src/app/containers/CpsOnwardJourney/index.jsx#L97), if we can transform an item in the camino data to look like a [promo story item](https://github.com/bbc/simorgh/blob/f060742f06630b91654e3aa23076de6b6f1c0307/src/app/models/propTypes/storyItem/index.js#L10) ?

Yeah, that's a good idea @rhenshaw56 I'll let people have a look at the investigation first and I'll organise a meeting next week. Although this is just showing what it would take to re-use story promo and further discussion would be needed to determine if making a new component would be faster/easier than this approach.

The reason we would need to replace the prop validation is that the [`indexImage`](https://github.com/bbc/simorgh/blob/f060742f06630b91654e3aa23076de6b6f1c0307/src/app/models/propTypes/storyItem/index.js#L26) contained in the promo story item, has to contain a [`path`](https://github.com/bbc/simorgh/blob/f060742f06630b91654e3aa23076de6b6f1c0307/src/app/models/propTypes/storyItem/index.js#L4) key, but we're only provided with a `href` from Camino. Technically we could rename the key from `href` to `path` in the data transformation to satisfy the validation, but they are fundamentally different and would be confusing for maintainabilty and consistency.

We also do validation in the onward journey parent containers themselves, so we don't really need to do another prop validation check again I think https://github.com/bbc/simorgh/blob/e17db8f1e75d773603017b270f10f90717002f23/src/app/containers/CpsFeaturesAnalysis/index.jsx#L41

**Comment by HarveyPeachey** [comment]
@rhenshaw56 I've also just had a thought if it might be easier if we can get the team who manage the Camino endpoint to add the path parameter to their response. That would save us having to remove the prop validation and then we can also make use of the ichef responsive image logic we have in Simorgh. Question is, do we want to be doing data transformation within the container.

**Comment by chris-hinds** [comment]
> @rhenshaw56 I've also just had a thought if it might be easier if we can get the team who manage the Camino endpoint to add the path parameter to their response. That would save us having to remove the prop validation and then we can also make use of the ichef responsive image logic we have in Simorgh. Question is, do we want to be doing data transformation within the container.

@HarveyPeachey is the team behind the camino API can do this in a reasonable time then great. if not it would be a fairly small piece of work for us to extract the path from the href value and then create then transform the data in to what is required by the story-promo.

**Comment by andrewscfc** [comment]
Good write-up @HarveyPeachey, a few questions on an approach I broadly agree with. You may want to go over this on a call with people interested to argue the points then run a swarm as @rhenshaw56 says above.

> The first option that removes the validation from the [CpsOnwardJourney Container](https://github.com/bbc/simorgh/blob/f060742f06630b91654e3aa23076de6b6f1c0307/src/app/containers/CpsOnwardJourney/index.jsx#L97) would be better 

Agree with this point, `CpsOnwardJourney` is a higher order component and doesn't need to care about the content it is wrapping a such.

> In this case, we would have to create a CpsRecommendations container, that would use the different components from [`psammead-story-promo`](https://github.com/bbc/psammead/tree/latest/packages/components/psammead-story-promo) to build the elements of the Recommendations block which would be an Image, Headline and Link.

When you say _use_, do you mean duplicate or extract out into shareable components? I'd imagine copying and pasting would be preferable in this case as you need to vary these elements based on the accessibility requirements.

> Make changes to `psammead-story-promo` to make `h3` optional in the headline where a `<strong>` will be used instead

This section _seems_ to contradict the part earlier where you were 'using' _the components from_ [`psammead-story-promo`](https://github.com/bbc/psammead/tree/latest/packages/components/psammead-story-promo) rather than using `psammead-story-promo`_itself_; why would `psammead-story-promo` need to change if you have taken what you need from the component and duplicated?

**Comment by HarveyPeachey** [comment]
@andrewscfc 
> > In this case, we would have to create a CpsRecommendations container, that would use the different components from [`psammead-story-promo`](https://github.com/bbc/psammead/tree/latest/packages/components/psammead-story-promo) to build the elements of the Recommendations block which would be an Image, Headline and Link.
> 
> When you say _use_, do you mean duplicate or extract out into shareable components? I'd imagine copying and pasting would be preferable in this case as you need to vary these elements based on the accessibility requirements.
> 
Sorry it was a little confusing trying to explain this. [`psammead-story-promo`](https://github.com/bbc/psammead/blob/db25f96d360f03b550ab27c0617d633ae9a15ae9/packages/components/psammead-story-promo/src/index.jsx#L125) itself has exported components within itself which are [`headline`](https://github.com/bbc/psammead/blob/db25f96d360f03b550ab27c0617d633ae9a15ae9/packages/components/psammead-story-promo/src/index.jsx#L125), [`link`](https://github.com/bbc/psammead/blob/db25f96d360f03b550ab27c0617d633ae9a15ae9/packages/components/psammead-story-promo/src/index.jsx#L197), `summary` and `index-alsos`. So a quick cobble of how recommendations would look with the amalgamated components:

<details>
  <summary><strong>Code</strong></summary>

```js
import StoryPromo, { Headline, Link } from '@bbc/psammead-story-promo';
import { ServiceContext } from '#contexts/ServiceContext';
import CpsOnwardJourney from '../CpsOnwardJourney';

const CpsRecommendations = ({
  headline,
  url,
  imgHref,
}) => {
  const {
    script,
    service,
    translations,
  } = useContext(ServiceContext);


  const Info = (
        <Headline
          script={script}
          service={service}
          promoHasImage=true
        >
          <Link href={url}>{headline}</Link>
        </Headline>
  );

  const Image = <img src={imgHref}>;

  const Content = <StoryPromo image={Image} info={Info} />;

  return (
  <CpsOnwardJourney
    labelId="recommendations-heading"
    title="Recommendations"
    content={Content}
  />
  );
};

export default CpsRecommendations;
```
</details>

But as @hindsc52 pointed out we can just extract the `path` from the `href` value, transform it into the storypromo prop structure and then just re-use the [story-promo container](https://github.com/bbc/simorgh/blob/latest/src/app/containers/StoryPromo/index.jsx) we have in Simorgh. This would give us the extra flexibility for live labels or other story promo features that can be used for this OJ in the future.

> > Make changes to `psammead-story-promo` to make `h3` optional in the headline where a `<strong>` will be used instead
> 
> This section _seems_ to contradict the part earlier where you were 'using' _the components from_ [`psammead-story-promo`](https://github.com/bbc/psammead/tree/latest/packages/components/psammead-story-promo) rather than using `psammead-story-promo`_itself_; why would `psammead-story-promo` need to change if you have taken what you need from the component and duplicated?

The reason [`psammead-story-promo`](https://github.com/bbc/psammead/tree/latest/packages/components/psammead-story-promo) needs a change is because the headline is [hard coded](https://github.com/bbc/psammead/blob/db25f96d360f03b550ab27c0617d633ae9a15ae9/packages/components/psammead-story-promo/src/index.jsx#L125) as a `<h3>` element which we don't want, we want the headline to just be contained in a `<strong>` element.

**Comment by andrewscfc** [comment]
@HarveyPeachey 

> [`psammead-story-promo`](https://github.com/bbc/psammead/blob/db25f96d360f03b550ab27c0617d633ae9a15ae9/packages/components/psammead-story-promo/src/index.jsx#L125) itself has exported components within itself which are [`headline`](https://github.com/bbc/psammead/blob/db25f96d360f03b550ab27c0617d633ae9a15ae9/packages/components/psammead-story-promo/src/index.jsx#L125), [`link`](https://github.com/bbc/psammead/blob/db25f96d360f03b550ab27c0617d633ae9a15ae9/packages/components/psammead-story-promo/src/index.jsx#L197), `summary` and `index-alsos`. 

Ah I missed this, are these exported for testing purposes only or are they used elsewhere? I would imagine if they are used outside of the component they should be 'promoted' to first class psammead components so they can easily be found and reused?

> The reason [`psammead-story-promo`](https://github.com/bbc/psammead/tree/latest/packages/components/psammead-story-promo) needs a change is because the headline is [hard coded](https://github.com/bbc/psammead/blob/db25f96d360f03b550ab27c0617d633ae9a15ae9/packages/components/psammead-story-promo/src/index.jsx#L125) as a `<h3>` element which we don't want, we want the headline to just be contained in a `<strong>` element.

That makes total sense now as you have clarified you intend to import the components 🙂 

So your approach sounds pretty good other than perhaps considering 'promoting' the components you are using for discoverability. Not sure what other's thoughts are on this?

**Comment by HarveyPeachey** [comment]
Closing and completing the investigation off the back of the solution discussion with members of the pod, I've captured the solution into 3 different issues:

https://github.com/bbc/simorgh/issues/6266
https://github.com/bbc/psammead/issues/3406
https://github.com/bbc/simorgh/issues/6267
