### ISSUE TITLE
Copyright component incorrectly placed into Figure

### ISSUE THREAD

**Issue by andrew-nowak** [BBC-archive/psammead#333]
**Describe the bug**
When creating a Figure component containing an Image and a Copyright components, as following the examples in the Figure and Copyright READMEs, the Copyright component is placed at the bottom right of the `<body/>`.

**To Reproduce**
Create a Figure component similar to the following:

```js
<Figure>
  <ImagePlaceholder ratio={imageRatio}>
    <Image alt={imageAlt} src={imageSrc} width={imageWidth} />
  </ImagePlaceholder>
  <Caption>Caption</Caption>
  <Copyright>Copyright</Copyright>
</Figure>
```

The Figure story in the Storybook when building this branch has such an example:
[`copyright-badly-placed-bug`](/bbc/psammead/tree/copyright-badly-placed-bug)

observe that the Copyright is visually located at the bottom right of the window.

**Expected behavior**
The Copyright component is visually located at the bottom right of the Image.

**Screenshots**
<img width="1674" alt="screen shot 2019-03-07 at 15 11 20" src="https://user-images.githubusercontent.com/10963046/53967016-53914680-40ec-11e9-9fb2-23ca63275d32.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser Firefox
- Version 65

**Smartphone (please complete the following information):**
untested

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/bbc/psammead/labels/bug)

**Comment by sareh** [comment]
When using the Copyright in addition to a placeholder, you can use it like this:
```
<Figure>
  <ImagePlaceholder ratio={imageRatio}>
    <Image alt={imageAlt} src={imageSrc} width={imageWidth} />
    <Copyright>Copyright</Copyright>
  </ImagePlaceholder>
  <Caption>Caption</Caption>
</Figure>
```

**Comment by andrew-nowak** [comment]
👍 I'll update the READMEs to match
