### ISSUE TITLE
Update Visually Hidden Text to support more use cases

### ISSUE THREAD

**Issue by simonsinclair** [BBC-archive/psammead#3361]
**Is your feature request related to a problem? Please describe.**

This component returns a fixed element with the visually hidden styles applied. We have found a need to apply visually hidden styles to other wrapping elements, and also control when and where these styles are applied.

E.G. An anchor that becomes visible when it's focussed.

```js
const SkipLink = styled.a`
  &:not(:focus):not(:active) {
    // Styles that keep the link hidden when it's not in focus or active.
  }
`;
```

**Describe the solution you'd like**

Flexibility could be achieved, while maintaining backwards compatibility, by adding an export for the style string. E.G.

```js
import { visuallyHiddenStyle } from '@bbc/psammead-visually-hidden-text';

const SkipLink = styled.a`
  &:not(:focus):not(:active) {
    ${visuallyHiddenStyle}
  }
`;
```

**Describe alternatives you've considered**
n/a

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
None.

**Comment by sareh** [comment]
@simonsinclair Is there a reason you cannot do the following in your component:

```
const VisuallyHiddenWhenUnfocussed = styled(VisuallyHiddenText)`
  &:not(:focus):not(:active) {
    ${visuallyHiddenStyle}
  }
`;
```

```
..... 
<VisuallyHiddenWhenUnfocussed as="a" />
  Link text here
</VisuallyHiddenWhenUnfocussed>
```

**Comment by simonsinclair** [comment]
> @simonsinclair Is there a reason you cannot do the following in your component:
> 
> ```
> const VisuallyHiddenWhenUnfocussed = styled(VisuallyHiddenText)`
>   &:not(:focus):not(:active) {
>     ${visuallyHiddenStyle}
>   }
> `;
> ```
> 
> ```
> ..... 
> <VisuallyHiddenWhenUnfocussed as="a" />
>   Link text here
> </VisuallyHiddenWhenUnfocussed>
> ```

Thanks for the comment, @Sareh. Where is `${visuallyHiddenStyle}` coming from?

Leaning on your example, we could treat the visually hidden styles as the default and then 'undo' them, but wouldn't that involve more code than necessary? E.G.

```js
const VisuallyHiddenUntilFocussed = styled(VisuallyHiddenText)`
  &:focus,
  &:active {
    // Override all the styles applied by @bbc/psammead-visually-hidden-text to make it display.
  }
`;
```

This is what [psammead-brand](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-brand/src/SkipLink/index.jsx#L32-L35) is doing, but without the help of `psammead-visually-hidden-text`.

P.S. I didn't know about the [as=""](https://styled-components.com/docs/api#as-polymorphic-prop) prop. That's cool. 👍
