### ISSUE TITLE
pashto local not working correctly

### ISSUE THREAD

**Issue by byteab** [BBC-archive/psammead#3399]
when I use "ps" locale some part of the text is pashto and some part english

for example => "وراندی a month"

**Comment by sareh** [comment]
@EhsanSarshar Thank you for raising this bug. We currently have only added the fields that we are using in our pages - [see those here in our ps locale file](https://github.com/bbc/psammead/blob/7366856a111d008aaaf78dd2760a000ddf3207a9/packages/utilities/psammead-locales/moment/ps.js#L10-L20). If you can suggest translations for those fields we're not using yet, please do submit them. We have some contributing guidelines here: [CONTRIBUTING.md](https://github.com/bbc/psammead/blob/latest/CONTRIBUTING.md)
