### ISSUE TITLE
Eslint import/no-extraneous-dependencies rule

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#340]
**Describe the bug**
We originally had the eslint rule `'import/no-extraneous-dependencies': 'off'` which allowed us to have npm dependancies in both a package, and in the top level, while not having eslint complain. 

**Expected behavior**
Turns out this never worked... If you go on latest and log `paths` on line 71 of  `node_modules/eslint-plugin-import/lib/rules/no-extraneous-dependencies.js` it logs 
```
[ '/Users/mcmild07/dev/psammead/package.json',
  '/Users/mcmild07/package.json' ]
```
instead of what we expected;
```
[ '/Users/mcmild07/dev/psammead/packages/components/psammead-image/package.json',
  '/Users/mcmild07/dev/psammead/package.json' ]
```

**Fix**
Unknown if its possible, may need to do some investigations

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/bbc/psammead/labels/bug)

**Comment by jamesbhobbs** [comment]
@dr3 this works in bbc/simorgh, I believe it may require the paths specified, which is also best practice as you shouldn't want this everywhere.
