### ISSUE TITLE
Allow StoryPromo headline to optionally render without a h3 tag

### ISSUE THREAD

**Issue by HarveyPeachey** [BBC-archive/psammead#3406]
**Is your feature request related to a problem? Please describe.**
Following on from investigation https://github.com/bbc/psammead/issues/3325 to implement the Recommendations component into Story pages in Simorgh, we decided to re-use story promos to create the container, however we have acceptance criteria for the headlines in recommendations to not use any HTML heading tags. Currently, `headline` is hardcoded to use [h3's](https://github.com/bbc/psammead/blob/3db1faa1f4836d2a7a87a3b1437659d11032fe75/packages/components/psammead-story-promo/src/index.jsx#L125).

**Describe the solution you'd like**
Allow the option of rendering the headline in a `<div>`, whilst keeping h3 as the default HTML element to stop this being a breaking change.

Use the [as prop](https://styled-components.com/docs/api#as-polymorphic-prop).

Limit elements rendered to a div, but allow different level of headings. Prevent images being rendered.

**Describe alternatives you've considered**

**Testing notes**
Add snapshot tests demonstrating the function.

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by ghost** [comment]
What is meant by `Limit elements rendered to a div`? Does it mean we have proptype checks?
