### ISSUE TITLE
Extend support for scripts in gel-foundation

### ISSUE THREAD

**Issue by mgurgel** [BBC-archive/psammead#342]
**Is your feature request related to a problem? Please describe.**
typography.js definitions do not comprise World Service scripts

**Describe the solution you'd like**
Make the types into functions that take the script as a parameter

**Describe alternatives you've considered**
We have considered having an all-knowing theme context object that would be called on by components, but that was a terrible idea.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [ ] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by alex-magana** [comment]
The following are the scripts we currently support as per
https://github.com/bbc/grandstand/tree/master/lib/settings/scripts

* arabic
* bengali
* burmese
* chinese
* cyrillic
* hindi
* japanese
* latin
* sinhala
* tamil
* thai

To cater for service specific typography settings within a script group
e.g Mundo in the latin script group, we may utilize ISO 639-1 language codes
to map a service to the repsective typography settings.
The table below is a service - script mapping of typography settings defined in WS - Font Stacks & Styles Off Forge v1.0

Service      | Script
-----------  | -------------
|Mundo        | latin-es |
|Arabic        | arabic |
|Burmese        | burmese |
|Hindi       | hindi    |
|Nepali      | hindi    |
|Bengali     | hindi    |
|UKChina     | chinese  |
|Zhongwen    | chinese  |
|Korean      | chinese  |
|Japanese    | chinese  |
|Thai        | chinese  |
|Sinhala        | sinhala |
|Tamil        | tamil |

NOTE
Script Changes in WS - Font Stacks & Styles Off Forge v1.0 vs WS LIVE  are as follows.

Service        | WS - Font Stacks & Styles Off Forge v1.0 | WS LIVE
-----------  | ------------- | -------------
|Bengali | hindi | bengali  |
|Japanese | chinese | japanese |
|Thai | chinese | latin |

The script setting for a service is to be passed to a psammead component as
a prop.
The script setting can be passed to the cotnainer which consumes the Context API.
The language codes are available in the content-api response for reference.
Below please find a link to the ISO list of languages for reference.
http://www.loc.gov/standards/iso639-2/php/code_list.php
The service-script mapping can be accessed in the iSite grandstand-typography content library below.

**Comment by alex-magana** [comment]
As discussed, I'll revert the file renaming changes I made to match the script configuration naming in [WS - Font Stacks & Styles Off Forge v1.0](https://docs.google.com/spreadsheets/d/1WMY-rlSbekhB4pV3ojMuYoWDC71Qs93CB2wTfDwAsJg/edit#gid=2081192161
)
