### ISSUE TITLE
Add `#F6F6F6` to @bbc/psammead-styles

### ISSUE THREAD

**Issue by Bopchy** [BBC-archive/psammead#3458]
**Is your feature request related to a problem? Please describe.**
Add the colour `#F6F6F6` to `packages/utilities/psammead-styles/src/colours.js` so that it can be used by the AMP ads component (https://github.com/bbc/simorgh/issues/6447). It should be called 'Lunar Light'.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Having the colour defined in Simorgh.

**Testing notes**
We should see this in storybook.

Dev insight: Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
Reach out to UX for an appropriate name for the colour.

**Comment by sareh** [comment]
We should ask UX what this colour should be named as.
