### ISSUE TITLE
Add GEL Group A breakpoint to gel-foundations

### ISSUE THREAD

**Issue by mgurgel** [BBC-archive/psammead#348]
**Is your feature request related to a problem? Please describe.**
gel-foundations does not provide a constant for the Group A breakpoint

**Describe the solution you'd like**
Add a breakpoint constant for 0 - 319 pixels in Group A as specified here http://www.bbc.co.uk/gel/guidelines/typography. There should be constants for the GEL_GROUP_A_MIN_WIDTH and GEL_GROUP_A_MAX_WIDTH boundaries of GROUP A and a media query constant that comprises both (name TBD)

**Describe alternatives you've considered**
No alternatives

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [ ] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by dr3** [comment]
@DenisBBC Can we please ensure that a tester leaves a comment on PRs so we have a record of them having seen it prior to merging
