### ISSUE TITLE
Investigate: A new solution for media durations for screen readers is required

### ISSUE THREAD

**Issue by greenc05** [BBC-archive/psammead#3538]
**Describe the bug**
We visually display media durations with a colon delimiter separating the units of time e.g. 1:00 - This is 1 minute and zero seconds. Screen readers infer their own semantics to this format. For example, VoiceOver Mac, Talkback and Jaws screen readers announce ‘1:00’ as ‘1 o’clock’ indicating time rather than duration. 

Our current live solution for screen readers is to use a comma instead of a colon as the delimiter between the units of time. This is still less than optimal as there is no context for the units of time though this stops screen readers recognising this as a time format. For example ‘1,00’ is no longer announced as ‘1 o’clock’ but instead ‘1 zero zero’ or ‘1 0 0’. 

However, when we looked into this solution we did not consider all the languages we support. On Russian with Voiceover Mac and iOS, this solution results in announcements dropping any last double zeros. For example ‘1,00’ is announced as ‘1’. Also on Russian some combinations of numbers using a comma delimiter are announced as fractions. For example ‘0,09’ is announced as ‘0 whole 9 of 100th’. I'm sure that Russian isn't the only service with issues.

We need a new solution for media durations for screen readers. This should start with an investigation into moment durations to see if we can output durations in words across the languages that we support, so we can output something like this: 'Video, How vancines work, duration 1 minute 2 seconds'

**Comment by greenc05** [comment]
Worth looking at the following as part of this investgation work:

- https://github.com/bbc/simorgh/pull/2648
- https://github.com/bbc/simorgh/pull/2640
- https://github.com/bbc/simorgh/issues/2085

**Comment by aeroplanejane** [comment]
Linked to WSMEDIA-250 and Radio Schedule Improvements tickets

**Comment by aeroplanejane** [comment]
From what I understand we won't be supporting Moment in the future so we may need to solve this with an alternative @greenc05

**Comment by greenc05** [comment]
Thanks @aeroplanejane I don't mind what the techincal solution is for the issue

**Comment by pharingee** [comment]
We encountered some issues with this a year ago: https://github.com/bbc/simorgh/issues/2996

**Comment by greenc05** [comment]
See https://github.com/bbc/psammead/issues/4048

**Comment by pharingee** [comment]
Closing this after discussions on #4048
