### ISSUE TITLE
Add ADR about choice of Styled Components

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#356]
**Is your feature request related to a problem? Please describe.**
We wrote up an ADR about the reasoning for choosing Styled Components for our front-end components. 
We should add this to Psammead, for greater visibility. 

**Describe the solution you'd like**
Add an ADR to this repository. 

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: N/A - the ADR should be readable. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by jamesbhobbs** [comment]
I don't see a need to explain the choice of the most popular library. Why we chose CSS-in-JS is because we knew we were building a SPA and I mandated tightly scoped css, after that it was a no-brainer.
