### ISSUE TITLE
Investigation: importing non-Reith fonts

### ISSUE THREAD

**Issue by mgurgel** [BBC-archive/psammead#359]
**Describe the solution you'd like**

WS needs to import and reference non-latin fonts in CSS. This investigation should come up with:
- A list of fonts that will be used by each service [HERE](https://docs.google.com/spreadsheets/d/1WMY-rlSbekhB4pV3ojMuYoWDC71Qs93CB2wTfDwAsJg/edit#gid=1458344872)
- Where the font files will be stored (if different from their current location) - must be compliant with licensing restrictions
- Where in Psammead will the font-face declarations live 
- How will components pull in the appropriate font for the service
- Possible failure scenarios
- A PR with an example component implementation and a Storybook entry with the results of the investigation

**Comment by dr3** [comment]
Closing this as done for now following https://github.com/bbc/psammead/pull/373
