### ISSUE TITLE
Definition of done - Psammead components

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#36]
**Is your feature request related to a problem? Please describe.**
We are about to move components into the Psammead library, but there is no explicit 'definition of done' for the component that is written down. e.g. which files are required, which tests are required, etc. 

We should add this, so that when we review new PRs to add components, we have clarity across Dev and Test as to what is needed. 

**Describe the solution you'd like**
We should discuss this in this issue and then ensure that the write-up is in a `CONTRIBUTING.md` file.

**Describe alternatives you've considered**
N/A

**Testing notes**
N/A

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by sareh** [comment]
**Definition of Done**
- Has this file structure 
```
├── README.md
├── __snapshots__
│   └── index.test.jsx.snap
├── eslintrc.js
├── index.jsx
├── index.stories.jsx
├── index.test.jsx
└── package.json
```
So there should be unit tests, stories and a package.json. Snapshot tests directory is optional.

The `package.json` is namespaced with `@bbc/psammead-*`  e.g. `@bbc/psammead-headings`. 

The author of the package 
```
  "author": {
    "name": "BBC Psammead Maintainers",
    "email": "PsammeadMaintainers@bbc.co.uk"
  },
```
Repository info
```
  "repository": {
    "type": "git",
    "url": "https://github.com/BBC-News/psammead/tree/latest/packages/Headings"
  },
```

**Tests**
When you run `npm run test` all unit tests should pass and there should be 100% test coverage of the component. No JS or CSS lint errors should be listed. 

**Storybook**
The Readme file should link to Storybook. This other issue about Storybook is a prerequisite: https://github.com/BBC-News/psammead/issues/37

**Comment by ChrisBAshton** [comment]
Two questions:

## eslintrc.js
**EDIT - have discussed with Drew and we agree no eslintrc.js is needed.**
 
What are the benefits of having a separate eslintrc.js for each component? We have one at the root. If a component needs to override some rules, it can do so with magic comments.

Advantages of having just one at the root:

* one lint config to rule them all - consistency between components
* less configuration & setup required for each component

Disadvantages:

* If we make a lint change at the root, we may have to update all of the components

## Authorship

After discussing on Slack, we've decided to create a maintainers email address for this part of the package.json:

```json
  "author": {
    "name": "BBC Articles Team",
    "email": "PsammeadMaintainers@bbc.co.uk"
  },
```

**Comment by sareh** [comment]
Testing `npm run test` should all the unit tests. That should be sufficient.

**Comment by ChrisBAshton** [comment]
This has come up once or twice already, so just to confirm - should we _not_ have a Code_Of_Conduct.md on a per-component basis?

I think having one at the root is sufficient - it's a monorepo after all, so all issues and PRs end up in the same place. It will only get confusing if we have component-level agreements in place - even if those agreements merely reference the one at the root.

**Comment by sareh** [comment]
Yes, agreed - there should only be a single `CODE_OF_CONDUCT.md` in the repository, at the top level.  It would make sense to link to it in the `README.md` of the individual package.

**Comment by ChrisBAshton** [comment]
Great 👍 this should be ready for someone to pick up and update Contributing.md now

**Comment by jackpopp** [comment]
Hey just want to check about:

```
  "author": {
    "name": "BBC Articles Team",
    "email": "PsammeadMaintainers@bbc.co.uk"
  },
```

Do you mean add this to root package.json or to components specifically added by articles team? It kinda of feels like it is implying that its solely owned and consumed by Articles team with that name.

**Comment by sareh** [comment]
@jackpopp Sorry, You're right. It should be updated to be `"name": "BBC Psammead Maintainers",`

**Comment by jackpopp** [comment]
👍

**Comment by dr3** [comment]
Oh nooos, We forgot a changelog file 😱

**Comment by sareh** [comment]
Changelog setup:
`CHANGELOG.md` in each package.
```

<h1 align="center">PackageName Changelog</h1>

| Version | Description |
|---------|-------------|
| 0.1.0 | [PR#49](https://github.com/BBC-News/psammead/pull/49) Initial creation of package |
```

**Comment by radiocontrolled** [comment]
In the contribution guide, I think we should spell out what we suggest for a component readme: 

e.g. as has been done in Simorgh, https://github.com/BBC-News/simorgh/issues/912

```
- ## Description (high-level summary that will be accessible to product/UX/Test, plus link to Storybook, explain the different cases)
- ## When to use this component (including where it is currently used)
- ## When to not use this component (if this is not known, can leave the section empty)
- ## Accessibility notes (ensuring they make sense to non-technical audiences)
- ## Roadmap (what we have planned for this component)
- ## Additional notes (link to any relevant ADRs)
```
