### ISSUE TITLE
SitewideLinks Component doesnt expand to full group 5 width

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#361]
**Describe the bug**
SitewideLinks Component doesn't expand to full group 5 width

**To Reproduce**

1. Go to any news article
2. See error

**Expected behavior**
It expands to the full 1280px

**Screenshots**
![image](https://user-images.githubusercontent.com/11341355/54522487-45052380-4965-11e9-95b8-9715f0330ff4.png)

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/bbc/psammead/labels/bug)

**Comment by sareh** [comment]
With `em`s: 
<img width="1440" alt="Screen Shot 2019-03-18 at 10 19 14" src="https://user-images.githubusercontent.com/3028997/54523471-84cd0a80-4967-11e9-90ec-a93d4a472a28.png">

With `rem`s:
<img width="1440" alt="Screen Shot 2019-03-18 at 10 19 34" src="https://user-images.githubusercontent.com/3028997/54523469-84347400-4967-11e9-9d9f-4611d46e7ff8.png">
