### ISSUE TITLE
media-message component -  Remove strong elements border bottom and add to Psammead storybook

### ISSUE THREAD

**Issue by greenc05** [BBC-archive/psammead#3624]
**Describe the bug**
- The strong element has an unnecessary border bottom in the media messsage component
- This component is not in Psammead storybook

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/ukrainian/bbc_ukrainian_tv/tv/w172xcsw46bvqpv
2. Change colour preferences in Firefox
3. You will see an extra border bottom on the strong element

**Expected behaviour**
- You should only see a border around the container (the grey box)
- You should see this component in Psammead storybook

**Screenshots**
<img width="799" alt="Screenshot 2020-07-20 at 17 06 13" src="https://user-images.githubusercontent.com/1061401/87960308-05e06880-caac-11ea-9b65-236a730f1c95.png">

**Testing notes**

- [ ] Test firefox with colour preferences changed and a custom mode in windows high contrast mode

**Comment by RichardPK** [comment]
PR implementing the change in Simorgh https://github.com/bbc/simorgh/pull/7540

**Comment by LilyL0u** [comment]
![Image 21-08-2020 at 16 52](https://user-images.githubusercontent.com/54575620/90910137-c66cab00-e3ce-11ea-84ed-1b82d03498cd.jpg)

Fixed. Beautiful.
