### ISSUE TITLE
Investigate displaying multiple language configurations per component in Storybook

### ISSUE THREAD

**Issue by mgurgel** [BBC-archive/psammead#370]
We need a way to toggle different language configurations per component in Storybook, so that UX, devs and testers can quickly and easily see how components behave under different languages. 

**Describe the solution you'd like**
_As a user_
_I want to select a language in Storybook_
_Then seen components display content in that language_

* Must be in Storybook
* Each component must have a pre-defined set of prop values for each language, that gets applied to the component upon selection. 
* The pre-defined prop values above should be easy to create, edit and duplicate. Preferably in stored JSON.
* Consider performing the toggle both at component level (toggle a language on a single component) or Storybook level (toggle a language across all components). Which is easier to implement and which provides the best user experience?
* Provide an example implementation on an existing using one LTR and one RTL language.

**Comment by andrew-nowak** [comment]
Method implemented in #378 
First usage in #377

**Comment by dr3** [comment]
Closing as done in https://github.com/bbc/psammead/pull/378
