### ISSUE TITLE
Image caption not read out on VoiceOver without explicit swipe

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#374]
**Describe the bug**
Using voiceover on IOS navigate to an image caption and hear it read ""image caption"" then stop. I would expect this to continue to read the actual content of the caption.

**To Reproduce**

1. Any iOS device, activate VoiceOver
2. Navigate to an article with an image & imagecaption
3. Navigate to the imagecaption
4. VoiceOver reads "image caption", but an additional swipe needed to read its contents

**Expected behavior**
VoiceOver should read "image caption" followed immediately by the actual caption.

**Additional context**
Originally raised by @pjlee11.

Worth checking with @greenc05 to confirm whether or not this is expected.

If it is a genuine issue, it's probably to do with how we mark up the imagecaption (e.g. is there an additional `<span>`?).

- [x] Initially labelled with ["bug"](https://github.com/bbc/psammead/labels/bug)

**Comment by greenc05** [comment]
@ChrisBAshton this isn't great UX but unfortunately we aren't in a position to do anything about this if we are to meet the visual design and Optimo requirements...

**Comment by jamesbhobbs** [comment]
Closing subsequent to Catharines comment
