### ISSUE TITLE
[1/2] Replace Styled Components with Emotion

### ISSUE THREAD

**Issue by simonsinclair** [BBC-archive/psammead#3764]
### Is your feature request related to a problem? Please describe.

In order to complete the migration to Emotion (https://github.com/bbc/psammead/issues/3763), Styled Components packages must be replaced with Emotion packages. This includes those used by the Jest and transpilation environments.

### Describe the solution you'd like

1. Implement Admin-only merge to freeze changes to Psammead.
2. Prepare Psammead environment.

### Describe alternatives you've considered
N/A.

### Testing notes
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- ~~[ ] This feature is expected to need manual testing.~~

### Additional context
None.

**Comment by RichardPK** [comment]
Psammead party of this work is done - closing the issue
