### ISSUE TITLE
Visually Hidden Text changelog is borked

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#380]
**Describe the bug**
Table formatting broken.

**To Reproduce**
Visit https://github.com/bbc/psammead/blob/latest/packages/components/psammead-visually-hidden-text/CHANGELOG.md

**Expected behavior**
Normal table rendered.

**Screenshots**
<img width="1042" alt="Screen Shot 2019-03-22 at 12 23 39" src="https://user-images.githubusercontent.com/5111927/54822637-5750cb80-4c9d-11e9-9711-80455941d77d.png">

**Additional context**
N/a

- [x] Initially labelled with ["bug"](https://github.com/bbc/psammead/labels/bug)

**Comment by jamesbhobbs** [comment]
Fixed
