### ISSUE TITLE
Update Psammead caption UX

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#382]
**Is your feature request related to a problem? Please describe.**
The caption has padding which it shouldnt

Current
![image](https://user-images.githubusercontent.com/11341355/54837526-888dc380-4cbe-11e9-8189-7ab7cb34638e.png)

Zeplin
![image](https://user-images.githubusercontent.com/11341355/54837550-95121c00-4cbe-11e9-9c1d-77e38d985ea5.png)

~~It also uses 'pseudo italics' (rather than the official Reith italic font).~~ EDIT: no it doesn't.

**Describe the solution you'd like**
Remove the left-padding ~~and use the Reith italic font~~.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Update snapshots. Test in Storybook.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
We should also use the "real" Reith italic font for this. Can fix as part of this PR.
