### ISSUE TITLE
createGlobalStyle example link broken in README

### ISSUE THREAD

**Issue by cseas** [BBC-archive/psammead#3907]
The link for "manage global styles as has been done in Simorgh." in the [README](https://github.com/bbc/psammead/blob/latest/packages/README.md) directs to the below file which doesn't exist anymore:
https://github.com/bbc/simorgh/blob/latest/src/app/lib/globalStyles.js

The closest thing I could find in the target repository is this file:
https://github.com/bbc/simorgh/blob/latest/src/app/Layouts/defaultPageWrapper.jsx

But even in that file it's not clear how to add the BBC fonts to global styles. Can someone please provide an example or update the link to point to the correct file where the example usage is?

**Comment by karinathomasbbc** [comment]
@cseas thanks for raising this issue.

Here's an example of how you could use BBC Fonts with GlobalStyles:

```
import { F_REITH_SANS_REGULAR, F_REITH_SANS_ITALIC } from '@bbc/psammead-styles/fonts';

<GlobalStyles fonts={[F_REITH_SANS_REGULAR, F_REITH_SANS_ITALIC]} />
```

See also https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-styles/README.md#global-styles

**Comment by cseas** [comment]
Thank you for the response! The above solution doesn't seem to work.
I tried to create a minimal example:

```tsx
import { latin } from "@bbc/gel-foundations/scripts";
import {
  GEL_FF_REITH_SERIF,
  getElephant,
} from "@bbc/gel-foundations/typography";
import { F_REITH_SERIF_REGULAR } from "@bbc/psammead-styles/fonts";
import GlobalStyles from "@bbc/psammead-styles/global-styles";
import React from "react";
import styled from "styled-components";

export function App() {
  return (
    <>
      <GlobalStyles fonts={[F_REITH_SERIF_REGULAR]} />
      <ElephantText>Could a computer</ElephantText>
    </>
  );
}

const ElephantText = styled.h1`
  font-family: ${GEL_FF_REITH_SERIF};
  ${getElephant(latin)}
`;
```

The above code gives this output:
![Selection_010](https://user-images.githubusercontent.com/29686866/97328201-c8a22880-189b-11eb-9abf-73f603c0f731.png)

This is clearly Helvetica so I'm guessing the Reith font did not get installed with the GlobalStyles.
