### ISSUE TITLE
Create psammead-footer

### ISSUE THREAD

**Issue by pjlee11** [BBC-archive/psammead#395]
**Is your feature request related to a problem? Please describe.**
In the [Simorgh PR](https://github.com/bbc/simorgh/pull/1491) we added the Footer component directly in the footer container due to time constraints. We should make a psammead-footer so the component is reuse-able. 

**Describe the solution you'd like**
Create a new component `psammead-footer` which sets 3.5rem (56px) `${GEL_SPACING_QUAD}` padding-top.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Snapshot tests and storybook stories are required. 

**Additional context**
n/a

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Closed since as of https://github.com/bbc/simorgh/pull/2611 the footer has no associated styles.
