### ISSUE TITLE
psammead-copyright `<p>` has `role="text"` - not supported in spec

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#396]
**Describe the bug**
We're currently doing:

```js
const Copyright = styled.p.attrs({
  role: 'text',
})
```

```html
<p role="text" class="Copyright-sc-11lgtw-0 eqxQmp">
```

This is failing the [W3C HTML validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.bbc.com%2Fnews%2Farticles%2Fcpzk9lkk2p7o) as [`role="text"` is not officially part of the spec](https://incl.ca/roletext-presently-kinda-not-thing-sorta/).

However, it was added to improve the VoiceOver experience (alternative would be 5 swipes to get past an image with a source and caption).

I wonder if there's a way we can accomplish both? If not, we should write an ADR (or at least a section in the psammead-caption readme) which describes the decision we've taken.

**To Reproduce**
See above.

**Expected behavior**
Our HTML pages should validate.

**Additional context**
This was probably added for a good reason - check with @greenc05.

- [x] Initially labelled with ["bug"](https://github.com/bbc/psammead/labels/bug)

**Comment by greenc05** [comment]
Role text was added to stop the 'text splitting' that is observed when using VoiceOver on iPhone to improve the screen reader UX, without this, the image source element is 2 swipes, one for 'Image source' and one for the actual source such as 'Getty images'. If we don't want any exceptions in our HTML validation then this will have to be removed, there aren't any other ways around this that I'm aware of.

**Comment by sareh** [comment]
We should add an explanation for the `role="text"` to the Accessibility section of the [Psammead-Copyright Readme](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-copyright/README.md). It should explain why the `role="text"` is necessary.
