### ISSUE TITLE
Inline link hover styling overlaps when the user is zoomed in

### ISSUE THREAD

**Issue by jamesbrumpton** [BBC-archive/psammead#397]
**Describe the bug**
If the user zooms in and hovers over an inline link the styling appears to overlap

**To Reproduce**

1. Run Storybook
2. Select Caption with an inline link
3. Using the browser's zoom in function, zoom in
4. Hover over the inline link
5. Observe

**Expected behavior**
The inline link styles should not overlapped when zoomed in
![Screen Shot 2019-03-26 at 15 09 13](https://user-images.githubusercontent.com/25743793/55009627-cbaba780-4fda-11e9-8792-2602103e0dc2.png)

- [ ] Initially labelled with ["bug"](https://github.com/bbc/psammead/labels/bug)

**Comment by sareh** [comment]
Blocked pending font file update that is happening. Can be reviewed after using Reith version 2.5xx
