### ISSUE TITLE
Investigation: How should we handle vertical rhythm/spacing in psammead

### ISSUE THREAD

**Issue by pjlee11** [BBC-archive/psammead#399]
**Is your feature request related to a problem? Please describe.**
Currently, we add vertical spacing, such as `padding-bottom`, to `psammead-figure`, `psammead-headings` and `psammead-paragraph`. This means that psammead can't produce a `<figure>` without define spacing below which limits the shareability of these components. 

**Describe the solution you'd like**
We should remove the vertical padding/margin off of "top-level" components (Organisms). 

**Describe alternatives you've considered**
We could set the default export to be without margin's then export another with margins.

**Testing notes**
[Tester to complete]

Dev insight: Snapshots will need updating. 

**Additional context**
Following this the application using psammead components should define the vertical spacing between components.

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by dr3** [comment]
How about 
```
import Figure, { FigureWithMargins } from '@bbc/psammead-figure'
```

**Comment by pjlee11** [comment]
^^ Good idea, added as a alternative solution

**Comment by jamesbhobbs** [comment]
Mentioned here: https://github.com/bbc/psammead/issues/408

**Comment by sareh** [comment]
Closing in favour of this new issue: https://github.com/bbc/psammead/issues/1431
