### ISSUE TITLE
Stylelint doesn't always throw error on multiple uses of `color`

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#40]
**Describe the bug**
Adding `color` twice to the same rule should raise an error. But Stylelint only throws that error if it detects _additional errors_ with it.

See https://github.com/BBC-News/psammead/pull/34#pullrequestreview-178188074 for full context.

We should identify which stylelint library/plugin/dependency has the bug, and raise an issue with them to get it fixed.

**To Reproduce**

1. Add a duplicate `color` property to any styled component.
2. Run `npm run test:lint:css` and watch it pass.
3. Now add `made-up-property: foo` to that same component.
4. Run `npm run test:lint:css` and watch it fail with TWO errors: one complaining about the color duplication, and one complaining about the made up property.

**Expected behavior**
It should error at step 2.

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/psammead/labels/bug)

**Comment by bcmn** [comment]
As far as I can tell this isn't a bug, so much as a subtle choice of the stylelint config we're using, `stylelint-config-recommended`.

There is a rule to achieve this behaviour, called [`declaration-block-no-duplicate-properties`](https://stylelint.io/user-guide/rules/declaration-block-no-duplicate-properties/). If we manually add it with a value of `true`, it behaves as this issue describes it should.

However, [stylelint-config-recommended implements this as follows](https://github.com/stylelint/stylelint-config-recommended/blob/ca9a869788a3c23b602ce23404ce73a0489e0efd/index.js#L9-L14):
```
"declaration-block-no-duplicate-properties": [
      true,
      {
        ignore: ["consecutive-duplicates-with-different-values"]
      }
]
```

The current stylelint behaviour is in line with this configuration. I'm personally not sure why this would be a beneficial thing, & would lean towards overriding it, if that's how other people feel?

**Comment by ChrisBAshton** [comment]
Hmmm.... it makes sense for fallbacks actually, e.g.

```css
display: block; /* IE */
display: grid;
```

...so I now understand why it wouldn't error when it sees duplicate properties. But I _don't_ understand why it would decide to error on duplicate properties when it finds another error! (Unless I put that `made-up-property` between the `color` declarations...? Could you check and verify?)

**Comment by bcmn** [comment]
> Hmmm.... it makes sense for fallbacks actually, e.g.

Aha! Thanks very much, I was racking my brain but didn't think of that.

> But I don't understand why it would decide to error on duplicate properties when it finds another error! (Unless I put that made-up-property between the color declarations...? Could you check and verify?)

![screen shot 2018-11-27 at 14 15 29](https://user-images.githubusercontent.com/11646957/49087475-febd7480-f24e-11e8-849f-38dcac808f30.png)

I can't replicate that unless it's in between the property declarations, no. Happy to close the issue? 🙂

**Comment by ChrisBAshton** [comment]
Thanks for checking. Sounds good! 👍
