### ISSUE TITLE
Organise peerDependencies for all components

### ISSUE THREAD

**Issue by pjlee11** [BBC-archive/psammead#402]
**Is your feature request related to a problem? Please describe.**
We should evaluate the `dependencies` of each of our components to ensure that we utilise both `peerDependencies` and `devDependencies` correctly. 

`peerDependencies` are required when the component needs a dependency for production but we do not want duplicates of the dependency in the component and the application which uses the component. EG: `react` and `styled-components`

`devDependencies` are required when the component needs a dependency for development, such as unit tests or stories. An example of this would be a unit test which created a React component to inject into the component being tested. EG: `React` or `styled-components`

`peerDependencies` and `devDependencies` are not mutually exclusive. 

Currently, if we `npm link` components from psammead to simorgh we get a duplicate of `styled-components` meaning the visual render is buggy. We also have `react` as a duplicate dependency in some places which is mitigated via treeshaking but we should fix this in the packages to ensure other applications without tree shaking won't have `react` on the page multiple times.

**Describe the solution you'd like**
Evaluate the dependencies of each package. Especially moving `react` and `styled-components`.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit and cypress tests  won't change, a visual regression of each component is necessary. 

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
My understanding is that we basically want to:

* ensure that all components have a peer dependency of `react` and `styled-components`, in order to:
* ...be able to `npm link` in the renderer, without any bugginess

I don't know where `devDependencies` comes into this, or indeed "duplicate dependency of react"

Could you rewrite some of the issue to clarify this and I'll take another look after? 😄

**Comment by pjlee11** [comment]
I've updated the description, let me know if this clarifies things
