### ISSUE TITLE
P2 a11y bug - episode list - Icon colour does not change colour when the user changes their colour preferences in Firefox

### ISSUE THREAD

**Issue by jroebu14** [BBC-archive/psammead#4037]
**Describe the bug**
Icon colour does not change colour when the user changes their colour preferences in Firefox. An example of how to do this has already been provided and discussed with dev and UX and can be seen here http://2bitstudio.co.uk/code-tests/world-service/recent-episodes-audio-svg.html 

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
CC @greenc05

**Comment by gavinspence** [comment]
An example of how to do this has already been provided and discussed with dev and UX and can be seen here http://2bitstudio.co.uk/code-tests/world-service/recent-episodes-audio-svg.html

**Comment by LilyL0u** [comment]
The behaviour now matched that on http://2bitstudio.co.uk/code-tests/world-service/recent-episodes-audio-svg.html, with the icon and text matching the foreground colour chosen in FF preferences.

In both the recent episodes component, and on the 2bitstudio page, the release date and the H2 'Recent Episodes', as well as the dividing lines, do not change colour. I imagine this is acceptable as it is the same on the 2bitstudio page, but I just want to double check. Is this fine @greenc05 ?

**Comment by greenc05** [comment]
Everything should change colour @LilyL0u Did you select 'Always' when changing the colours?

**Comment by LilyL0u** [comment]
Retested. This is fine.
