### ISSUE TITLE
P2 a11y bug - episode list - Icon does not change colour when using a custom high contrast mode on windows

### ISSUE THREAD

**Issue by jroebu14** [BBC-archive/psammead#4038]
**Describe the bug**
Icon does not change colour when using a custom high contrast mode on windows

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**CC @greenc05

**Comment by gavinspence** [comment]
An example of how to do this has already been provided and discussed with dev and UX and can be seen here http://2bitstudio.co.uk/code-tests/world-service/recent-episodes-audio-svg.html

**Comment by LilyL0u** [comment]
Icon now changes colour when using a custom high contrast mode on Windows.
