### ISSUE TITLE
P2 a11y bug - episode list - P2 Icon should resize when the browser font size is changed

### ISSUE THREAD

**Issue by jroebu14** [BBC-archive/psammead#4039]
**Describe the bug**
Icon should resize when the browser font size is changed

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
CC @greenc05

**Comment by LilyL0u** [comment]
Icon resizes when I change the browser font size (Firefox, IE11 and Chrome)
