### ISSUE TITLE
h2 styling tweaks

### ISSUE THREAD

**Issue by pjlee11** [BBC-archive/psammead#404]
**Is your feature request related to a problem? Please describe.**
The new designs have the h2 with the following styles:

**Mobile (up to 600px)**
- padding-top 48px
- padding-bottom 24px

**Above Mobile**
- padding-top 56px
- padding-bottom 24px

Currently the padding-top is 32px on all breakpoints so needs updating.

**Describe the solution you'd like**
Given the H2 will most often follow an image or text block these both have a padding-bottom of 24px UX have agreed that for an MVP of vertical rhythm the h2 will specify padding-top minus 24px. 

Therefore the following CSS is needed on the h2:
```
styled.h2 {
    padding: 24px 0;

    @media-query(min-width:600px) {
        padding-top: 32px;
     }
}
```

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Snapshots will need updating and visual regression test in Storybook is required.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
We've raised #408 of the back of this, as this is not a sustainable way of working going forward. But to get us ready for v1 launch, this is a suitable measure for now 👍

**Comment by pjlee11** [comment]
Updated from 400px to 600px after confirming with UX
