### ISSUE TITLE
Humanize durations for screen readers

### ISSUE THREAD

**Issue by pharingee** [BBC-archive/psammead#4048]
**Is your feature request related to a problem? Please describe.**
We visually display media durations with a colon delimiter separating the units of time e.g. 1:00 - This is 1 minute and zero seconds. Screen readers infer their own semantics to this format. For example, VoiceOver Mac, Talkback and Jaws screen readers announce ‘1:00’ as ‘1 o’clock’ indicating time rather than duration.

Our current live solution for screen readers is to use a comma instead of a colon as the delimiter between the units of time. This is still less than optimal as there is no context for the units of time though this stops screen readers recognising this as a time format. For example ‘1,00’ is no longer announced as ‘1 o’clock’ but instead ‘1 zero zero’ or ‘1 0 0’.

However, when we looked into this solution we did not consider all the languages we support. On Russian with Voiceover Mac and iOS, this solution results in announcements dropping any last double zeros. For example ‘1,00’ is announced as ‘1’. Also on Russian some combinations of numbers using a comma delimiter are announced as fractions. For example ‘0,09’ is announced as ‘0 whole 9 of 100th’. I'm sure that Russian isn't the only service with issues.

**Describe the solution you'd like**
We need a solution that displays durations in a natural "human" way for screen readers, mentioning hours, minutes and seconds when we need to. e.g. "11 minutes 4 seconds" for English or "11 минут 4 секунды" for Russian.
The solution should not be dependent on moment since there is a possible move away from the moment library.
We need a solution that takes into account all the variations of all the languages we support.

**Describe alternatives you've considered**
The use of [HumanizeDuration.js](https://github.com/EvanHahn/HumanizeDuration.js). It is the closest solution we  have found to what we need but it does not include languages we support like pidgin although we can easily extend it.

The use of moment library. It includes the "ago" concept is more for past dates than for duration.

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by gavinspence** [comment]
While the current implementation of the durations is not perfect for screenreaders, this improvement would add significant page weight. The HumanizeDuration only supports [17/41 services](https://docs.google.com/spreadsheets/d/1zfg8WmyfKKmE5PjH3BabZAqUckzIXF0M74wRpgwKadw/edit?usp=sharing) -  meaning that we would still need to find a solution for the remaining services (or most likely keep the existing behaviour). 

With this in mind, I don't think it's worth taking this further given the small improvement. There are other bigger improvements we should be focusing on.
