### ISSUE TITLE
Proposal: move spacing-between-components responsibility to the renderer

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#408]
**Is your feature request related to a problem? Please describe.**
Reading issue #404, it's clear that vertical spacing between components is a complex problem, which we're currently solving by mixing and matching padding values between components and making assumptions about which components will appear in combination with others.

This is not sustainable, and is likely to cause significant technical debt and buggy behaviour over time.

Instead, components should be free of any padding/margin intended to denote vertical rhythm; this should become the responsibility of the renderer. We can define renderer-specific vertical spacing via:

In application, define spacing, using GEL foundations, e.g.:

```js
import { css } from 'styled-components';
import { GEL_SPACING } from '@bbc/gel-foundations/spacing';

const articleH2Spacing = css`
  padding: ${GEL_SPACING_DBL} 0;
  padding-top: ${GEL_SPACING_DBL};
`;

```

In component:

```js
const StyledSubHeading = styled.h2`
  color: ${C_SHADOW};
  font-family: ${GEL_FF_REITH_SANS};
  margin: 0; /* Reset */
  padding: ${GEL_SPACING_DBL} 0;
  font-weight: 700;
  ${GEL_TRAFALGAR};
  ${props => props.spacingStyles}
`;

export const SubHeading = ({spacingStyles = ``}) => {
  <StyledSubHeading spacingStyles={spacingStyles} />
};
```

https://github.com/bbc/grandstand/blob/master/lib/utilities/_spacing.scss

**Describe the solution you'd like**
A PR which removes all `margin-top`/`margin-bottom`/`padding-top`/`padding-bottom` from all components, and takes a `spacingStyles` prop (TBC).

This should be a major version release and be agreed between both teams.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by pjlee11** [comment]
I think we should be pairing with UX on this as they are currently of the opinion that some of the "bugs" would actually be beneficial to stop editorial staff from "styling" the page based on the block type they use and where they put them. 

https://github.com/bbc/simorgh/pull/1504 gives the initial explanation that we would review edge cases before deciding on a work flow. Also @dr3's [comment](https://github.com/bbc/psammead/issues/399#issuecomment-477173778) suggests that psammead could export both a component with margins and one without which is an interesting idea

**Comment by pjlee11** [comment]
>A PR which removes all margin-top/margin-bottom/padding-top/padding-bottom from all components, and takes a spacingStyles prop (TBC).

IMO this should be "remove from all organisms", otherwise things like `Link` in `SiteWideLinks` lose the context of having increased padding for accessibility touch area

**Comment by sareh** [comment]
Closing in favour of this new issue: https://github.com/bbc/psammead/issues/1431
