### ISSUE TITLE
Amend Canonical Consent Banner

### ISSUE THREAD

**Issue by simonsinclair** [BBC-archive/psammead#4290]
### Is your feature request related to a problem? Please describe.

Following a number of reviews, we must make some changes to the Canonical Consent Banner.

#### Visual UX
1. UX would like to make changes to the options container width between `400px - 599px`. Instead of options filling the entire width, they should be restricted to look more like the below image. See "New options container width" below.
2. At screen sizes where the options stack on top of each other, the last option needs to have the same padding as the one above. See "Fix bottom option padding" for context - the bottom option should have more space beneath it.
3. We should amend our `text-decoration: underline;` approach and create a faux-underline using `border-bottom` to give us control over its position. Previously, we could not see an example of this on live, but the following page shows there is a precedence for faux-underlines: https://www.bbc.com/afrique/region-55796266. (See point 4 below before starting this for links)

#### Screen reader UX / accessiblity acceptance criteria
1. Button hover state - While the grey on orange meets contrast, I’m not sure the contrast between this and the none hover state is sufficient to rely on colour alone, can we add an underline/border - see design https://app.zeplin.io/project/5c8a5e021d454124ef90669f/screen/600eb4159b96e2094d95484b
2. Button focus state - Add underline/border as per hover, and also reinstate the default focus outline (the box shadow on zeplin is an 'illustration' of this)
3. Add role list to attribue to ul. This will resinstate the list semantics on VoiceOver, which it removes due to seeing list stlye none on the CSS
4. Meet the following AAC (I suggest you implement a 2px transparent border on hover/focus to achieve this, 'transparent' will become a colour defined in the preferences in these modes) - for a code example see https://github.com/bbc/psammead/pull/707/files 

    Given I am using Windows High Contrast mode
    And also when I change my colour preferences in FireFox
    When I hover over link elements
    Then they have a visible state change
    
    Given I am using Windows High Contrast mode
    And also when I change my colour preferences in FireFox
    When I navigate through [component] by pressing the TAB key
    Then all links have a visible state change
    And this is in addition to the browser default focus outline styling
    
5. Meet the following AAC
    Given I am using Windows High Contrast mode
    And also when I change my colour preferences in FireFox
    When I view the consent/privacy banner
    Then an outline is visible for all buttons
    And I can see where the top of the compoment is **e.g. there is a line/border**

### Describe alternatives you've considered
N/A.

### Testing notes
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [ ] ~~This feature is expected to need manual testing.~~

#### New options container width
<img width="813" alt="Screenshot 2021-01-25 at 15 55 47" src="https://user-images.githubusercontent.com/1430787/105732268-2c360380-5f28-11eb-90b9-c35a35991137.png">

#### Fix bottom option padding
<img width="328" alt="Screenshot 2021-01-25 at 16 18 34" src="https://user-images.githubusercontent.com/1430787/105733047-00674d80-5f29-11eb-81a6-e3b30154bf3c.png">

**Comment by HarryVerhoef** [comment]
Thanks for the amendments @simonsinclair and @greenc05.

Regarding part 3 of the visual UX amendments, the faux-underline, if we are to use `display: flex;`, then it may be necessary to reintroduce the hacky `margin: auto;` solution to the problem where the `border` is applied to the block as a whole instead of each line. Is that ok?

**Comment by simonsinclair** [comment]
> Regarding part 3 of the visual UX amendments, the faux-underline, if we are to use `display: flex;`, then it may be necessary to reintroduce the hacky `margin: auto;` solution to the problem where the `border` is applied to the block as a whole instead of each line. Is that ok?

Hey @HarryVerhoef, before we reintroduce the `margin: auto` solution, please can you take a look at the implementation I linked above? If that doesn't work, then let's explore wrapping the text in a `span` element and applying a border to that - Sport use this option. 👍🏼

**Comment by HarryVerhoef** [comment]
Thanks for the response @simonsinclair, I don't think the implementation linked makes use of `display: flex`, but the `span` option sounds promising. I'll investigate and fire up a PR as soon as I can once training is over  👍
