### ISSUE TITLE
RTL testing for homepage card component

### ISSUE THREAD

**Issue by j-pendlebury** [BBC-archive/psammead#433]
**Describe the solution you'd like**
Make sure the component works with RTL scripts.

**Testing notes**
Entire box model should be reversed

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
IMO this should be done as part of each Card pr/issue, using storybook's toggle, and doesnt need to be its own issue. We can mention it in the `Dev insight` on those issues

**Comment by j-pendlebury** [comment]
Maybe this needs a bit of rephrasing because what I meant by this is testing with stuff like `padding-left` -> `padding-right`, etc., that it works correctly, and if not then this issue will take care of any further work.

But let's talk about this tomorrow.

**Comment by j-pendlebury** [comment]
No longer required. RTL testing is done as part of overall testing of each component.
