### ISSUE TITLE
Create a card component - mobile width

### ISSUE THREAD

**Issue by j-pendlebury** [BBC-archive/psammead#435]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/psammead/issues/391 which adds the card component with support focus on 600px we should iterate on it to support mobile widths

**Describe the solution you'd like**
Update the homepage card component to work at mobile widths.

UX designs - [[LINK]](https://app.zeplin.io/project/5c8a5e021d454124ef90669f?seid=5cac6dd258ed0fbf55cdc9bf) (DONT TRUST THIS SCREENSHOT, ITS OLD,  CHECK ZEPLIN)

![image](https://user-images.githubusercontent.com/11341355/55893948-26372d00-5bb1-11e9-96e3-5ce5f49871f0.png)
![image](https://user-images.githubusercontent.com/11341355/55893979-30592b80-5bb1-11e9-9251-eb45562182e3.png)

**Testing notes**
Dev insight: Unit test snapshots and storybook should be sufficient

**Additional context**
A 600px component to be created in https://github.com/bbc/psammead/issues/391.

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment]
Investigate that this is currently implemented :) if not, create a PR to fix it

**Comment by j-pendlebury** [comment]
On mobile widths, the story introduction should not be displayed. Will open a PR to make this change.

<img width="705" alt="image" src="https://user-images.githubusercontent.com/13763899/56956660-b5928900-6b3c-11e9-8520-70ff382dae56.png">
