### ISSUE TITLE
Update Creating-Components.md for AMP

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#438]
**Is your feature request related to a problem? Please describe.**
Once we've implemented the AmpImg component in #953, we'll have our first example of AMP vs canonical components.

We should update our [Creating-Components.md](https://github.com/BBC-News/simorgh/blob/latest/docs/Creating-Components.md) documentation to outline the ideal 'AMP-first' process.

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by amywalkerdev** [comment]
https://github.com/bbc/psammead/blob/latest/packages/components/README.md
https://github.com/bbc/psammead/blob/latest/CONTRIBUTING.md

Those are probably the best to mention amp-first

**Comment by jamesbhobbs** [comment]
I'm closing this to consolidate such issues
