### ISSUE TITLE
Upgrade Yeoman to v5

### ISSUE THREAD

**Issue by jroebu14** [BBC-archive/psammead#4447]
**Is your feature request related to a problem? Please describe.**
Yeoman v4 contains vulnerable packages.

**Describe the solution you'd like**
Upgrade Yeoman to v5.

**Describe alternatives you've considered**
Yeoman seems like it's not maintained too well since it's docs are quite out of date and has a few vulnerable packages that affect us. Maybe worth considering one of these options:

- Removing yeoman since we don't create new packages too often and I can't remember a time I've used it or anyone else has
- Replacing yeoman with something else, either another package generator or our own simple CLI or npm/node script e.g. `yarn packages:create` that accepts arguments e.g. package name, author etc and generates the package
- Removing yeoman and having a "skeleton package" that developers can duplicate and change as needed with documentation on what exactly to change.

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment]
Do we have a decision on this?

I'm 100% for removing it - we don't create many psammead packages, and we have a goal to create even fewer going forward.

Even if we ever create one again, it takes about 2 minutes regardless of whether we use yeoman or not

**Comment by jroebu14** [comment]
I agree, I don't think it would be missed too much. I'd be fine with removing but keen to hear other opinions.
