### ISSUE TITLE
GEL-Styled-Components package

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#45]
**Is your feature request related to a problem? Please describe.**
We should create a `gel-styled-components` npm package. 
It should be published to the BBC npm account (instructions here: https://github.com/bbc/npm) 

It should export variables in these files:
```
breakpoints.js
spacing.js
grid.js
typography.js
```

The `breakpoints` and `spacing` files export constants. Naming convention: `GEL_SPACING`
The `grid` and `typography` files export Styled Components. 

We should be able to import constants like this: 

`import { GEL_SPACING, GEL_MARGIN_BELOW_400PX } from "@bbc/gel-styled-components/spacing"`
`import { GROUP_0_SCREEN_WIDTH_MIN } from "@bbc/gel-styled-components/breakpoints"`
`import { T_BREVIER } from "@bbc/gel-styled-components/typography"`

Full discussion was on this issue: https://github.com/BBC-News/psammead/issues/32

**Describe the solution you'd like**
The package should live in this repository, in this directory:
`packages/utilities/psammead-styles`

It should have this structure:

- `README.md` (Basic description)
- `package.json` (Author: psammeadmaintainers@bbc.co.uk)
- `CONTRIBUTING.md` (for now, it should link to a parent CONTRIBUTING.md in `psammead`

- `spacing.js` Reference from Simorgh repo: https://github.com/BBC-News/simorgh/blob/latest/src/app/lib/constants/styles.js#L30-L50
- `breakpoints.js` Reference from Simorgh repo: https://github.com/BBC-News/simorgh/blob/latest/src/app/lib/constants/styles.js#L51-L82  Note: all these constants should be all-caps with underscores. e.g. `GROUP_0_SCREEN_WIDTH_MIN` 
The three typography breakpoint values should be updated to be in line with the GEL guidelines here http://www.bbc.co.uk/gel/guidelines/typography#type-sizes
`smartPhoneScreenWidthMin` => `GROUP_B_MIN_WIDTH`
`smartPhoneScreenWidthMax` => `GROUP_B_MAX_WIDTH`
`laptopScreenWidthMin` => `GROUP_CD_MIN_WIDTH`

As a result, this `mediaQuery` should be updated to be `MEDIA_QUERY_TYPOGRAPHY`. It is only needed for Typography https://github.com/BBC-News/simorgh/blob/latest/src/app/helpers/mediaQueries.js#L7-L13

- `typography.js`: Reference from Simorgh repo: https://github.com/BBC-News/simorgh/blob/latest/src/app/lib/constants/typography.js#L12-L73

- `grid.js` Reference from Simorgh repo: https://github.com/BBC-News/simorgh/blob/latest/src/app/lib/layoutGrid.js#L16-L82  **I suggest not yet including the grid variables in this PR.** These four variables `layoutWrapperWithoutGrid` `layoutGridWrapper` `layoutGridItemConstrained` `layoutGridItem` are currently only used in Footer, Brand, Article components and they should be refactored before we add them to this utility package. 

**Describe alternatives you've considered**
N/A

**Testing notes**
We should be able to import constants like this: 
`import { T_LONG_PRIMER } from "@bbc/gel-styled-components/typography"`
`import { T_LONG_PRIMER } from "@bbc/gel-styled-components/typography"`

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Before this ticket is picked up, it would be good to clarify the naming convention. e.g. we currently do not have prefix for breakpoint, `B_` even though we have one for Typography `T_`. Spacing uses `GEL_SPACING_` as the prefix, which is similar to what is used by the Sass implementation of GEL (https://github.com/bbc/gel-grid) that used `gel-spacing-unit`.

It would be good to have consistency in our naming convention across this package, prior to creating it.

**Comment by BogdanDogaru** [comment]
I agree with name-spacing this way, it should hopefully make our code easier to understand.
We need to document what each prefix means.

Also, do we just need to add a prefix for breakpoint, or are there other constants?

**Comment by dr3** [comment]
LGTM 👍

**Comment by sareh** [comment]
@bogdandogaru Regarding prefixes, I think it could be useful to have consistent prefixes, of the format `GEL_S_` for spacing, `GEL_T_` for typography, `GEL_B` for breakpoints, `GEL_G_` for grid.

Therefore we will have these changes:
`T_LONG_PRIMER` => `GEL_T_LONG_PRIMER`
`GEL_SPACING_DBL` => `GEL_S_DBL`
`GEL_MARGIN_BELOW_400PX` => `GEL_S_MARGIN_BELOW_400PX`
`smartPhoneScreenWidthMin` => `GEL_B_GROUP_B_MIN_WIDTH`
`smartPhoneScreenWidthMax` => `GEL_B_GROUP_B_MAX_WIDTH`
`laptopScreenWidthMin` => `GEL_B_GROUP_CD_WIDTH_MIN`

`group0ScreenWidthMin` => `GEL_B_GROUP_0_WIDTH_MIN`
`group0ScreenWidthMax` => `GEL_B_GROUP_0_WIDTH_MAX`

**Comment by dr3** [comment]
Quickly put togeather a PR so we can comment on the names easier, obs alot may change https://github.com/BBC-News/psammead/pull/48

**Comment by bcmn** [comment]
> @BogdanDogaru Regarding prefixes, I think it could be useful to have consistent prefixes, of the format `GEL_S_` for spacing, `GEL_T_` for typography, `GEL_B` for breakpoints, `GEL_G_` for grid.
> 
> Therefore we will have these changes:
> `T_LONG_PRIMER` => `GEL_T_LONG_PRIMER`
> `GEL_SPACING_DBL` => `GEL_S_DBL`
> `GEL_MARGIN_BELOW_400PX` => `GEL_S_MARGIN_BELOW_400PX`
> `smartPhoneScreenWidthMin` => `GEL_B_GROUP_B_MIN_WIDTH`
> `smartPhoneScreenWidthMax` => `GEL_B_GROUP_B_MAX_WIDTH`
> `laptopScreenWidthMin` => `GEL_B_GROUP_CD_WIDTH_MIN`
> 
> `group0ScreenWidthMin` => `GEL_B_GROUP_0_WIDTH_MIN`
> `group0ScreenWidthMax` => `GEL_B_GROUP_0_WIDTH_MAX`

I definitely agree it should be standardised this thoroughly. Would icons also be ultimately namespaced in a similar way, seeing as they are also part of GEL?

I can't tell how odd a single letter namespace would seem, or how much it would help/hinder users with different levels of experience with the library 🤔 Conflicted 😕

**Comment by ChrisBAshton** [comment]
Playing devil's advocate: why do we want to namespace our exports?

`import { T_BREVIER } from "@bbc/gel-styled-components/typography"`
^ seems a bit redundant

`import { BREVIER } from "@bbc/gel-styled-components/typography"`
^ feels better to me.

As the consumer, I already know I'm importing something from `typography` - why do we namespace twice?

**Comment by radiocontrolled** [comment]
LGTM 👍

**Comment by dr3** [comment]
@ChrisBAshton do you recommend the same thing for breakpoints and spacings?

**Comment by ChrisBAshton** [comment]
Hmmm, I think for breakpoints yes (`GEL_B_GROUP_B_MIN_WIDTH` => `GROUP_B_MIN_WIDTH`)

~~But for spacing, it's quite nice to reassure that this is a GEL spacing. (`GEL_SPACING_DBL` => `GEL_S_DBL` => `GEL_SPACING_DBL` - i.e. let's stick with what we already have!)~~ EDIT: no, `SPACING_DBL` is probably best for consistency 👍

**Comment by dr3** [comment]
So change 
https://github.com/BBC-News/psammead/pull/48/files#diff-c8816b16ab78743568c32ca0502b83eeR6 
`GEL_B_GROUP_B_MIN_WIDTH` to `GROUP_B_MIN_WIDTH`

https://github.com/BBC-News/psammead/pull/48/files#diff-46fe02720d5fe4a5dff6d57fee83acf5R6
`GEL_S` to `SPACING`

https://github.com/BBC-News/psammead/pull/48/files#diff-46fe02720d5fe4a5dff6d57fee83acf5R7
`GEL_S_DBL` to `SPACING_DBL`

https://github.com/BBC-News/psammead/pull/48/files#diff-0bca77da4961fbe55c210c5e64d472f1R4
`GEL_T_LONG_PRIMER` to `LONG_PRIMER`

**Comment by radiocontrolled** [comment]
We are saying in the comments that we are using GEL, so as long as we preserve / keep meaningful comments, the suggestion in https://github.com/BBC-News/psammead/issues/45#issuecomment-442060437 is also fine by me.

**Comment by sareh** [comment]
The `GEL` namespace is useful, so I propose we keep it.
The reason being that when anyone uses utilities within components and applications, there is a clear distinction between `GEL` utility constants and all other constants. 

I'm happy to agree to do without the `_T_`, `_B_` and `_S_`.

So, in summary: 
`T_LONG_PRIMER` => `GEL_LONG_PRIMER`
`GEL_SPACING_DBL` => `GEL_SPACING_DBL`
`GEL_MARGIN_BELOW_400PX` => `GEL_MARGIN_BELOW_400PX`
`smartPhoneScreenWidthMin` => `GEL_GROUP_B_MIN_WIDTH`
`smartPhoneScreenWidthMax` => `GEL_GROUP_B_MAX_WIDTH`
`laptopScreenWidthMin` => `GEL_GROUP_CD_WIDTH_MIN`
`group0ScreenWidthMin` => `GEL_GROUP_0_WIDTH_MIN`
`group0ScreenWidthMax` => `GEL_GROUP_0_WIDTH_MAX`

**Comment by dr3** [comment]
Thanks @sareh I have applied that pattern to https://github.com/BBC-News/psammead/pull/48

**Comment by sareh** [comment]
As a result of the creation of the PR #48, further discussion took place with regards to naming.

We decided to split this into two packages namespaced as `gel-`:

- `@bbc/gel-constants` which would include `spacing` & `breakpoints` These are just the exported constants.

- `@bbc/gel-foundations-styled-components` which would include `grid` `typography`  
This will be where we later pull in GEL iconography, as and when it is needed.

**Comment by dr3** [comment]
As seen above this work is now taking place in https://github.com/BBC-News/psammead/pull/69 and  https://github.com/BBC-News/psammead/pull/70
