### ISSUE TITLE
Refactor inputProvider storybook helper function

### ISSUE THREAD

**Issue by amywalkerdev** [BBC-archive/psammead#450]
**Is your feature request related to a problem? Please describe.**
The inputProvider storybook helper function doesn't allow passing in default text for the storybook knob, instead it always uses 'Enter sample text'.

**Describe the solution you'd like**
Refactor the function so it allows passing in default text as well as the component and name.

It should still accept switching with translations too.

**Testing notes**
[Tester to complete]

Dev insight: Storybook example and unit tests

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by andrew-nowak** [comment]
Also closely related to #454 and #456
