### ISSUE TITLE
Slack notifications are not posted in the _#si_repo_psammead_ channel.

### ISSUE THREAD

**Issue by alex-magana** [BBC-archive/psammead#458]
**Describe the bug**
Slack notifications issued from Jenkins builds for the `psammead` job aren't posted on
`#si_repo_psammead` channel.

**To Reproduce**

1. Go to https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/psammead/branches
2. Click on the _Run_ button to initiate a build. This is the `play` icon to the right of a branch listing.
3. Select the `Deploy Storybook & Publish to NPM` step in the pipeline e.g https://ci.news.tools.bbc.co.uk/blue/organizations/jenkins/psammead/detail/latest/171/pipeline
4. Select the `Send Slack Message` step.
5. Observe the output below.
```
run slackstepsend, step null:false, desc :false

Slack Send Pipeline step configured values from global config - baseUrl: true, teamDomain: true, token: true, channel: false, color: false

ERROR: Slack notification failed. See Jenkins logs for details.
```
6. The slack notification isn't posted in the `#si_repo_psammead` channel.

**Expected behavior**
The `Send Slack Message` step should result in a notification in the `#si_repo_psammead` channel on slack.

**Screenshots**

**Additional context**

- [ ] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by pharingee** [comment]
I'm unable to reproduce the error, and Slack messages seem to be sending fine now. @benjaminhobbs did you fix this?
