### ISSUE TITLE
Set up Jenkins CI to run tests

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#46]
**Is your feature request related to a problem? Please describe.**

- On each PR, Jenkins CI should run the tests `npm run test`. This should include both unit tests and linting (eslint, stylelint). 

- On each merge into `latest`, Jenkins CI should run the tests. 

**Describe the solution you'd like**
There should be a Jenkinsfile in this repository that runs the tests on each commit on each branch and whenever there is a merge into the `latest` branch. 

Please refer to this Simorgh Jenkinsfile: https://github.com/BBC-News/simorgh/blob/latest/Jenkinsfile & the related Makefile: https://github.com/BBC-News/simorgh/blob/latest/Makefile

**Describe alternatives you've considered**
We've discussed using Travis. For now, Jenkins should be sufficient. 

**Testing notes**
There should be all tests passing on a PR.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
RE "why we're not using Travis [yet]": we’ve gone for Jenkins for simplicity (we don’t have Travis set up yet, and we need Jenkins for the Storybook deployment, so may as well use Jenkins for both - for the time being).
