### ISSUE TITLE
Create @bbc/psammead-promo-separator

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#463]
**Is your feature request related to a problem? Please describe.**
In between our story promos we need a separator line.

**Describe the solution you'd like**
Create a psammead component for the separator

UX spec:

- Height: 1px
- Colour: `C_LUNAR` from `@bbc/psammead-styles/colours`
- Spacing:
  - `0` - `600px`:
    - Above: 16px - `GEL_SPACING_DBL` from `@bbc/gel-foundations`
    - Below: 8px - `GEL_SPACING` from `@bbc/gel-foundations`
  - +`600px`:
    - Above: 16px - `GEL_SPACING_DBL` from `@bbc/gel-foundations`
    - Below: 16px - `GEL_SPACING_DBL` from `@bbc/gel-foundations`
  - +`1008px`:
    - Above: 24px - `GEL_SPACING_TRPL` from `@bbc/gel-foundations`
    - Below: 24px - `GEL_SPACING_TRPL` from `@bbc/gel-foundations`

![image](https://user-images.githubusercontent.com/11341355/56655359-6eaf1a00-668a-11e9-88f8-1c45476c3b7c.png)

note: side padding will be done by simorgh wrapper and isn't needed in this component

**Testing notes**
[Tester to complete]

Dev insight: Snapshot and storybook

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by DenisHdz** [comment]
Closing in favour of #477
