### ISSUE TITLE
Add missing typography styles to scripts

### ISSUE THREAD

**Issue by ghost** [BBC-archive/psammead#465]
**Is your feature request related to a problem? Please describe.**
The following styles are missing in all the other scripts except `latin` and `cyrillic`
 * Atlas
* Elephant
* Imperial
* Royal
* Foolscap

This will raise an error on `getTypeSizes` when any of the missing style is requested.

**Describe the solution you'd like**
Add styles for the missing typography styles to `latinDiacritics`, `arabic`, `arabicPashto`,`bengali`, `burmese`,`hindi`,`nepali`,`sinhalese`,`tamil`,`thai`,`chinese`,`korean` and `ethiopic`

[Tester to complete]

Dev insight: Unit tests will be sufficient

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by DenisHdz** [comment]
Those styles haven't been defined by UX in the spreadsheet, that's why they weren't added into the rest of the scripts files and I believe we won't be using them in our components.
As they were already in Psammead, we placed them just in the `latin-and-cyrillic` script.
@pjlee11 Do you know if those GEL Types are used by the Articles Team?

**Comment by pjlee11** [comment]
My understanding is that those typography specs need UX to confirm the sizes. I'm not sure where they are being used, not convinced articles are even using those groups yet. This should be blocked in UX providing the values for those typography groups

**Comment by andrew-nowak** [comment]
UX are not currently planning to use any of these styles, and therefore do not want to spend time defining the values. As they also do not believe that they are being used anywhere, and a quick search across psammead and simorgh seems to confirm this, we propose deleting the `getAtlas` etc. functions, which should help prevent these errors. The values could also be removed from the `latin` script. These functions and values could be added again once they are required and values have been defined for each style in every script.

@pjlee11 @sadickisaac Do you have opinions on this suggestion?

**Comment by pjlee11** [comment]
I'd be happy to move forward by deleting the unused functions

**Comment by ghost** [comment]
Am all for deleting the functions if they are not currently used in the project.

**Comment by DenisHdz** [comment]
Closing in favor of #516
