### ISSUE TITLE
Allow for brand to be passed SVG height

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#466]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/psammead/issues/199 we are able to pass different SVG groups into the brand. Because of the differences in width, we need to be able to define a svg height

**Describe the solution you'd like**
Accept an SVG height props which sets the height of the SVG element. The width should be dynamic, based on the SVG height received and the svg ratio.

**UX:**
- 0 -> 600px the banner should always be 62px tall
- 600px+ the banner should always be 80px tall

- The banner should accept props to set the height of the SVG at 
`0 - 319` width
`320 - 599` width
`600+` width

E.g. A brand could have an svg thats 16px below 320, 20px 320 -> 599 and 24px 600px+
All values should be setable via props

![image](https://user-images.githubusercontent.com/11341355/56796868-616d6900-680b-11e9-9dd4-81d2cd692dbb.png)

The full height of the brand should be fixed at 62px below 600px width and 80px above 600px width. The SVG should remain vertically centered

This _WILL_ change the height of the brand for news, this is expected https://github.com/bbc/simorgh/issues/1637#issuecomment-487060909

**Testing notes**
[Tester to complete]

Dev insight: Storybook with knob to set heights

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by dr3** [comment]
~Blocked on UX news confirmation~
done https://github.com/bbc/simorgh/issues/1637#issuecomment-487060909

**Comment by pjlee11** [comment]
For the record we previously handled the scaling of the SVG's on the alephAMP solution dynamically like so:
```
// HTML
<a href="/russian" class="brand__svg russian--branding ">
  <svg width="410" height="30" viewBox="0 0 328 24" xmlns="http://www.w3.org/2000/svg">
    <g fill="none" fill-rule="evenodd">
     <path> {PATH_HERE}</path>
    </g>
  </svg>
  <span class="off-screen">BBC News Русская служба </span>
</a>

// CSS
.brand__svg russian--branding {
  max-width: 50%;
}

svg {
  max-height: 30px;
    max-width: 100%;
}
```

- [Example AMP page with dynamic SVG](https://www.bbc.com/russian/amp/features-48103147)
- [CodePen of dynamic SVG](https://codepen.io/phil-lee/pen/QPRyKL?editors=1100)

**Comment by pjlee11** [comment]
Above 600px width:
80 total height, 24px svg, padding top and bottom 28px. Implemented as padding bottom 24px with a 4px border on hover. 

Below 600px width:
62px, 24px space reserved for svg (SVG could be small and vertically centred), padding top and bottom 19px (ew - this should probably be confirmed with UX ideally this would be 16px padding so 56px total banner height. If not 20px is better than 19px.) Implemented with a border bottom, is this remaining as 4px, the same as above 600px

**Comment by pjlee11** [comment]
UX have confirmed 56px under 600px width
