### ISSUE TITLE
Psammead brand throws error if svg isnt provided

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#472]
**Describe the bug**
If you don't provide a svg to @bbc/psammead-brand it throws an error. While it is currently a required prop, it should fail safe.

**To Reproduce**

1. Call the brand without an svg
2. See error `Cannot read property 'viewbox' of undefined`

**Expected behavior**
It fails gracefully, not throwing an error

- [x] Initially labelled with ["bug"](https://github.com/bbc/psammead/labels/bug)

**Comment by ghost** [comment]
By failing gracefully do you mean not displaying the `Brand` component and not throwing an error in the process?

**Comment by dr3** [comment]
Either returning null for the whole brand, or not rendering a svg. Either way, we need to not access `svg.viewbox` if `svg` is null.

Worth checking with UX if they would prefer a page render with no svg in a brand or no brand entirely

**Comment by laurapsn** [comment]
The brand component should be rendered without the brand svg.
