### ISSUE TITLE
Create font mapping utility

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#478]
**Is your feature request related to a problem? Please describe.**
In psammead we currently manually hardcode font settings such as
```
font-family: ${GEL_FF_REITH_SERIF};
font-weight: 500;
font-style: italic;
```

For news this works fine, however as we move to new services we need to ensure that we map the logic correctly.

**Describe the solution you'd like**
Create some utility which maps the desired settings into css. An example of this could be
```
const styles = getFoobar({ serif: true, weight: 'bold', italic: true}, serviceConfig);
```
This would automap for the service e.g.
News
```
font-family: ${GEL_FF_REITH_SERIF};
font-weight: 500;
font-style: italic;
```
Persian
```
font-family: ${PERSIAN_FONT_FAMILY};
font-weight: 700;
font-style: normal;
```

Stages of issue: 
1) Propose a solution to the ws and articles pods
2) Implement solution in psammead

**Testing notes**
[Tester to complete]

Dev insight: Unit tests for dayyyss

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by DenisHdz** [comment]
Blocked until UX provides us the fallbacks.

**Comment by dr3** [comment]
Closing in favour of https://github.com/bbc/psammead/issues/539
