### ISSUE TITLE
Create new font faces in @psammead-styles

### ISSUE THREAD

**Issue by DenisHdz** [BBC-archive/psammead#479]
NOT NEEDED FOR FIRST 3 SERVICES

**Is your feature request related to a problem? Please describe.**
Create new font faces in [`Psammead styles`](https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-styles/src/fonts.js) package.

**Describe the solution you'd like**
Using the fonts defined in [News Fonts](https://github.com/bbc/news-fonts/) add the required font faces to the package.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

**Additional context**

- [X] Initially labelled with ["Refinement needed"](https://github.com/bbc/psammead/labels/Refinement%20Needed)

**Comment by j-pendlebury** [comment]
Closed due to duplication https://github.com/bbc/psammead/issues/735
