### ISSUE TITLE
InputProvider errors on components with children

### ISSUE THREAD

**Issue by ghost** [BBC-archive/psammead#495]
**Describe the bug**
When you pass a component that has a `child` or `children` to `inputProvider`, an error is thrown.
```jsx
InputProvider(['inline link', 'caption'], (linkText, captionText) => (
  <Caption script={latin}>
    {captionText}
    <InlineLink href="https://www.bbc.com"> {linkText} </InlineLink>
  </Caption>
)
```

**To Reproduce**

1. Go to Storybook Caption
2. Click on with offscreen text

**Expected behavior**
`inputProvider` should be able to handle components with and without children.

**Screenshots**
**Desktop (please complete the following information):**

- OS: macOs
- Browser: Chrome
- Version: 74

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andrew-nowak** [comment]
Not sure this is the case; the API for inputProvider changed in 2.0.0 so it should not be as simple as updating the package.jsons - I would expect your example to work when written as follows

```jsx
inputProvider(
  [
    { name: 'inline link', defaultText: 'A link' },
    { name: 'caption', defaultText: 'This is a caption' },
  ],
  ([linkText, captionText], script) => (
    <Caption script={script}>
      {captionText}
      <InlineLink script={script} href="https://www.bbc.com">
        {linkText}
      </InlineLink>
    </Caption>
  ),
)
```

**Comment by ghost** [comment]
I have submitted an issue to update the stories to use `@bbc/psammead-storybook-helpers@2.0.0`
https://github.com/bbc/psammead/issues/497
