### ISSUE TITLE
Make Branding SVGs link href dynamic

### ISSUE THREAD

**Issue by jamesbrumpton** [BBC-archive/psammead#500]
**Is your feature request related to a problem? Please describe.**
Currently, the SVGs are not dynamically linked but hardcoded to `bbc.co.uk/news` instead.

**Describe the solution you'd like**
The SVG branding should be dynamically linked. Accept a prop to be used as the inline link href. 

Default to the bbc homepage `https://www.bbc.com` (CONFIRM WITH PRODUCT), Maybe we could not use a link if a href isnt provided

**Testing notes**
The SVGs are linked to the relative branding.

Dev insight: Unit tests and storybook, have the link be a text knob

**Additional context**
https://github.com/bbc/psammead/blob/latest/packages/components/psammead-brand/src/index.jsx#L80

**Comment by clareevansbbc** [comment]
Regarding this question: 
> Default to the bbc homepage https://www.bbc.com (CONFIRM WITH PRODUCT), Maybe we could not use a link if a href isnt provided

We expect a service to always provide a link to the Front Page which should be applied to this Brand. If no link is provided we should not include the link, so that the Brand does not link to anywhere. 

Thanks
