### ISSUE TITLE
Promo with video content

### ISSUE THREAD

**Issue by greenc05** [BBC-archive/psammead#506]
**Is your feature request related to a problem? Please describe.**
We need to update the media indicator component as per the solution below and also add the video information to the link element

**Describe the solution you'd like**
Please see https://docs.google.com/document/d/1Y6fkoXoAP0BLIHJfAD48MhnDil1XQ_QFSwNI5DN8ZPg/edit?usp=sharing

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
This will be documented on the screen reader UX and accessibility acceptance criteria written week of 13th May

**Comment by j-pendlebury** [comment]
@david-boydell to talk to @greenc05

**Comment by dr3** [comment]
@greenc05 Can you confirm the implementation on https://www.test.bbc.com/igbo is correct :) if so, please close this issue :)

**Comment by greenc05** [comment]
Code looks good except for 2 small issues, which @aacn500 is going to address by removing the visually hidden text of 'video/audio' in the media indicator on the image. Will close this...  https://github.com/bbc/psammead/issues/698
