### ISSUE TITLE
Publishing is failing due to alpha versioning

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#518]
**Describe the bug**
Due to how we check for published packages in the registry, we try to publish already published alpha packages, throwing an error

**To Reproduce**

1. Run the psammead jenkins job
2. See error

```
You cannot publish over the previously published versions: 0.1.0-alpha.1. : @bbc/psammead-story-promo-list
```

**Expected behavior**
It knows its published and doesnt try

**Additional context**
This is failing as `npm show @bbc/psammead-story-promo-list version` returns `0.1.0-alpha.0`, the newest release tagged as `latest`. However, as `0.1.0-alpha.1` has been published, when it tries, it fails.

**Possible solution:**
Change [this code](https://github.com/bbc/psammead/blob/latest/scripts/publish/src/getRegistryVersion.js) to run `npm show ${name} versions` instead of `npm show ${name} version`. This returns an array of all published versions, regardless of if they are alpha or not. If our version matches any in that array, dont publish.

**Comment by chris-hinds** [comment]
Evidence of trying to publish a package which was in-fact already published but nit picked up by our publishing script.

![image](https://user-images.githubusercontent.com/14273378/57777669-49a64800-771a-11e9-9787-79f968b89c70.png)

**Comment by chris-hinds** [comment]
Evidence of publishing fix now working and not trying to publish an already published package

![image](https://user-images.githubusercontent.com/14273378/57781137-7f026400-7721-11e9-840b-fef06dbd8d96.png)

**Comment by chris-hinds** [comment]
@jamesbrumpton See above comments.
