### ISSUE TITLE
Update font config to be dynamic per service

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#539]
BLOCKED ON UX MAPPING CONFIG

**Describe the solution you'd like**
Update our [existing font families](https://github.com/bbc/psammead/blob/latest/packages/utilities/gel-foundations/src/typography.js#L4-L8) and manual weight and styling to be a function, dynamically created per service

**Describe alternatives you've considered**
Create 6 functions, in the format of `getSerifMedium(service)` which takes in service name for each service and exports css

Functions:
```
getSerifMedium('persian')
getSerifMediumItalic('persian')
getSansRegular('persian')
getSansItalic('persian')
getSansBold('persian')
getSansBoldItalic('persian')
```

Example behaviour
`getSerifMediumItalic('news')` returns
```
css`
font-family: ReithSerif, Helvetica, Arial, sans-serif;
font-weight: 500;
font-style: italic;
`
```
`getSerifMediumItalic('persian')` returns
```
css`
font-family: NassimPersian, Arial, Verdana, Geneva, Helvetica, sans serif;
font-weight: 700;
font-style: normal;
`
```

Depending on how complicated to config gets, we may decide that instead of passing in `service` we export `config` for each service which gets passed into the function. This is done to avoid bloating other services with weight. When implementing this, once you have a good idea of the size of the config, chat to the team and see what they think.

This can probably go in `@bbc/psammead styles` as it pairs closely with [the fontfaces used](https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-styles/src/fonts.js#L4). We can thus remove the font-family stuff from `@bbc/gel-foundations` [here](https://github.com/bbc/psammead/blob/latest/packages/utilities/gel-foundations/src/typography.js#L4-L8)

 
**Testing notes**
No testing

Dev insight: Unit tests

**Comment by j-pendlebury** [comment]
JIRA: WSFRONTPGS-26
Font Spreadsheet: https://docs.google.com/spreadsheets/d/1YIUyAS_WyrPudH-RTdVesFtUKvhNGhVejRSRThnCByw/edit#gid=0

**Comment by dr3** [comment]
Ive updated the above table to inc correct persian, confirmed with Laura

**Comment by dr3** [comment]
New UX criteria has come up, will update issue with new info

**Comment by clareevansbbc** [comment]
The remaining information required can be found here: https://docs.google.com/spreadsheets/d/15BqYKXzXrRD7cA7Nd5432x_D51ATilAfQEiZs10lUD8/edit#gid=1222978349

**Comment by ghost** [comment]
If `serifMedium` is requested for `persian` and `persian` doesn't have medium serif defined what should happen? should we return an `empty string` or `null` or try and see if `serifRegular` is available and return that.

**Update**
Document shared above by clare answers my question.
