### ISSUE TITLE
Add unit tests to Story Promo

### ISSUE THREAD

**Issue by DenisHdz** [BBC-archive/psammead#541]
**Is your feature request related to a problem? Please describe.**
At the moment we don't have tests that check if the `StoryPromo` component is rendering the right and expected elements.

**Describe the solution you'd like**
Add tests in `@psammead-story-promo/src/index.test.jsx` to check if the `StoryPromo` renders the `h3`, `p`, `time`, and `img` as done already in the Simorgh [container](https://github.com/bbc/simorgh/blob/latest/src/app/containers/StoryPromo/index.test.jsx).

Also, we should check if the Image is rendered with the `src` and `alt` attributes.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by ghost** [comment]
Why is `snapshot` testing not sufficient for `StoryPromo`. I am not convinced that we need to render `StoryPromo` using `react-testing-library` to make sure that we have the `h3`, `p`, `time` and `img`. This information is already in the snapshot data. `StoryPromo` is presentational and doesn't have any logic in it.
@sareh @hindsc52
