### ISSUE TITLE
Add mediaIndicator to Top Story Promo

### ISSUE THREAD

**Issue by j-pendlebury** [BBC-archive/psammead#545]
~BLOCKED ON [#572](https://github.com/bbc/psammead/issues/572).~

**Is your feature request related to a problem? Please describe.**
Similar to https://github.com/bbc/simorgh/issues/1574, Top Story Promo will need to be able to support media stories by showing the mediaIndicator for either audio or video media type.

**Describe the solution you'd like**
Top Story promo displays media indicator if the story is of type MAP.
Displays a SVG depending on media type.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**
![image](https://user-images.githubusercontent.com/13763899/59344547-3b8e1c00-8d06-11e9-9c8b-4deaa02d4d0b.png)

**Comment by andrew-nowak** [comment]
This might have already been done: https://github.com/bbc/psammead/pull/578/files#diff-cfe98725ca3d73fa9b4b1936998b8977R96
This ticket may just be checking that it works as expected

**Comment by andrew-nowak** [comment]
This looks done to me 
![image](https://user-images.githubusercontent.com/10963046/59690341-2ec36980-91d9-11e9-9bb1-155156ab2e8f.png)

**Comment by ghost** [comment]
Closing this issue. Read [this](https://github.com/bbc/psammead/issues/545#issuecomment-501216301) comment
