### ISSUE TITLE
Create moment package that includes additional localisations

### ISSUE THREAD

**Issue by amywalkerdev** [BBC-archive/psammead#549]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by dr3** [comment]
Closing in favour of https://github.com/bbc/psammead/issues/553 which has more description
