### ISSUE TITLE
Use metal for caption, timestamp, visited link

### ISSUE THREAD

**Issue by twinlensreflex** [BBC-archive/psammead#555]
**Is your feature request related to a problem? Please describe.**
We want the text of:

- [ ] caption
- [ ] timestamp
- [ ] visited link

to be the shade [#6E6E73 metal](https://bbc.github.io/psammead/?path=/story/utilities-psammead-styles--colours) 

**Describe the solution you'd like**
1. css updated to use metal colour
2. Please add before and after screenshot comparisons.

**Testing notes**
* colour contrast checking

Dev insight: Unit / snapshot tests are fine.

**Additional context**

**Comment by jamesbhobbs** [comment]
Duplicated here I think: https://github.com/bbc/psammead/issues/455
