### ISSUE TITLE
Export ESM version of psammead packages to allow tree shaking

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#557]
**Is your feature request related to a problem? Please describe.**
We currently export psammead packages as commonjs es5 modules. These dont allow for tree shaking which means currently, if you pull in 1 export of a component, you pull in all of them.

**Describe the solution you'd like**
Export an ESM version of our packages via a consistent API. We should decide this as a group but will likely be something like 

| commonjs | esm |
|----------|-----|
|`@bbc/psammead-styles/svgs` | `@bbc/psammead-styles/esm/svgs` |
| `@bbc/psammead-headings` | `@bbc/psammead-headings/esm` |

**The ESM files that are exported SHOULD be babel'd for `@babel/preset-react` and `babel-plugin-styled-components`**

**Testing notes**
[Tester to complete]

Dev insight: Unit tests for endpoints

**Comment by j-pendlebury** [comment]
Needs a conversation with Core Pod

**Comment by dr3** [comment]
Closing as done
