### ISSUE TITLE
Extend Most Read component to canonical pages

### ISSUE THREAD

**Issue by 12** [BBC-archive/psammead#563]
**Is your feature request related to a problem? Please describe.**
Following work carried out in #562, the Most Read component should now be extended to work on canonical pages as well.

**Describe the solution you'd like**
I want to be able to view the most read articles on a canonical, non-AMP page.

**Testing notes**
[Tester to complete]

Dev insight: Cypress and unit tests. Visual regression.

**Comment by 12** [comment]
This is blocked on #562

**Comment by sareh** [comment]
Closed as duplicate.
