### ISSUE TITLE
Put Caption component into Psammead

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#57]
**Is your feature request related to a problem? Please describe.**
Corresponding 'pull from Psammead' issue in Simorgh: https://github.com/BBC-News/simorgh/issues/1002.

**Describe the solution you'd like**
A PR in Psammead, which adds Caption component.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit tests (if any) will be transferred from Simorgh.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by BogdanDogaru** [comment]
Blocked on:
- [x] https://github.com/BBC-News/simorgh/pull/1019

**Comment by ChrisBAshton** [comment]
Blocked on https://github.com/BBC-News/simorgh/pull/1033
