### ISSUE TITLE
Create a skeleton package for psammead-most-popular

### ISSUE THREAD

**Issue by andrew-nowak** [BBC-archive/psammead#577]
**Is your feature request related to a problem? Please describe.**
We need to create the `psammead-most-popular` package.

**Describe the solution you'd like**
A package skeleton containing the various files common to all psammead packages eg. CHANGELOG.md, package.json, README.md, etc. Fill these out with as much information as you can, but feel free to leave sections with placeholders for now.

The package.json should contain `"private": true`, as described [here](https://github.com/bbc/psammead#balloon-publishing-a-package).

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by sareh** [comment]
Closed as fixed
