### ISSUE TITLE
Support non-latin numerals in most-read

### ISSUE THREAD

**Issue by andrew-nowak** [BBC-archive/psammead#584]
**Is your feature request related to a problem? Please describe.**
Not all services want to show the numbered Most Read list using 'latin' numerals (1, 2, etc.) but instead use the numerals used locally (for Persian: ١,٢, etc.)

https://github.com/bbc/simorgh/issues/1812#issuecomment-498670434

**Describe the solution you'd like**

**Describe alternatives you've considered**
https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type (bengali and arabic-indic seem to have good support on non-IE browsers)

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by sareh** [comment]
An alternate implementation is to have`list-style-type: none` for the ordered list and to include the numerals in a span with specific styles (relating to font, colour and script). So there should not need to be any specific 'support' other than a static map of values in the correct script. e.g.:

```
const numerals = {
  latin: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
  persian: ['۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹', '۱۰'],
  ...
};
```

This could be preferable for accessibility reasons.

**Comment by sareh** [comment]
Closed since we have the list of numerals via `@bbc/psammead-locales/numerals` https://bbc.github.io/psammead/?path=/story/utilities-psammead-locales--numerals
<img width="349" alt="Screenshot of numerals within storybook" src="https://user-images.githubusercontent.com/3028997/67387336-9aa24e00-f58e-11e9-92be-6ec9887b7639.png">
