### ISSUE TITLE
Create Navigation component

### ISSUE THREAD

**Issue by DenisHdz** [BBC-archive/psammead#593]
Jira ticket WSFRONTPGS-28

**Is your feature request related to a problem? Please describe.**
We need a Navigation bar for the WS Front Page.

**Describe the solution you'd like**
Create a navigation bar according to the UX designs and screen reader UX that meets the accessibility acceptance criteria.

<img width="971" alt="Screenshot 2019-06-12 at 11 16 31" src="https://user-images.githubusercontent.com/46446236/59343364-9d00bb80-8d03-11e9-8832-a2f9b426d51d.png">
<img width="471" alt="Screenshot 2019-06-12 at 11 16 52" src="https://user-images.githubusercontent.com/46446236/59343367-9eca7f00-8d03-11e9-8e05-99a63b4d7486.png">

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by j-pendlebury** [comment]
@DenisBBC to add screenshots
