### ISSUE TITLE
Update brand component story on storybook

### ISSUE THREAD

**Issue by ghost** [BBC-archive/psammead#606]
**Is your feature request related to a problem? Please describe.**
When a different service is chosen from the knob the visually hidden text on the `Brand`  component doesn't update.

**Describe the solution you'd like**
Provide a knob to allow changing of  the visually hidden text

**Testing notes**
[Tester to complete]

Dev insight: No test needed only visually checking the `DOM` for updates.

**Additional context**

**Comment by Bopchy** [comment]
This needs #609 to be merged so that knob can be added to the updated code
