### ISSUE TITLE
Add lang attribute to the brand component

### ISSUE THREAD

**Issue by ghost** [BBC-archive/psammead#607]
**Is your feature request related to a problem? Please describe.**
We currently don't have a lang attribute defined for the Brand Component which would help screen readers to announce brand name in the correct accent. i.e `BBC News’ is announced with an English accent.

**Describe the solution you'd like**
Add a `lang` attribute to the `Brand` component.

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by david-boydell** [comment]
Hi Dennis,

Is this definitely required to be _en-GB_? In https://www.w3.org/International/questions/qa-html-language-declarations#langvalues it says it should be _en_.

Cheers
David
