### ISSUE TITLE
Update psammead-styles to new definition of done

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#61]
**Describe the bug**
We have decided not to have a CONTRIBUTING.md file in each package.

psammead-styles should be updated to match psammead-assets's readme and delete the CONTRIBUTING.md file

Also update the author to Psammead Maintainers

Also add changelog in style of psammead-assets

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
And should also have a Changelog.md

**Comment by ChrisBAshton** [comment]
And update team name: https://github.com/BBC-News/psammead/blob/latest/packages/utilities/psammead-styles/package.json#L10
