### ISSUE TITLE
Psammead timestamp container - Accept and use moment locale

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#613]
**Is your feature request related to a problem? Please describe.**
We need to use different moment locales for different services

**Describe the solution you'd like**
Accept a 'locale' prop, and tell moment to use it. This makes the assumption that the locale is available to the package. 

Moment uses a `moment.locale('fa')` api to set the locale, which we can do once at the start of the component.

**Testing notes**
[Tester to complete]

Dev insight: Unit tests, storybook examples

**Additional context**

**Comment by dr3** [comment]
Persian: fa
news: en-gb
igbo: ig
yoruba: yo
pidgin: pcm

**Comment by andrew-nowak** [comment]
> Persian: fa
> news: en-gb
> igbo: ig
> yoruba: yo
> pidgin: pcm

These should be in `locale` in the service config already -- double check and add if necessary
