### ISSUE TITLE
Media Indicator improvements

### ISSUE THREAD

**Issue by andrew-nowak** [BBC-archive/psammead#632]
~~Needs discussion with @greenc05~~

Relates to bbc/simorgh#1940 and bbc/simorgh#1793

**Is your feature request related to a problem? Please describe.**
The visually hidden text for video promos is moving from the media indicator to the promo headline.

The entire element should be marked as `aria-hidden` - add this attribute to the top-most wrapping element and remove from all other elements.

The `<time>` element should only contain the duration if present, move the visually hidden text element outside of this.

Change the recommendations for usage of the visually hidden text prop in the README to only contain 'audio' and 'video', and not the duration. (we are keeping the visually hidden text for any user agents which do not respect `aria-hidden`.

The media indicator currently only renders the offscreen text if `duration && datetime && offscreenText` - but we should be able to render eg. `offscreenText="video"` even if we don't know the duration and vice versa.

**Testing notes**
[Tester to complete]

Dev insight: Unit tests

**Additional context**

**Comment by greenc05** [comment]
Spoken to @aacn500
