### ISSUE TITLE
World Service SVGs

### ISSUE THREAD

**Issue by pjlee11** [BBC-archive/psammead#635]
**Is your feature request related to a problem? Please describe.**
We previously asked UX for SVGs for the World Service websites, which they began producing fresh. This is not required as we have production ready SVGs in our current AMP solution which we can use. They are in the [repo](https://github.com/bbc/ws-alephamp-queue-renderer/tree/62db4f34962fcdea26afc907fa3abd089c0f7efb/assets/brand)

**Describe the solution you'd like**
Copy over the currently used simorgh WS SVGs (only 5) to `psammead-assets`. Edit the `viewbox` values to match the desired 24px height. 

Dont copy them all, we cant treeshake

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Snapshots and Storybook regression are required.

**Additional context**
This will save UX from having to produce assets that we already have.

**Comment by greenc05** [comment]
Can we please keep our accessibility attributes on the svgs, looking those in the repo I don't see them? e.g. focusable false and aria-hidden true

**Comment by greenc05** [comment]
Also, if these are for the brand - I'm not sure the SVG's look right, shouldn't they contain the word 'News' and also have a pipe/line after this before the local service name?

**Comment by dr3** [comment]
@pjlee11 Ive updated to say just the existing simorgh site SVGs and we cant treeshake yet, and thats alot of svg

**Comment by dr3** [comment]
Flicking between igbo and yoruba, they still appear to jump 🙈

**Comment by pjlee11** [comment]
If they still are jumping then I'd go back to UX and ask if it's worth trying export all service SVGs to be pixel perfect when the only place we will really see the "jump" is on storybook when flicking between services or on the odd case in the future where we link from service to service. Also given we have a Mobile first audience it's unlikely the brand would be in the viewport for the rare user journey that a user goes from one service to another and sees the brand "jump" by 1-2px's

**Comment by sareh** [comment]
We need the SVGs in `@bbc/psammead-assets/svgs` for Arabic, Pashto and Urdu, for the Articles project.  These should be carried out in the same way with the same accessibility markup as for Igbo, Pidgin, Yoruba Brand SVGs.
