### ISSUE TITLE
Create package checker script

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#64]
**Is your feature request related to a problem? Please describe.**
Eventually, and hopefully, we will have outside contributors to psammead. It would be good to have a script that can check a bunch of things on every commit to ensure standards are met.

**Describe the solution you'd like**
A script that checks for the following things:
- NPM package version has been increased
- Changelog.md has been updated
- Readme.md includes the expected required sections (contributing, Code of Conduct, licence etc)
- Check package.json includes "repository, author, licence, bugs, homepage"

**Additional context**
We could name the script after one of the children who keeps Psammead out of trouble https://en.wikipedia.org/wiki/Five_Children_and_It#Characters

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
Split out into two scripts:

1. Validate the component against a set criteria, e.g. readme contains everything, etc. This would run every time. (SHOULD for alpha-3)
2. Validate a changed component, in that it should have a new entry in the Changelog, should have a bumped package.json and package-lock.json. (MUST for alpha-3)

**Comment by ChrisBAshton** [comment]
Moved to #146 and #147.
