### ISSUE TITLE
Brand - Add transparent border for accessibility

### ISSUE THREAD

**Issue by greenc05** [BBC-archive/psammead#646]
**Describe the bug**
When you view the brand component in high contrast mode on PC or if you change the colour preferences in FF you don't see background colours and therefore can't see when the brand component ends/starts.

**To Reproduce**
- Change the colour preferences in FF - See check point 5 https://bbc-news.github.io/accessibility-news-and-you/accessibility-news-and-testers
- View in high contrast mode in PC - See check point 4 https://bbc-news.github.io/accessibility-news-and-you/accessibility-news-and-testers

**Expected behaviour**
When the brand component is in the header add CSS

```
  border-bottom: 0.0625rem solid transparent;
```
When the brand component is in the footer add CSS

```
  border-top: 0.0625rem solid transparent;
```

We will need different behaviour if there is navigation in the header - No border for the brand as we will have a bottom border from the navigation component - Speak to @DenisBBC 

**Screenshots**
Header - High contrast mode on PC without border bottom:
![banner-top](https://user-images.githubusercontent.com/1061401/59666812-7c29e180-91ad-11e9-8d90-5d511e578d09.png)

Header - High contrast mode on PC with border bottom:
![banner-top-with-line](https://user-images.githubusercontent.com/1061401/59666813-7cc27800-91ad-11e9-930a-6eda7151bebf.png)

Footer - Colour preferences changed in FF without border:
<img width="1392" alt="FF-bottom" src="https://user-images.githubusercontent.com/1061401/59666824-851ab300-91ad-11e9-8967-9baff225d55f.png">

Footer - Colour preferences changed in FF with border top and bottom (note bottom not to be applied here):
<img width="1392" alt="FF-bottom-with-border" src="https://user-images.githubusercontent.com/1061401/59666822-851ab300-91ad-11e9-978c-6a124dd194d9.png">

**Comment by DenisHdz** [comment]
Since the `Navigation` component is going to have a border at the bottom and it will allow us to make a separation between the `Brand` and the content of the page, we could pass a prop to the `Brand` and display the border if it's an `Article` and do not display it if it's the `Front Page`.

On the other hand, I just confirmed with UX that the `Brand` used in the Footer should have a border just at the top.

**Comment by laurapsn** [comment]
The requirement for the footer to have a border just at the top needs to be shared across Articles and Front pages for consistency.
