### ISSUE TITLE
Investigate better way of bumping version

### ISSUE THREAD

**Issue by ryanmccombe** [BBC-archive/psammead#648]
**Is your feature request related to a problem? Please describe.**
Some frustration is caused in how we handle the changelog / version bumping of Psammead - developers manually bump the version in package.json and add notes to the changelog

This causes conflicts when there are many PRs in progress - developers bump to a version that is already being used in another PR

The first PR that gets merged to latest will officially "claim" that version - outstanding PRs will now either need updated, or we may miss it and merge without a version bump

**Describe the solution you'd like**
It seems like there would be easier ways to handle this - eg, bumping version and possibly handling the changelog automatically on merge to latest

**Describe alternatives you've considered**
n/a

**Testing notes**
[Tester to complete]

Dev insight: Unlikely to require testing

**Additional context**
n/a

**Comment by jamesbhobbs** [comment]
NB https://www.npmjs.com/package/lerna-changelog

**Comment by jamesbhobbs** [comment]
An idea for this https://github.com/bbc/psammead/issues/888

**Comment by jamesbhobbs** [comment]
Going with https://github.com/bbc/psammead/issues/888
