### ISSUE TITLE
Discuss what to do with npm package psammead

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#65]
**Is your feature request related to a problem? Please describe.**
@radiocontrolled accidentally published psammead to https://www.npmjs.com/package/psammead. While this isn't a huge problem, as one of us would have had to claim it eventually, we should decide what to do with it.

### Possible options
- Make us all collaborators on it and use it. 
    Problem - Could get confused with `@bbc/psammead` if we ever made it
- Remove the code, publish an empty module with a readme explaining not to use it with a link to the github repo

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by dr3** [comment]
Talking to Phil, our best bet is to probably create a tiny npm package, with just a readme inside it, and publish over that publish. This means there will be no code in the package, just a readme

**Comment by dr3** [comment]
We should also change https://github.com/BBC-News/psammead/blob/latest/package.json#L2 `psammead` to be `@bbc/psammead` to avoid this in future. Also transfer ownership of the package to a team admin

**Comment by ChrisBAshton** [comment]
We made a similar mistake here:

https://www.npmjs.com/package/news-vj-developer-scaffold

Emailed NPM to ask them to remove it, and they then replace it with a Security Holding Package.

@radiocontrolled are you happy emailing NPM support? https://www.npmjs.com/support

**Comment by radiocontrolled** [comment]
@dr3 @ChrisBAshton Have emailed to ask for it to be removed & for a Security Holding Package to be added.

**Comment by radiocontrolled** [comment]
Reopening pending further discussion of https://github.com/BBC-News/psammead/issues/65#issuecomment-442130465

**Comment by radiocontrolled** [comment]
I have published over this: https://www.npmjs.com/package/psammead
