### ISSUE TITLE
Update package versions to V1

### ISSUE THREAD

**Issue by amywalkerdev** [BBC-archive/psammead#650]
**Is your feature request related to a problem? Please describe.**
Some of our package versions are still sub-V1 which causes issues as sub-v1 versions in npm are classed as major versions
e.g. `0.4.0` is a major bump from `0.3.0`

**Describe the solution you'd like**
Update the following packages to V1:
psammead-figure
psammead-image-placeholder
psammead-image
psammead-inline-link
psammead-media-indicator
psammead-section-label
psammead-sitewide-links
psammead-story-promo (alpha)
psammead-story-promo-list (alpha)
psammead-timestamp
psammead-visually-hidden-text
psammead-assets
psammead-styles
psammead-test-helpers

**Describe alternatives you've considered**
Leaving them as they are, which is messy and inconsistent with our other post v1 packages.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Comment by sareh** [comment]
Note: If the current version is an alpha version, please ensure that you set the new version to also be an alpha`1.0.0-alpha.0`.
