### ISSUE TITLE
Bump @bbc/gel-foundations to latest in all packages

### ISSUE THREAD

**Issue by chris-hinds** [BBC-archive/psammead#673]
**Is your feature request related to a problem? Please describe.**
We are using multiple versions of @bbc/gel-foundations across our packages and because of the tree-shaking issues this is being included in our bundle multiple times upping the bundle size.

**Describe the solution you'd like**
Until we have tree-shaking working correctly we should ensure that @bbc/gel-foundations is up to date in all our packages to reduce the use of various different versions across the repo.

**Describe alternatives you've considered**
None really!

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by dr3** [comment]
Issue LGTM
