### ISSUE TITLE
Add Licence file

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#7]
**Is your feature request related to a problem? Please describe.**
Consider best Licence and add to Psammead

**Describe the solution you'd like**
Repository has a defined licence

**Additional context**
Most likely we want to use the same licence as Simorgh https://github.com/BBC-News/simorgh/blob/latest/LICENSE

**Comment by ChrisBAshton** [comment]
Blocked on https://github.com/BBC-News/simorgh/issues/964
