### ISSUE TITLE
Components without a knob on story book show console error

### ISSUE THREAD

**Issue by thekp** [BBC-archive/psammead#702]
**Describe the bug**
Components on story book that do not use `knob` show an error in the console.
![image](https://user-images.githubusercontent.com/30599794/60090226-0b993c80-973a-11e9-87f5-41638e962fe6.png)

At the moment, I have found that `image-placeholder` shows this console error.

**To Reproduce**
Steps to reproduce the behaviour:

1. Run psammead story book locally
2. Go to image-placeholder component (image/image-placeholder)
3. Check the console in the browser

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andrew-nowak** [comment]
I wasn't able to replicate this locally, possibly it has already been fixed? @thekp could you check if this still occurs for you?

**Comment by thekp** [comment]
I've just checked locally and [here](https://bbc.github.io/psammead/?path=/story/components-images-imageplaceholder--1x1-image-placeholder). I also cannot see the console error anymore. And am happy for this issue to be closed.

Thanks @aacn500 .
