### ISSUE TITLE
Add getSerifBold in @bbc/psammead-styles/font-styles

### ISSUE THREAD

**Issue by ghost** [BBC-archive/psammead#717]
**Is your feature request related to a problem? Please describe.**
`StoryPromo` `Headline` uses a serif bold font and `@bbc/psammead-styles/font-styles` doesn't provide a function to get serif bold font styles.

**Describe the solution you'd like**
Add `getSerifBold` function to `@bbc/psammead-styles/font-styles` and confirm with ux on the fallback expected if a serif bold font isn't availble

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Unit tests

**Additional context**

**Comment by david-boydell** [comment]
Hi @sadickisaac, can you let me know what the fallback agreed with UX is?
