### ISSUE TITLE
Create font-family stacks for all WS sites

### ISSUE THREAD

**Issue by pjlee11** [BBC-archive/psammead#735]
**Is your feature request related to a problem? Please describe.**
For each of the WS sites add the correct `font-family` stack to `packages/utilities/psammead-styles/src/font-families.js`, similar to `nassimPersian`. 

**Describe the solution you'd like**
For each WS service create an exported `const` which contains the correct `font-family` and `font-style` and `font-weight`. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Storybook regression of the `Typographies` story ensuring the correct font-families are being used for the service

**Additional context**
Raised from https://github.com/bbc/psammead/pull/719

**Comment by sareh** [comment]
Alongside this, I suggest adding a table in the documentation stating which font-families should be used with which script configurations.

**Comment by dr3** [comment]
@pjlee11 This issue is to expand https://github.com/bbc/psammead/blob/latest/packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap to more services right?

**Comment by sareh** [comment]
Services and their font families (using the latest details from the UX spreadsheet)

AFRICA

Service |  Font Family
-- | --
Afaan Oromoo | Helmet, Freesans, Helvetica, Arial, sans-serif
Afrique | Helmet, Freesans, Helvetica, Arial, sans-serif
Amharic   (Ethiopic) | "Noto Sans Ethiopic", Arial, Verdana, Geneva, Helvetica, sans-serif
Gahuza | Helmet, Freesans, Helvetica, Arial, sans-serif
Hausa | Helmet, Freesans, Helvetica, Arial, sans-serif
Igbo | Helmet, Freesans, Helvetica, Arial, sans-serif
Pidgin/Naijá | Helmet, Freesans, Helvetica, Arial, sans-serif
Somali | Helmet, Freesans, Helvetica, Arial, sans-serif
Swahili | Helmet, Freesans, Helvetica, Arial, sans-serif
Tigrinya   (Ethiopic) | "Noto Sans Ethiopic", Arial, Verdana, Geneva, Helvetica, sans-serif
Yoruba | Helmet, Freesans, Helvetica, Arial, sans-serif

ASIA   (CENTRAL) 

Service |  Font Family
-- | --
Kyrgyz | Helmet, Freesans, Helvetica, Arial, sans-serif
Uzbek | Helmet, Freesans, Helvetica, Arial, sans-serif

ASIA   (PACIFIC)

Service |  Font Family
-- | --
Burmese | Padauk, Arial, Verdana, Geneva, Helvetica, sans-serif
Indonesia | Helmet, Freesans, Helvetica, Arial, sans-serif
Japanese | "Hiragino Kaku Gothic Pro", "ﾋﾗギﾉ角ゴPro W3", "MS PGothic", "MS UI Gothic", Helvetica, Arial, sans-serif
Korean | "Apple SD Gothic Neo", AppleGothic, "Malgun Gothic", Dotum, "Noto Sans CJK KR", sans-serif
Thai | Tahoma, Helmet, Freesans, Helvetica, Arial, sans-serif
UKChina | Helvetica, Arial, STHeiti, 华文黑体, "Microsoft YaHei", 微软雅黑, SimSun, 宋体
Vietnamese | Helmet, Freesans, Helvetica, Arial, sans-serif
Zhongwen | Helvetica, Arial, STHeiti, 华文黑体, Microsoft, YaHei, 微软雅黑, SimSun, 宋体

ASIA   (SOUTH) 

Service |  Font Family
-- | --
Bengali | "Shonar Bangla", Helmet, Freesans, Helvetica, Arial, sans-serif
Gujarati | "Mukta Vaani", Rasa, "Noto Sans Gujarati", "Hind vadodara", Shruti, Gautami, "Gujarati Sangam MN", "Gujarati MT", sans-serif
Hindi | "Noto Sans Devanagari", Arial, Verdana, Geneva, Helvetica, sans-serif
Marathi | "Noto Sans Devanagari", Hind, "Mukta Vaani", Gautami, "Kohinoor Devanagari", sans-serif
Nepali | "Noto Sans Devanagari", Arial, Verdana, Geneva, Helvetica, sans-serif
Pashto | "BBC Nassim Pashto", Arial, Verdana, Geneva, Helvetica, sans-serif
Punjabi | "Noto Sans Gurmukhi", Gautami, "Kohinoor Gurmukhi", sans-serif
Sinhala | "Iskoola Pota BBC", Arial, Verdana, Geneva, Helvetica, sans-serif
Tamil | Latha, Helmet, Freesans, Helvetica, Arial, sans-serif
Telugu | Mallanna, "Noto Sans Telugu", "Hind Guntur", Gautami, "Kohinoor Telugu", sans-serif
Urdu | "BBC Nassim Urdu", Arial, Verdana, Geneva, Helvetica, sans-serif

EUROPE 

Service |  Font Family
-- | --
Azeri | Helmet, Freesans, Helvetica, Arial, sans-serif
Russian | Helmet, Freesans, Helvetica, Arial, sans-serif
Serbian | Helmet, Freesans, Helvetica, Arial, sans-serif
Turkce | Helmet, Freesans, Helvetica, Arial, sans-serif
Ukrainian | Helmet, Freesans, Helvetica, Arial, sans-serif

LATIN   AMERICA 

Service |  Font Family
-- | --
Portuguese | Helmet, Freesans, Helvetica, Arial, sans-serif
Mundo | Helmet, Freesans, Helvetica, Arial, sans-serif

MIDDLE   EAST 

Service |  Font Family
-- | --
Arabic | "BBC Nassim Arabic", Arial, Verdana, Geneva, Helvetica, sans-serif
Persian | "BBC Nassim Persian", Arial, Verdana, Geneva, Helvetica, sans-serif

Updated 29-07-2019 according to UX requirements.

**Comment by sareh** [comment]
Blocked pending clarification with regards to which font families to use for each service.

**Comment by ryanmccombe** [comment]
Adding media tag as this is required for our v1

I'm happy to start a PR for these services if that would help @sareh ?

- Amharic
- Oromo
- Indonesia
- Korean
- Tigrinya

**Comment by sareh** [comment]
Confirmed the font-families with Laura from UX & updated the table above accordingly (https://github.com/bbc/psammead/issues/735#issuecomment-512775637). 
Thanks, @ryanmccombe, I've started work on this now. Will share it with you for code review. 🙂
