### ISSUE TITLE
Brand can't be seen in FireFox when a user changes the colour preferences

### ISSUE THREAD

**Issue by pjlee11** [BBC-archive/psammead#736]
**Describe the bug**
When a user changes the colour preferences in FireFox the brand SVG is displayed as white on a white background (if a white background colour has been chosen) and therefore can't be seen. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to `FireFox`
2. Click on `Firefox -> Preferences -> Languages & Appearance -> Colours...`
3. For `Override the colours...` select `Always` and then click `OK`
4. Visit https://www.bbc.co.uk/news/articles/c8xxl4l3dzeo
5. See error as Brand isn't visible 

**Expected behaviour**
I should still be able to see the brand SVG when:

1. User has changed colour preferences in Firefox (including with a white background)
2. User has no CSS
3. User has selected a High Contrast mode on PC with a white background and also a custom mode  (Point 4 on https://bbc-news.github.io/accessibility-news-and-you/accessibility-news-and-testers)
4. Low priority but ideally you should still be able to see the logo when printing an article - We already have some CSS for this - which should be unaffected if applying the recommended fix in the [comment below](https://github.com/bbc/psammead/issues/736#issuecomment-507324293) https://github.com/bbc/psammead/blob/latest/packages/components/psammead-brand/src/index.jsx#L72

**Screenshots**
![image](https://user-images.githubusercontent.com/7791726/60437423-32f27c80-9c06-11e9-91dd-d579a086bb61.png)

**Additional context**
As this bug is due to FireFox override the CSS styles we have defined for the page there might not be an easy fix. Ideally we would need something on the page to indicate that the styles have been overridden.

**Comment by greenc05** [comment]
We could try applying `fill: currentColor` instead of `fill: rgb(255, 255, 255)` to the SVG to fix this. May also need to apply a colour of white to the wrapping link... Remember to ensure this can also still be seen in High contrast mode on PC, as well as with CSS turned off.

**Comment by jamesbhobbs** [comment]
@greenc05 you're not in today to discuss, my view.... I think this is probably a P2 priority issue (where P1 is highest for anyone unfamiliar with our grading system). It's clearly P1 when it occurs, but it only occurs when colour-preferences are changed. Nevertheless P2 means we need to fix urgently, so we will get someone to look at it soon. 

PS I believe this would also affect WS front pages in simorgh which will go live soon with a far larger audience.

**Comment by dr3** [comment]
@benjaminhobbs It does cover WS (soz i removed the label to avoid confusion with `high priority` label) @greenc05 Agreed that is isn't an immediate issue for frontpages due to our inclusion of the Nav

**Comment by j-pendlebury** [comment]
Could this potentially be fixed by https://github.com/bbc/psammead/pull/704? 

Currently `psammead-brand` is using an old version of `psammead-assets`, which does not contain the changes made in PR above.

**Comment by pjlee11** [comment]
@jblaut Potentially, definitely worth investigating
