### ISSUE TITLE
IOS brand link splitting

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#743]
**Describe the bug**
On Safari IOS voiceover the brand link is read out as
```
'BBC news, link, banner, landmark'
'comma, link'
'igbo, link' 
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Use voice over on IOS on safari 
2. Visit stage.bbc.com/igbo
3. hear error

**Expected behaviour**
It reads out `BBC news, Igbo, link, banner, landmark`

**Smartphone (please complete the following information):**

- Device: iPhoneXS
- OS: iOS12.1
- Browser: Safari
- Version: Whatever it comes with

**Additional context**

**Comment by greenc05** [comment]
Applying `role="text"` to the visually hidden span or adding a span that contains the visually hidden span with `role="text"` applied this should fix this
