### ISSUE TITLE
Psammead storybook prop types warnings

### ISSUE THREAD

**Issue by andrew-nowak** [BBC-archive/psammead#754]
**Is your feature request related to a problem? Please describe.**
Multiple stories are emitting prop type warnings to the console.

#### Brand/without brand link

` The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".`

#### Figure/containing Image, ImagePlaceholder, Copyright and Caption

``Warning: Failed prop type: The prop `script` is marked as required in `Paragraph`, but its value is `undefined`.``

#### Moment locales/ig

```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <Table>. See https://fb.me/react-warning-keys for more information.
    in tr
```
    
```
Warning: validateDOMNesting(...): <tr> cannot appear as a child of <table>. Add a <tbody> to your code to match the DOM tree generated by the browser.
    in tr
    in table (created by Context.Consumer)
    in StyledComponent (created by Table)
    in Table
```

**Describe the solution you'd like**
Fix these prop type warnings.

**Describe alternatives you've considered**
😢 

**Testing notes**
[Tester to complete]

Dev insight: Inspection of console while browsing storybook

**Comment by j-pendlebury** [comment]
Include any other existing propType warnings that you seen which are not mentioned in the issue

**Comment by j-pendlebury** [comment]
Refined by ws-frontpages

**Comment by Bopchy** [comment]
`The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".` has been highlighted here - https://github.com/storybookjs/storybook/issues/6998, as an issue that came about from updating Storybook to version 5.
