### ISSUE TITLE
Change input provider to use services, not languages

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#759]
**Is your feature request related to a problem? Please describe.**
Our input provider currently asks you to change the language, we should update it to say services

**Describe the solution you'd like**
Update use of word 'language' to say 'service'
Ensure `text-variants.js` only includes services, not languages

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by andrew-nowak** [comment]
Closing as done 

![image](https://user-images.githubusercontent.com/10963046/60825275-399f6780-a1a3-11e9-9b9f-ad774302a191.png)
<https://bbc.github.io/psammead/>
