### ISSUE TITLE
Brand breakpoint s 399/400 instead of 599/600

### ISSUE THREAD

**Issue by david-boydell** [BBC-archive/psammead#762]
**Describe the bug**
The padding and height of the Branding should change between 599 and 600px. Currently this breakpoint is set at 399/400.

**To Reproduce**
Steps to reproduce the behaviour:

1. Checkout `latest` and kick off Storybook
2. View http://localhost:8180/iframe.html?id=components-brand--without-brand-link
3. Reduce innerWidth to 400px
4. Reduce innerWidth to 399px

**Expected behaviour**
The change in the representation should have occurred between 599px and 600px, instead of 399px and 400px

**Desktop (please complete the following information):**

- OS: All
- Browser All
- Version All

**Additional context**
Zeplin doc here: https://app.zeplin.io/project/5c8a5e021d454124ef90669f/dashboard?seid=5c8bdfde9e37ea24d7fd2377

**Comment by dr3** [comment]
🙈 The zeplin is wrong we moved to 400px switch in https://github.com/bbc/psammead/pull/684

**Comment by david-boydell** [comment]
Agreed with UX that this should remain 399/400
