### ISSUE TITLE
Allow limiting dir decorator per service

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#770]
**Is your feature request related to a problem? Please describe.**
Following https://github.com/bbc/psammead/pull/758 the input provider can be limited to a subset of services.

**Describe the solution you'd like**
Decide on a new API and allow passing a subset of services.

We will likely need to create a function that returns a Decorator, as decorators only accept the `storyFn` prop by default.

**Testing notes**
[Tester to complete]

Dev insight: Test in storybook, a story will have a restricted list of services to pick.

**Additional context**

**Comment by thekp** [comment]
I believe this issue is not required as functionality can be done through the inputProvider. 

In additional, to filter out the services through the dirDecorator still requires knowledge of services and this is already implemented in the inputProvider.
