### ISSUE TITLE
Review and Improve package structure

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#78]
**Is your feature request related to a problem? Please describe.**
@ChrisBAshton raised in this thread https://github.com/BBC-News/psammead/pull/74#discussion_r237375529 that the way our utilities packages are structured isn't ideal and can be improved.

**Describe the solution you'd like**
Evaluate, propose and implement a better package structure to give the most freedom, clarity and modern principles to our packages and their creators.

**Describe alternatives you've considered**
Leaving as is

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by jamesdonoh** [comment]
The requirements and justification for 'improvement' on this issue are not clearly defined or described, so we're closing it.
