### ISSUE TITLE
Update the Psammead README

### ISSUE THREAD

**Issue by radiocontrolled** [BBC-archive/psammead#85]
**Is your feature request related to a problem? Please describe.**
On the 30 November WS / Reach and Languages / Articles sharing day, we identified that need a comprehensive README for Psammead to describe the project and encourage collaboration on it.

**Describe the solution you'd like**
In addition to details of installation & use, the README should cover the following territory:
```
  - What is Psammead? What should be included in this resource? Explanation of: 
    - Utilities
    - Components - only presentational components. What does this mean?
    - Contexts ()
    - Themes (not yet added)
  - What isn’t Psammead? 
    - Which global styles should you apply? (see issue #87)
    - Where should you include containers? 
    - What happens to very product-specific components? 
    - Psammead is not a place for business logic
  - Build process
  - Publish process
  - a11y 
    - considerations section about taking into account a11y when you are implementing a
   component (e.g., landmark roles)
  - Contact details, e.g. 
   -  "This is currently maintained by developers in Articles, Reach + Languages, who are accessible via PsammeadMaintainers@bbc.co.uk", possibly Slack

```
See this [living discussion on dropbox](https://paper.dropbox.com/doc/Psammead--AS3SCuFNDKWwnJF5Hihn4dWTAg-o19T5ZEB6UeKTw1INSSmC) for more detail: 

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
```
# What is Psammead?
  - Name!
  - Utilities
  - Components - only presentational components. What does this mean?

# What isn’t Psammead? 
  - Global styles you should define (see issue #87)
  - Psammead is not a place for business logic - explain containers
    - Give an example of how to combine components
    -  e.g. FooterContainer, and link to Simorgh and have an inline example.
  - What happens to very product-specific components?  

# Build process

# Publish process

# Browser and accessibility support

# Contact details
```

**Comment by pjlee11** [comment]
As a group we've decided the following:

We should open an issue for each of the following:
- Name! (could)
- Utilities (should)
- Components - only presentational components. What does this mean? (must)
- Global styles you should define (see issue #87) (must)
- Psammead is not a place for business logic - explain containers (should)
- Give an example of how to combine components (should)
- What happens to very product-specific components? (alpha-3: should)
- ~Build process~ Local setup (must) - how to run tests
- Browser and accessibility support (should)
- Contact details (must)

Also follow up tickets to:
- Evaluate publish process (alpha-2 could)

**Comment by pjlee11** [comment]
Following the above, we have created these issues:

- [Naming](https://github.com/BBC-News/psammead/issues/11)
- [Utilities](https://github.com/BBC-News/psammead/issues/140)
- [Components](https://github.com/BBC-News/psammead/issues/137)
- [Global styles](https://github.com/BBC-News/psammead/issues/139)
- [Component usage](https://github.com/BBC-News/psammead/issues/141)
- [Product-specific components](https://github.com/BBC-News/psammead/issues/149)
- ~Build process~ [Getting started](https://github.com/BBC-News/psammead/issues/145)
- [Browser and accessibility support](https://github.com/BBC-News/psammead/issues/98)
- [Contact details](https://github.com/BBC-News/psammead/issues/135)
- [Evaluate publish process](https://github.com/BBC-News/psammead/issues/136)
