### ISSUE TITLE
Update styled components attrs property

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#86]
**Describe the bug**
Styled components now throws a warning on the headers component

**To Reproduce**

1. Go to psammead once https://github.com/BBC-News/psammead/pull/79 is merged
2. Run `npm test`

```
Functions as object-form attrs({}) keys are now deprecated and will be removed in a future version of styled-components. Switch to the new attrs(props => ({})) syntax instead for easier and more powerful composition. The attrs key in question is "id" on component "styled.h2".
```

**Expected behavior**
It doesn't show error

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/psammead/labels/bug)

**Comment by bcmn** [comment]
![image](https://user-images.githubusercontent.com/11646957/49449116-1a39f980-f7d2-11e8-954e-4ec443f7d35a.png)

[Details from the styled-components changelog](https://github.com/styled-components/styled-components/blob/master/CHANGELOG.md).
