### ISSUE TITLE
Readme explanation of Global Styles needed for components

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#87]
**Is your feature request related to a problem? Please describe.**
We currently need Global Styles in our application, that includes the normalise, border-box and font face declarations.  
In a future issue, we will make these available as part of our Psammead utilities e.g. in `@bbc/gel-foundations-styled-components`.

For now, we should document how one should set up global styles to ensure Psammead components will have the correct fonts and normalisation: 
https://github.com/BBC-News/simorgh/blob/latest/src/app/lib/globalStyles.js

**Describe the solution you'd like**
To have a clear section in the top-level README.md's usage instructions. 

**Describe alternatives you've considered**
N/A

**Testing notes**
The Readme should make sense to someone unfamiliar with Psammead

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
This can be incorporated in #85.
