### ISSUE TITLE
Migrate SitewideLinks Component to Psammead

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#90]
**Is your feature request related to a problem? Please describe.**
We are creating a SitewideLinks component in https://github.com/BBC-News/simorgh/issues/1034, once this has been done we should migrate it to psammead 

Corresponding issue in Simorgh: https://github.com/BBC-News/simorgh/issues/1060

**Testing notes**
Storybook should still work, tests should still pass, and SiteWideLinks should be viewable in Storybook.

**Describe the solution you'd like**
Copy SitewideLinks into psammead as a new package

- [ ] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by dr3** [comment]
https://github.com/BBC-News/simorgh/pull/1045 is about to be merged so this is good to go

**Comment by PriyaKR** [comment]
LGTM
