### ISSUE TITLE
Promote story promo out of alpha

### ISSUE THREAD

**Issue by andrew-nowak** [BBC-archive/psammead#933]
**Is your feature request related to a problem? Please describe.**
It's still marked as alpha

**Describe the solution you'd like**
It's no longer marked as alpha

**Describe alternatives you've considered**
Going live with an 'alpha' component

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by j-pendlebury** [comment]
Much description. Such words
