### ISSUE TITLE
Footer - Copyright text is always in English

### ISSUE THREAD

**Issue by greenc05** [BBC-archive/psammead#934]
~Blocked on [simorgh/2667](https://github.com/bbc/simorgh/issues/2667)~

**Is your feature request related to a problem? Please describe.**
The copyright text in the footer is always in English regardless of the service.

**Describe the solution you'd like**
Add an English language attribute around this content. ``` <span lang="en-GB">© 2019 BBC.</span> ``` so the accessibility acceptance criteria is met "All content not in the main language of the page must have the correct lang attribute"

**Describe alternatives you've considered**

**Testing notes**
The copyright information should be announced with an english accent when using a screen reader

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

**Comment by j-pendlebury** [comment]
Refined by WS-FP pod

**Comment by sareh** [comment]
Note: for services that have scripts which are right-to-left, this should also have the attribute `dir="ltr"`.

**Comment by EinsteinNjoroge** [comment]
@greenc05 Looking at the services config files, the copyright text for most services appears as just `© 2019` without the word `BBC`. Should we make this uniform i.e _dynamically add the word BBC to the services that don't have it?_

**Comment by sareh** [comment]
@EinsteinCarrey I believe the word BBC is translated for several services - e.g. for Persian it is 
<span dir="rtl">بی بی سی</span>

@greenc05 I'd suggest that we should actually fully translate the numerals to use the numbers in the correct script, since we are doing so for dates, and Most Read numbers as well.  I am not sure that it is required to enforce English around the BBC in the copyright. 

e.g. currently on Persian: (Copyright symbol,  2019, BBC.)
<img width="109" alt="Screen Shot suggested approach" src="https://user-images.githubusercontent.com/3028997/61639107-bc8bec00-ac92-11e9-8c6b-9c1ce12172d4.png">

With corrected numerals:
<img width="109" alt="Screen Shot current approach" src="https://user-images.githubusercontent.com/3028997/61639106-bc8bec00-ac92-11e9-8f93-e9c65a3272f4.png">

As a result, the lang attribute does not need adding.

**Comment by EinsteinNjoroge** [comment]
@sareh I concur with fully translating the numerals.
My concern, however, is about the word `BBC` which doesn't appear in the copyright text for some services such as `Swahili, Hindi, Rusian, Serbian  _etc.._.`. Should we introduce it dynamically?

**Comment by greenc05** [comment]
I've asked Laura/UX to advise....

**Comment by laurapsn** [comment]
@EinsteinCarrey the BBC label is currently not translated but transliterated for non-Latin languages e.g. Russian BBC > Би-би-си

@sareh I agree, especially now that we have Persian numbers in the Most read components, it is worth using numbers in the correct script. 

Having said that, in my opinion the Lang attribute should still be valid for Copyright, where you may not want to translate _Copyright_ to _Derecho de autor_ in Spanish. @greenc05

**Comment by EinsteinNjoroge** [comment]
@sareh @laurapsn I've included these two screenshots from `igbo` and `russian` service respectively. Note that one has the word `BBC` in the copyright text and the disclaimer while the other only has `BBC` in the disclaimer.
(_NB: I used google translate to display them in English_)

![Screen Shot 2019-07-23 at 11 16 28 AM](https://user-images.githubusercontent.com/21374761/61695279-e51bf080-ad3b-11e9-8261-fc91c3aba1cb.png)
![Screen Shot 2019-07-23 at 11 16 19 AM](https://user-images.githubusercontent.com/21374761/61695280-e51bf080-ad3b-11e9-8ab6-8781e70a2c74.png)

**Comment by sareh** [comment]
@EinsteinCarrey Thanks for the examples you've included - yes there are inconsistencies within the translation text, which should be addressed first, so all services have the same structure of `copyright symbol year BBC.`, then the separate disclaimer sentence. 
Then after that, the work can be done. 

@laurapsn - there needs to be the `BBC` mentioned twice. Once is for the `BBC.` in the `© 2019 BBC. `. Then it is also needed for the Disclaimer sentence. e.g. for Russian it should be `'Би-би-си. Би-би-си не несет ответственности за содержание других сайтов.',`
This then shows up online as `© 2019 Би-би-си. Би-би-си не несет ответственности за содержание других сайтов.',`

**Comment by EinsteinNjoroge** [comment]
Following  [Laura's comment ](https://github.com/bbc/psammead/issues/934#issuecomment-513849903), I'll add the English language attribute around the copyright only since the numerals in the year will be translated.
