### ISSUE TITLE
Deep snapshots have ForwardRef instead of component names

### ISSUE THREAD

**Issue by bcmn** [BBC-archive/psammead#95]
**Describe the bug**
When using deep rendering with `styled-components` V4, snapshot references to other React components are replaced with `<ForwardRef />`. [An example of this is visible in the original Simorgh PR for styled-components V4](https://github.com/BBC-News/simorgh/pull/695/files#diff-21c2870128b7d951044c5459438579f6).

Luckily, as most Psammead components are currently only composed to a depth of 1, this isn't yet visible in this repo. However, it will become an issue as we introduce more complex or nested components.

**Possible Solutions/Approaches**
This issue is caused by our dependency `jest-styled-components`. If we stick with using jest-styled-components alone, we will have to await or contribute to their resolution of this issue. They have a [ticket on it here](https://github.com/styled-components/jest-styled-components/issues/191). We could potentially contribute to the PRs that spawn out of it if we considered it a high priority.

Alternatively, if we are evaluating using Enzyme or react-testing-library alongside jest-styled-components, one of the benefits from either of these moves would be that this would no longer be an issue.

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/psammead/labels/bug)

**Comment by ChrisBAshton** [comment]
Superseded by #273.
