### ISSUE TITLE
Add Browser Support Table to Psammead

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#98]
**Is your feature request related to a problem? Please describe.**
We currently do not have any reference to our Browser support support list within Psammead.

We should add it to the Psammead Readme.md

**Describe the solution you'd like**
We would like to add a high-level summary of Browser Support support into Psammead, using this as an example:
https://github.com/alphagov/govuk-frontend#browser-support

@pjlee11 created a browser support matrix based on a 0.05% metric, and put this browser support matrix below:

| Browser           | Lowest version    |
| ----------------- | ---------- |
| Safari           | 7    |
| Facebook for iPhone           | 187    |
| Chrome for iOS           | 68    |
| Chrome           | 25    |
| Edge           | 14    |
| Firefox           | 48    |
| IE           | 9    |
| Amazon Silk           | 69    |
| Opera Mini           | 4    |
| Android Browser           | 4    |
| Nokia           | 6280    |
| Firefox for iOS           | 13    |
| Facebook for Android           | 190    |

We should add this matrix to the README, with a note that we don't actually support it yet but that this level of support is an aspiration for v1.

**Describe alternatives you've considered**
We could have the browser support in another file or another repository. 

**Testing notes**
[Tester to complete]

Dev insight: This is documentation. It should be easily understood by Devs, Testers, Product Owners, UX Designers & Business Analysts. 

**Context**
Analysis of existing documentation and resources:

- We have Browser stats for the News site, but they're not granular enough for our purposes https://docs.google.com/spreadsheets/d/1X6e7_3XCtUN9SFsMrSFCUMbl6KOjkTdS6Su9RcAJlBc/edit 
- We have a more detailed breakdown of browser stats that are exported from Comscore into a spreadsheet - `browsers-2018-08-09.xlsx`  (File removed, due to reasoning here: https://github.com/BBC-News/psammead/issues/98#issuecomment-444129534)

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by sareh** [comment]
Working on this is blocked on receiving up-to-date browser stats from Comscore from @jimjohnsonrollings.

**Comment by sareh** [comment]
It was agreed that we should add browser stats as percentages, rather than exact numbers. 
This Issue is blocked from being picked up, pending getting these %-based stats added to this issue. cc @pjlee11

**Comment by ChrisBAshton** [comment]
In future, we'll split into:

* (for launch) Find out what browsers we need to support - 0.05%, put it in an issue - then put in a README, with a note that we don't actually support it yet but it's an aspiration for v1.

In future:
* Test & verify each component in each browser (probably itself needs multiple issues)
* Update the browser stats somewhere public every month.

**Comment by pjlee11** [comment]
The following values are produced using [Browser Stats Percentage](https://github.com/pjlee11/browser-stats-percentage). To reproduce clone the repo, follow setup instructions, provide real data and run `npm run getLowestSupportedBrowserVersion`. 

Stats used in this instance were from Oct 2018

| Service                     | Browser           | Lowest version    |
| --------------------------- | ----------------- | ---------- |
| news        | Safari           | 0    |
| news        | Facebook for iPhone           | 187    |
| news        | Chrome for iOS           | 69    |
| news        | Chrome           | 25    |
| news        | Edge           | 14    |
| news        | Firefox           | 48    |
| news        | IE           | 11    |
| news        | Facebook for Android           | 191    |
| news        | Amazon Silk           | 69    |
| news        | Opera Mini           | 4    |
| news        | Android Browser           | 4    |
| news        | Nokia           | 6280    |

| Service                     | Browser           | Lowest version    |
| --------------------------- | ----------------- | ---------- |
| news-ws-persian        | Safari           | 0    |
| news-ws-persian        | Chrome for iOS           | 68    |
| news-ws-persian        | Facebook for iPhone           | 189    |
| news-ws-persian        | Firefox for iOS           | 13    |
| news-ws-persian        | Chrome           | 28    |
| news-ws-persian        | Edge           | 14    |
| news-ws-persian        | Firefox           | 52    |
| news-ws-persian        | IE           | 9    |
| news-ws-persian        | Facebook for Android           | 190    |
| news-ws-persian        | Android Browser           | 4    |
| news-ws-persian        | Opera Mini           | 4    |

NB: The `Safari` version of 0 is reported as there is an entry in the data with the "Browser name" set as "Safari" where the majority follow a different format of "Safari 8.x". I am separately following this up

**Comment by ChrisBAshton** [comment]
Thanks Phil - great work. So the lowest common denominator for both is this:

| Browser           | Lowest version    |
| ----------------- | ---------- |
| Safari           | 0    |
| Facebook for iPhone           | 187    |
| Chrome for iOS           | 68    |
| Chrome           | 25    |
| Edge           | 14    |
| Firefox           | 48    |
| IE           | 9    |
| Amazon Silk           | 69    |
| Opera Mini           | 4    |
| Android Browser           | 4    |
| Nokia           | 6280    |
| Firefox for iOS           | 13    |
| Facebook for Android           | 190    |

So we're saying all components should ideally be tested in the above browsers ^.

Can you open a PR that adds that to the README? (I guess we need to nail what "Safari 0" means too).

**Comment by pjlee11** [comment]
It seems that our stats provider will return `Safari` if it can't recognise a version so as a team we will need to decide how we interpret this value as `Safari 0` does not exist. 

My personal opinion would be to not include entries without versions (unless it is the only version that exists for the browser)

**Comment by ChrisBAshton** [comment]
I'd say we should keep it but have version as `Latest` (we know our audience uses Safari, we just can't pin down an exact version. So rather than neglect the browser entirely, have it in the list but don't commit to a version).

**Comment by pjlee11** [comment]
I've changed the defaulting `0` to be `misc` for the following use case for clarity:

| Service                     | Browser           | Versions    |
| --------------------------- | ----------------- | ---------- |
| news        | Safari           | 7, 8, 9, 10, 11, 12, misc   |

Given this I'm going to omit `misc` enteries unless they are the only entry for that browser as we do not want to lose an entire browser report just because we can't identify the version

**Comment by pjlee11** [comment]
Therefore /news support would be:

| Service                     | Browser           | Versions    |
| --------------------------- | ----------------- | ---------- |
| news        | Safari           | 7, 8, 9, 10, 11, 12    |
| news        | Facebook for iPhone           | 187, 189, 190, 191, 192, 193, 194, 195    |
| news        | Chrome for iOS           | 69, 70    |
| news        | Chrome           | 25, 30, 34, 38, 43, 44, 49, 50, 52, 53, 55, 56, 57, 59, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70    |
| news        | Edge           | 14, 15, 16, 17, 18    |
| news        | Firefox           | 48, 52, 60, 62, 63    |
| news        | IE           | 11    |
| news        | Facebook for Android           | 191, 192, 193, 194, 195    |
| news        | Amazon Silk           | 69    |
| news        | Opera Mini           | 4, 7, 36    |
| news        | Android Browser           | 4    |
| news        | Nokia           | 6280    |

Then with only the lowest version we should support: 

| Service                     | Browser           | Lowest version    |
| --------------------------- | ----------------- | ---------- |
| news        | Safari           | 7    |
| news        | Facebook for iPhone           | 187    |
| news        | Chrome for iOS           | 69    |
| news        | Chrome           | 25    |
| news        | Edge           | 14    |
| news        | Firefox           | 48    |
| news        | IE           | 11    |
| news        | Facebook for Android           | 191    |
| news        | Amazon Silk           | 69    |
| news        | Opera Mini           | 4    |
| news        | Android Browser           | 4    |
| news        | Nokia           | 6280    |

**Comment by ChrisBAshton** [comment]
Great - I recommend we strip out 'service' when we add to the README, as consumers won't particularly care where we get our stats from:

| Browser           | Lowest version    |
| ----------------- | ---------- |
| Safari           | 7    |
| Facebook for iPhone           | 187    |
| Chrome for iOS           | 68    |
| Chrome           | 25    |
| Edge           | 14    |
| Firefox           | 48    |
| IE           | 9    |
| Amazon Silk           | 69    |
| Opera Mini           | 4    |
| Android Browser           | 4    |
| Nokia           | 6280    |
| Firefox for iOS           | 13    |
| Facebook for Android           | 190    |

**Comment by ChrisBAshton** [comment]
Do we have enough refinement to raise a PR now? :)

**Comment by pjlee11** [comment]
RE: stripping out service - That depends, because when we start adopting psammead for Persian articles the support tables will be very different so we could do that in the short term but in the medium to long-term we will need to know the various different services support models

**Comment by ChrisBAshton** [comment]
Remember that this is like the accessibility support table - it's a quick at-a-glance "these are the browsers/technologies our components support, but check the individual READMEs" rather than a "this is how we arrived at our support table" (which might be best covered in the CONTRIBUTING.md separately). Although I'd add a little sentence in for context.

So I'd recommend for a PR in the main README:

```
these are the browsers/technologies our components support, but check the individual READMEs

TABLE

Note that these browser support levels have been defined by usage statistics for BBC News and BBC Persian.
```

**Comment by pjlee11** [comment]
Persian is even lower FYI, that's why I added the distinction 

| Service                     | Browser           | Versions    |
| --------------------------- | ----------------- | ---------- |
| news-ws-persian        | Safari           | 7    |
| news-ws-persian        | Chrome for iOS           | 68    |
| news-ws-persian        | Facebook for iPhone           | 189    |
| news-ws-persian        | Firefox for iOS           | 13    |
| news-ws-persian        | Chrome           | 28    |
| news-ws-persian        | Edge           | 14    |
| news-ws-persian        | Firefox           | 52    |
| news-ws-persian        | IE           | 9    |
| news-ws-persian        | Facebook for Android           | 190    |
| news-ws-persian        | Android Browser           | 4    |
| news-ws-persian        | Opera Mini           | 4    |

**Comment by ChrisBAshton** [comment]
I've got the lowest combination for both in https://github.com/BBC-News/psammead/issues/98#issuecomment-447841119
